<a href="https://colab.research.google.com/github/Naga-SDonepudi/nlp_for_ml/blob/main/Sentiment_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Sentiment Analysis
### Dataset

In [68]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

kindle_data = pd.read_csv("all_kindle_review.csv")

In [69]:
kindle_data

,Unnamed: 0.1,Unnamed: 0,asin,helpful,rating,reviewText,reviewTime,reviewerID,reviewerName,summary,unixReviewTime
0,0,11539,B0033UV8HI,"[8, 10]",3,"Jace Rankin may be short, but he's nothing to ...","09 2, 2010",A3HHXRELK8BHQG,Ridley,Entertaining But Average,1283385600
1,1,5957,B002HJV4DE,"[1, 1]",5,Great short read. I didn't want to put it dow...,"10 8, 2013",A2RGNZ0TRF578I,Holly Butler,Terrific menage scenes!,1381190400
2,2,9146,B002ZG96I4,"[0, 0]",3,I'll start by saying this is the first of four...,"04 11, 2014",A3S0H2HV6U1I7F,Merissa,Snapdragon Alley,1397174400
3,3,7038,B002QHWOEU,"[1, 3]",3,Aggie is Angela Lansbury who carries pocketboo...,"07 5, 2014",AC4OQW3GZ919J,Cleargrace,very light murder cozy,1404518400
4,4,1776,B001A06VJ8,"[0, 1]",4,I did not expect this type of book to be in li...,"12 31, 2012",A3C9V987IQHOQD,Rjostler,Book,1356912000
...,...,...,...,...,...,...,...,...,...,...,...
11995,11995,2183,B001DUGORO,"[0, 0]",4,Valentine cupid is a vampire- Jena and Ian ano...,"02 28, 2014",A1OKS5Q1HD8WQC,lisa jon jung,jena,1393545600
11996,11996,6272,B002JCSFSQ,"[2, 2]",5,I have read all seven books in this series. Ap...,"05 16, 2011",AQRSPXLNEQAMA,TerryLP,Peacekeepers Series,1305504000
11997,11997,12483,B0035N1V7K,"[0, 1]",3,This book really just wasn't my cuppa. The si...,"07 26, 2013",A2T5QLT5VXOJAK,hwilson,a little creepy,1374796800
11998,11998,3640,B001W1XT40,"[1, 2]",1,"tried to use it to charge my kindle, it didn't...","09 17, 2013",A28MHD2DDY6DXB,"Allison A. Slater ""Gryphon50""",didn't work,1379376000
11999,11999,11398,B003370JUS,"[5, 6]",3,Taking Instruction is a look into the often hi...,"07 5, 2012",A3JUXLB4K9ZXCC,Dafna Yee,"If you like BDSM with a touch of romance, this...",1341446400

In [70]:
kindle_data.head()

,Unnamed: 0.1,Unnamed: 0,asin,helpful,rating,reviewText,reviewTime,reviewerID,reviewerName,summary,unixReviewTime
0,0,11539,B0033UV8HI,"[8, 10]",3,"Jace Rankin may be short, but he's nothing to ...","09 2, 2010",A3HHXRELK8BHQG,Ridley,Entertaining But Average,1283385600
1,1,5957,B002HJV4DE,"[1, 1]",5,Great short read. I didn't want to put it dow...,"10 8, 2013",A2RGNZ0TRF578I,Holly Butler,Terrific menage scenes!,1381190400
2,2,9146,B002ZG96I4,"[0, 0]",3,I'll start by saying this is the first of four...,"04 11, 2014",A3S0H2HV6U1I7F,Merissa,Snapdragon Alley,1397174400
3,3,7038,B002QHWOEU,"[1, 3]",3,Aggie is Angela Lansbury who carries pocketboo...,"07 5, 2014",AC4OQW3GZ919J,Cleargrace,very light murder cozy,1404518400
4,4,1776,B001A06VJ8,"[0, 1]",4,I did not expect this type of book to be in li...,"12 31, 2012",A3C9V987IQHOQD,Rjostler,Book,1356912000

In [71]:
kindle_data.tail()

,Unnamed: 0.1,Unnamed: 0,asin,helpful,rating,reviewText,reviewTime,reviewerID,reviewerName,summary,unixReviewTime
11995,11995,2183,B001DUGORO,"[0, 0]",4,Valentine cupid is a vampire- Jena and Ian ano...,"02 28, 2014",A1OKS5Q1HD8WQC,lisa jon jung,jena,1393545600
11996,11996,6272,B002JCSFSQ,"[2, 2]",5,I have read all seven books in this series. Ap...,"05 16, 2011",AQRSPXLNEQAMA,TerryLP,Peacekeepers Series,1305504000
11997,11997,12483,B0035N1V7K,"[0, 1]",3,This book really just wasn't my cuppa. The si...,"07 26, 2013",A2T5QLT5VXOJAK,hwilson,a little creepy,1374796800
11998,11998,3640,B001W1XT40,"[1, 2]",1,"tried to use it to charge my kindle, it didn't...","09 17, 2013",A28MHD2DDY6DXB,"Allison A. Slater ""Gryphon50""",didn't work,1379376000
11999,11999,11398,B003370JUS,"[5, 6]",3,Taking Instruction is a look into the often hi...,"07 5, 2012",A3JUXLB4K9ZXCC,Dafna Yee,"If you like BDSM with a touch of romance, this...",1341446400

In [72]:
kindle_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12000 entries, 0 to 11999
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0.1    12000 non-null  int64
 1   Unnamed: 0      12000 non-null  int64
 2   asin            12000 non-null  object
 3   helpful         12000 non-null  object
 4   rating          12000 non-null  int64
 5   reviewText      12000 non-null  object
 6   reviewTime      12000 non-null  object
 7   reviewerID      12000 non-null  object
 8   reviewerName    11962 non-null  object
 9   summary         11998 non-null  object
 10  unixReviewTime  12000 non-null  int64
dtypes: int64(4), object(7)
memory usage: 1.0+ MB

* For sentiment analysis, the important features from the dataset were rating and review text
* Reading those two columns and creating a seperate dataset

In [73]:
## reading Rating and Review test data, then saving to kindle_data
kindle_df = kindle_data[["rating", "reviewText"]]

In [74]:
kindle_df.head()

   rating                                         reviewText
0       3  Jace Rankin may be short, but he's nothing to ...
1       5  Great short read.  I didn't want to put it dow...
2       3  I'll start by saying this is the first of four...
3       3  Aggie is Angela Lansbury who carries pocketboo...
4       4  I did not expect this type of book to be in li...

In [75]:
kindle_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12000 entries, 0 to 11999
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   rating      12000 non-null  int64
 1   reviewText  12000 non-null  object
dtypes: int64(1), object(1)
memory usage: 187.6+ KB

In [76]:
print("Length of Dataset: ", len(kindle_df))
print("Shape: ", kindle_df.shape)

Length of Dataset:  12000
Shape:  (12000, 2)

In [77]:
## Checking the missing values
kindle_df.isnull().sum()

rating        0
reviewText    0
dtype: int64

In [78]:
## Checking the unique values, and frequencly of each value
kindle_df["rating"].unique()

array([3, 5, 4, 2, 1])

In [79]:
kindle_df["rating"].nunique()

5

In [80]:
kindle_df["rating"].value_counts()

rating
5    3000
4    3000
3    2000
2    2000
1    2000
Name: count, dtype: int64

### Feature Engineering
* Categorizing the ratings as 0 (if rating less than 3) and 1 (if rating greater than 3)

In [81]:
kindle_df.loc[:, "rating"] = kindle_df["rating"].apply(lambda a:0 if a<3 else 1)

In [82]:
kindle_df.head()

   rating                                         reviewText
0       1  Jace Rankin may be short, but he's nothing to ...
1       1  Great short read.  I didn't want to put it dow...
2       1  I'll start by saying this is the first of four...
3       1  Aggie is Angela Lansbury who carries pocketboo...
4       1  I did not expect this type of book to be in li...

In [83]:
kindle_df.tail()

       rating                                         reviewText
11995       1  Valentine cupid is a vampire- Jena and Ian ano...
11996       1  I have read all seven books in this series. Ap...
11997       1  This book really just wasn't my cuppa.  The si...
11998       0  tried to use it to charge my kindle, it didn't...
11999       1  Taking Instruction is a look into the often hi...

In [84]:
kindle_df["rating"].value_counts()

rating
1    8000
0    4000
Name: count, dtype: int64

### preprocessing the ratingText data

In [86]:
kindle_df.loc[:, "reviewText"] = kindle_df["reviewText"].str.lower()
kindle_df["reviewText"]

0        jace rankin may be short, but he's nothing to ...
1        great short read.  i didn't want to put it dow...
2        i'll start by saying this is the first of four...
3        aggie is angela lansbury who carries pocketboo...
4        i did not expect this type of book to be in li...
                               ...
11995    valentine cupid is a vampire- jena and ian ano...
11996    i have read all seven books in this series. ap...
11997    this book really just wasn't my cuppa.  the si...
11998    tried to use it to charge my kindle, it didn't...
11999    taking instruction is a look into the often hi...
Name: reviewText, Length: 12000, dtype: object

* Cleaning the data by removing special characters

In [94]:
import nltk
import re
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
nltk.download('wordnet')
nltk.download('stopwords')
from bs4 import BeautifulSoup

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [89]:
kindle_df.loc[:, 'reviewText']=kindle_df['reviewText'].apply(lambda x:re.sub('[^a-z A-z 0-9-]+', '',x))
## Removing the stopswords
kindle_df.loc[:, 'reviewText']=kindle_df['reviewText'].apply(lambda x:" ".join([y for y in x.split() if y not in stopwords.words('english')]))
## Removing url
kindle_df.loc[:, 'reviewText']=kindle_df['reviewText'].apply(lambda x: re.sub(r'(http|https|ftp|ssh)://([\w_-]+(?:(?:\.[\w_-]+)+))([\w.,@?^=%&:/~+#-]*[\w@?^=%&/~+#-])?', '' , str(x)))
## Removing html tags
kindle_df.loc[:, 'reviewText']=kindle_df['reviewText'].apply(lambda x: BeautifulSoup(x, 'lxml').get_text())
## Removing additional spaces
kindle_df.loc[:, 'reviewText']=kindle_df['reviewText'].apply(lambda x: " ".join(x.split()))

In [90]:
kindle_df.head(10)

   rating                                         reviewText
0       1  jace rankin may short hes nothing mess man hau...
1       1  great short read didnt want put read one sitti...
2       1  ill start saying first four books wasnt expect...
3       1  aggie angela lansbury carries pocketbooks inst...
4       1  expect type book library pleased find price right
5       1  aislinn little girl big dreams death older bro...
6       0  makings good story unfortunately disappointsit...
7       1  got like collaborated short stories alot times...
8       1  loved book hooked series hope kelsey maxwell r...
9       1  thats good thing short sweet tease gives every...

### Leammatization

In [91]:
### Initializing
lemmatizer = WordNetLemmatizer()

In [92]:
def word_lemmatizer(text):
  return " ".join([lemmatizer.lemmatize(word) for word in text.split()])

In [95]:
kindle_df.loc[:, "reviewText"] = kindle_df["reviewText"].apply(lambda a:word_lemmatizer(a))

In [97]:
kindle_df.head(10)

   rating                                         reviewText
0       1  jace rankin may short he nothing mess man haul...
1       1  great short read didnt want put read one sitti...
2       1  ill start saying first four book wasnt expecti...
3       1  aggie angela lansbury carry pocketbook instead...
4       1  expect type book library pleased find price right
5       1  aislinn little girl big dream death older brot...
6       0  making good story unfortunately disappointsit ...
7       1  got like collaborated short story alot time tw...
8       1  loved book hooked series hope kelsey maxwell r...
9       1  thats good thing short sweet tease give everyt...

### Model building
* Splitting data to train and test sets

In [98]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(kindle_df["reviewText"], kindle_df["rating"], test_size=0.2)

In [105]:
# BagofWords
from sklearn.feature_extraction.text import CountVectorizer
cv_bow = CountVectorizer()
X_train_bow = cv_bow.fit_transform(X_train).toarray()
X_test_bow = cv_bow.transform(X_test).toarray()

In [106]:
# TF-IDF
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer()
X_train_tfidf = tfidf.fit_transform(X_train).toarray()
X_test_tfidf = tfidf.transform(X_test).toarray()

In [113]:
X_train_bow

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [114]:
X_train_tfidf

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

* Using naive bayes algorithm as it performs well on sparse matrix (with almost zeroes)

In [116]:
from sklearn.naive_bayes import GaussianNB
model_bow = GaussianNB().fit(X_train_bow, y_train)
model_tfidf = GaussianNB().fit(X_train_tfidf, y_train)

###Utilizng metrics

In [117]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [119]:
y_pred_bow = model_bow.predict(X_test_bow)
y_pred_tfidf = model_tfidf.predict(X_test_tfidf)

In [120]:
print("Accuracy Score BOW: ", accuracy_score(y_test, y_pred_bow))
print("Accuracy Score TFIDF: ", accuracy_score(y_test, y_pred_tfidf))

Accuracy Score BOW:  0.58
Accuracy Score TFIDF:  0.5845833333333333

In [127]:
print("Confusion Matrix BOW: \n", confusion_matrix(y_test, y_pred_bow))
print("Confusion Matrix TFIDF: \n", confusion_matrix(y_test, y_pred_tfidf))

Confusion Matrix BOW:
 [[515 281]
 [727 877]]
Confusion Matrix TFIDF:
 [[503 293]
 [704 900]]

### Word2Vec

In [128]:
!pip install gensim

Collecting gensim
  Downloading gensim-4.4.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (8.4 kB)
Requirement already satisfied: numpy>=1.18.5 in /usr/local/lib/python3.12/dist-packages (from gensim) (2.0.2)
Requirement already satisfied: scipy>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from gensim) (1.16.3)
Requirement already satisfied: smart_open>=1.8.1 in /usr/local/lib/python3.12/dist-packages (from gensim) (7.5.1)
Requirement already satisfied: wrapt in /usr/local/lib/python3.12/dist-packages (from smart_open>=1.8.1->gensim) (2.1.2)
Downloading gensim-4.4.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (27.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.9/27.9 MB 15.1 MB/s eta 0:00:00
Installing collected packages: gensim
Successfully installed gensim-4.4.0

In [129]:
from gensim.models import Word2Vec

In [131]:
sentences = [text.split() for text in kindle_df["reviewText"]]   # tokenized reviews

In [132]:
w2v = Word2Vec(sentences, vector_size=100, window=5, min_count=2)

In [133]:
def w2v_avg(text):
    words = text.split()
    vectors = [w2v.wv[word] for word in words if word in w2v.wv]
    return np.mean(vectors, axis=0) if vectors else np.zeros(100)

In [134]:
X_w2v = np.array([w2v_avg(text) for text in kindle_df['reviewText']])

In [137]:
## Training
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

X_train, X_test, y_train, y_test = train_test_split(X_w2v, kindle_df["rating"], test_size=0.2)

model = LogisticRegression()
model.fit(X_train, y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [143]:
## prediction
y_pred_w2v = model.predict(X_test)

In [144]:
print("Accuracy Score W2V: ", accuracy_score(y_test, y_pred_w2v))

Accuracy Score W2V:  0.77625

In [145]:
print("Confusion Matrix W2V: \n", confusion_matrix(y_test, y_pred_w2v))

Confusion Matrix W2V:
 [[ 459  351]
 [ 186 1404]]