<a href="https://colab.research.google.com/github/Naga-SDonepudi/nlp_for_ml/blob/main/word_to_vector_representation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Bag of Words (BoW)
* A technique is NLP used to convert words to vector rpresenation based on the frequency of words
* Before changing words to vectors, it counts how many times each word appears in a sentence.

In [106]:
import pandas as pd

In [107]:
matter = pd.read_csv('SMSSpamCollection.txt',
                    sep='\t',names=["label","text"])

In [108]:
matter

     label                                               text
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham               Will ü b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

### Data Preprocessing

In [109]:
import nltk
import re
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [110]:
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer

In [111]:
port_stemmer = PorterStemmer()

In [112]:
corpus = []
for i in range(0, len(matter)):
  review=re.sub('[^a-zA-Z]',' ', matter['text'][i])
  review=review.lower()
  review=review.split()
  review=[port_stemmer.stem(word) for word in review if not word in stopwords.words('english')]
  review=' '.join(review)
  corpus.append(review)

In [113]:
corpus

['go jurong point crazi avail bugi n great world la e buffet cine got amor wat',
 'ok lar joke wif u oni',
 'free entri wkli comp win fa cup final tkt st may text fa receiv entri question std txt rate c appli',
 'u dun say earli hor u c alreadi say',
 'nah think goe usf live around though',
 'freemsg hey darl week word back like fun still tb ok xxx std chg send rcv',
 'even brother like speak treat like aid patent',
 'per request mell mell oru minnaminungint nurungu vettam set callertun caller press copi friend callertun',
 'winner valu network custom select receivea prize reward claim call claim code kl valid hour',
 'mobil month u r entitl updat latest colour mobil camera free call mobil updat co free',
 'gonna home soon want talk stuff anymor tonight k cri enough today',
 'six chanc win cash pound txt csh send cost p day day tsandc appli repli hl info',
 'urgent week free membership prize jackpot txt word claim c www dbuk net lccltd pobox ldnw rw',
 'search right word thank breather promis wont take help grant fulfil promis wonder bless time',
 'date sunday',
 'xxxmobilemovieclub use credit click wap link next txt messag click http wap xxxmobilemovieclub com n qjkgighjjgcbl',
 'oh k watch',
 'eh u rememb spell name ye v naughti make v wet',
 'fine way u feel way gota b',
 'england v macedonia dont miss goal team news txt ur nation team eg england tri wale scotland txt poboxox w wq',
 'serious spell name',
 'go tri month ha ha joke',
 'pay first lar da stock comin',
 'aft finish lunch go str lor ard smth lor u finish ur lunch alreadi',
 'ffffffffff alright way meet sooner',
 'forc eat slice realli hungri tho suck mark get worri know sick turn pizza lol',
 'lol alway convinc',
 'catch bu fri egg make tea eat mom left dinner feel love',
 'back amp pack car let know room',
 'ahhh work vagu rememb feel like lol',
 'wait still clear sure sarcast x want live us',
 'yeah got v apologet n fallen actin like spoilt child got caught till go badli cheer',
 'k tell anyth',
 'fear faint housework quick cuppa',
 'thank subscript rington uk mobil charg month pleas confirm repli ye repli charg',
 'yup ok go home look time msg xuhui go learn nd may lesson',
 'oop let know roommat done',
 'see letter b car',
 'anyth lor u decid',
 'hello saturday go text see decid anyth tomo tri invit anyth',
 'pl go ahead watt want sure great weekend abiola',
 'forget tell want need crave love sweet arabian steed mmmmmm yummi',
 'rodger burn msg tri call repli sm free nokia mobil free camcord pleas call deliveri tomorrow',
 'see',
 'great hope like man well endow lt gt inch',
 'call messag miss call',
 'get hep b immunis nigeria',
 'fair enough anyth go',
 'yeah hope tyler could mayb ask around bit',
 'u know stubborn even want go hospit kept tell mark weak sucker hospit weak sucker',
 'think first time saw class',
 'gram usual run like lt gt half eighth smarter though get almost whole second gram lt gt',
 'k fyi x ride earli tomorrow morn crash place tonight',
 'wow never realiz embarass accomod thought like sinc best could alway seem happi cave sorri give sorri offer sorri room embarass',
 'sm ac sptv new jersey devil detroit red wing play ice hockey correct incorrect end repli end sptv',
 'know mallika sherawat yesterday find lt url gt',
 'congrat year special cinema pass call c suprman v matrix starwar etc free bx ip pm dont miss',
 'sorri call later meet',
 'tell reach',
 'ye gauti sehwag odi seri',
 'gonna pick burger way home even move pain kill',
 'ha ha ha good joke girl situat seeker',
 'part check iq',
 'sorri roommat took forev ok come',
 'ok lar doubl check wif da hair dresser alreadi said wun cut v short said cut look nice',
 'valu custom pleas advis follow recent review mob award bonu prize call',
 'today song dedic day song u dedic send ur valuabl frnd first rpli',
 'urgent ur award complimentari trip eurodisinc trav aco entri claim txt di morefrmmob shracomorsglsuplt ls aj',
 'hear new divorc barbi come ken stuff',
 'plane give month end',
 'wah lucki man save money hee',
 'finish class',
 'hi babe im home wanna someth xx',
 'k k perform',
 'u call',
 'wait machan call free',
 'that cool gentleman treat digniti respect',
 'like peopl much shi pa',
 'oper lt gt',
 'still look job much ta earn',
 'sorri call later',
 'k call ah',
 'ok way home hi hi',
 'place man',
 'yup next stop',
 'call later network urgnt sm',
 'real u get yo need ticket one jacket done alreadi use multi',
 'ye start send request make pain came back back bed doubl coin factori gotta cash nitro',
 'realli still tonight babe',
 'ela kano il download come wen ur free',
 'yeah stand close tho catch someth',
 'sorri pain ok meet anoth night spent late afternoon casualti mean done stuff moro includ time sheet sorri',
 'smile pleasur smile pain smile troubl pour like rain smile sum hurt u smile becoz someon still love see u smile',
 'pleas call custom servic repres pm guarante cash prize',
 'havent plan buy later check alreadi lido got show e afternoon u finish work alreadi',
 'free rington wait collect simpli text password mix verifi get usher britney fml po box mk h ppw',
 'watch telugu movi wat abt u',
 'see finish load loan pay',
 'hi wk ok hol ye bit run forgot hairdress appoint four need get home n shower beforehand caus prob u',
 'see cup coffe anim',
 'pleas text anymor noth els say',
 'okay name ur price long legal wen pick u ave x am xx',
 'still look car buy gone drive test yet',
 'per request mell mell oru minnaminungint nurungu vettam set callertun caller press copi friend callertun',
 'wow right mean guess gave boston men chang search locat nyc someth chang cuz signin page still say boston',
 'umma life vava umma love lot dear',
 'thank lot wish birthday thank make birthday truli memor',
 'aight hit get cash',
 'would ip address test consid comput minecraft server',
 'know grumpi old peopl mom like better lie alway one play joke',
 'dont worri guess busi',
 'plural noun research',
 'go dinner msg',
 'ok wif co like tri new thing scare u dun like mah co u said loud',
 'gent tri contact last weekend draw show prize guarante call claim code k valid hr ppm',
 'wa ur openin sentenc formal anyway fine juz tt eatin much n puttin weight haha anythin special happen',
 'enter cabin pa said happi b day boss felt special askd lunch lunch invit apart went',
 'winner u special select receiv holiday flight inc speak live oper claim p min',
 'goodo ye must speak friday egg potato ratio tortilla need',
 'hmm uncl inform pay school directli pl buy food',
 'privat account statement show unredeem bonu point claim call identifi code expir',
 'urgent mobil award bonu caller prize final tri contact u call landlin box wr c ppm',
 'new address appl pair malarki',
 'today voda number end select receiv award match pleas call quot claim code standard rate app',
 'go sao mu today done',
 'predict wat time finish buy',
 'good stuff',
 'know yetund sent money yet sent text bother send dont involv anyth impos anyth first place apologis',
 'room',
 'hey girl r u hope u r well del r bak long time c give call sum time lucyxx',
 'k k much cost',
 'home',
 'dear call tmorrow pl accomod',
 'first answer question',
 'sunshin quiz wkli q win top soni dvd player u know countri algarv txt ansr sp tyron',
 'want get laid tonight want real dog locat sent direct ur mob join uk largest dog network bt txting gravel nt ec p msg p',
 'haf msn yiju hotmail com',
 'call meet',
 'check room befor activ',
 'rcv msg chat svc free hardcor servic text go u get noth u must age verifi yr network tri',
 'got c lazi type forgot lect saw pouch like v nice',
 'k text way',
 'sir wait mail',
 'swt thought nver get tire littl thing lovabl person coz somtim littl thing occupi biggest part heart gud ni',
 'know pl open back',
 'ye see ya dot',
 'what staff name take class us',
 'freemsg repli text randi sexi femal live local luv hear u netcollex ltd p per msg repli stop end',
 'ummma call check life begin qatar pl pray hard',
 'k delet contact',
 'sindu got job birla soft',
 'wine flow never',
 'yup thk cine better co need go plaza mah',
 'ok ur typic repli',
 'per request mell mell oru minnaminungint nurungu vettam set callertun caller press copi friend callertun',
 'everywher dirt floor window even shirt sometim open mouth come flow dream world without half chore time joy lot tv show see guess like thing must exist like rain hail mist time done becom one',
 'aaooooright work',
 'leav hous',
 'hello love get interview today happi good boy think miss',
 'custom servic annonc new year deliveri wait pleas call arrang deliveri',
 'winner u special select receiv cash holiday flight inc speak live oper claim',
 'keep safe need miss alreadi envi everyon see real life',
 'new car hous parent new job hand',
 'love excit day spend make happi',
 'pl stop bootydeli f invit friend repli ye see www sm ac u bootydeli stop send stop frnd',
 'bangbab ur order way u receiv servic msg download ur content u goto wap bangb tv ur mobil internet servic menu',
 'place ur point e cultur modul alreadi',
 'urgent tri contact last weekend draw show prize guarante call claim code valid hr',
 'hi frnd best way avoid missunderstd wit belov one',
 'great escap fanci bridg need lager see tomo',
 'ye complet form clark also utter wast',
 'sir need axi bank account bank address',
 'hmmm thk sure got time hop ard ya go free abt muz call u discuss liao',
 'time come later',
 'bloodi hell cant believ forgot surnam mr ill give u clue spanish begin',
 'well gonna finish bath good fine night',
 'let know got money carlo make call',
 'u still go mall',
 'turn friend stay whole show back til lt gt feel free go ahead smoke lt gt worth',
 'text doesnt repli let know log',
 'hi spoke maneesha v like know satisfi experi repli toll free ye',
 'lift hope offer money need especi end month approach hurt studi anyway gr weekend',
 'lol u trust',
 'ok gentleman treat digniti respect',
 'guy close',
 'go noth great bye',
 'hello handsom find job lazi work toward get back net mummi boytoy miss',
 'haha awesom minut',
 'pleas call custom servic repres freephon pm guarante cash prize',
 'got xma radio time get',
 'ju reach home go bath first si use net tell u finish k',
 'uniqu enough find th august www areyouuniqu co uk',
 'sorri join leagu peopl dont keep touch mean great deal friend time even great person cost great week',
 'hi final complet cours',
 'stop howev suggest stay someon abl give or everi stool',
 'hope settl new school year wishin gr day',
 'gud mrng dear hav nice day',
 'u got person stori',
 'hamster dead hey tmr meet pm orchard mrt',
 'hi kate even hope see tomorrow bit bloodi babyjontet txt back u xxx',
 'found enc lt gt',
 'sent lt gt buck',
 'hello darlin ive finish colleg txt u finish u love kate xxx',
 'account refil success inr lt decim gt keralacircl prepaid account balanc rs lt decim gt transact id kr lt gt',
 'goodmorn sleep ga',
 'u call alter ok',
 'say like dat dun buy ericsson oso cannot oredi lar',
 'enter cabin pa said happi b day boss felt special askd lunch lunch invit apart went',
 'aight yo dat straight dogg',
 'pleas give us connect today lt decim gt refund bill',
 'shoot big load get readi',
 'bruv hope great break reward semest',
 'home alway chat',
 'k k good studi well',
 'yup noe leh',
 'sound great home',
 'final match head toward draw predict',
 'tire slept well past night',
 'easi ah sen got select mean good',
 'take exam march',
 'yeah think use gt atm regist sure anyway help let know sure readi',
 'ok prob take ur time',
 'os call ubandu run without instal hard disk use os copi import file system give repair shop',
 'sorri call later',
 'u say leh cours noth happen lar say v romant ju bit lor thk e nite sceneri nice leh',
 'new mobil must go txt nokia collect today www tc biz optout gbp mtmsg',
 'would realli appreci call need someon talk',
 'u meet ur dream partner soon ur career flyng start find free txt horo follow ur star sign e g horo ari',
 'hey compani elama po mudyadhu',
 'life strict teacher bcoz teacher teach lesson amp conduct exam life first conduct exam amp teach lesson happi morn',
 'dear good morn',
 'get gandhipuram walk cross cut road right side lt gt street road turn first right',
 'dear go rubber place',
 'sorri batteri die yeah',
 'ye tv alway avail work place',
 'text meet someon sexi today u find date even flirt u join p repli name age eg sam msg recd thirtyeight penc',
 'print oh lt gt come upstair',
 'ill littl closer like bu stop street',
 'wil reach',
 'new theori argument win situat lose person dont argu ur friend kick amp say alway correct',
 'u secret admir look make contact u find r reveal think ur special call',
 'tomarrow final hear laptop case cant',
 'pleassssssseeeee tel v avent done sportsx',
 'okay shine meant sign sound better',
 'although told u dat baig face watch realli like e watch u gave co fr u thanx everyth dat u done today touch',
 'u rememb old commerci',
 'late said websit dont slipper',
 'ask call ok',
 'kalli wont bat nd inning',
 'didnt work oh ok goodnight fix readi time wake dearli miss good night sleep',
 'congratul ur award cd voucher gift guarante free entri wkli draw txt music tnc www ldew com win ppmx age',
 'ranjith cal drpd deeraj deepak min hold',
 'wen ur lovabl bcum angri wid u dnt take serious coz angri childish n true way show deep affect care n luv kettoda manda nice day da',
 '',
 'up day also ship compani take wk way usp take week get lag may bribe nipost get stuff',
 'back lemm know readi',
 'necessarili expect done get back though headin',
 'mmm yummi babe nice jolt suzi',
 'lover need',
 'tri contact repli offer video handset anytim network min unlimit text camcord repli call',
 'park next mini come today think',
 'yup',
 'anyway go shop co si done yet dun disturb u liao',
 'luton ring ur around h',
 'hey realli horni want chat see nake text hot text charg pm unsubscrib text stop',
 'dint come us',
 'wana plan trip sometm',
 'sure yet still tri get hold',
 'ur rington servic chang free credit go club mobil com choos content stop txt club stop p wk club po box mk wt',
 'evo download flash jealou',
 'rington club get uk singl chart mobil week choos top qualiti rington messag free charg',
 'come mu sort narcot situat',
 'night end anoth day morn come special way may smile like sunni ray leav worri blue blue bay',
 'hmv bonu special pound genuin hmv voucher answer easi question play send hmv info www percent real com',
 'usf guess might well take car',
 'object bf come',
 'thanx',
 'tell rob mack gf theater',
 'awesom see bit',
 'sent type food like',
 'done hand celebr full swing yet',
 'got call tool',
 'wen u miss someon person definit special u person special miss keep touch gdeve',
 'ok ask money far',
 'oki',
 'yeah think usual guy still pass last night get ahold anybodi let know throw',
 'k might come tonight class let earli',
 'ok',
 'hi babi im cruisin girl friend r u give call hour home that alright fone fone love jenni xxx',
 'life mean lot love life love peopl life world call friend call world ge',
 'dear shall mail tonit busi street shall updat tonit thing look ok varunnathu edukkukaye raksha ollu good one real sens',
 'hey told name gautham ah',
 'haf u found feel stupid da v cam work',
 'oop got bit',
 'much buzi',
 'accident delet messag resend pleas',
 'mobil custom may claim free camera phone upgrad pay go sim card loyalti call offer end thfeb c appli',
 'unless situat go gurl would appropri',
 'hurt teas make cri end life die plz keep one rose grave say stupid miss u nice day bslvyl',
 'cant pick phone right pl send messag',
 'need coffe run tomo believ time week alreadi',
 'awesom rememb last time got somebodi high first time diesel v',
 'shit realli shock scari cant imagin second def night u think somewher could crash night save taxi',
 'oh way food fridg want go meal tonight',
 'womdarful actor',
 'sm ac blind date u rodd aberdeen unit kingdom check http img sm ac w icmb cktz r blind date send hide',
 'yup remb think book',
 'jo ask u wana meet',
 'lol ye friendship hang thread caus u buy stuff',
 'themob check newest select content game tone gossip babe sport keep mobil fit funki text wap',
 'garag key bookshelf',
 'today accept day u accept brother sister lover dear best clo lvblefrnd jstfrnd cutefrnd lifpartnr belovd swtheart bstfrnd rpli mean enemi',
 'think ur smart win week weekli quiz text play cs winnersclub po box uz gbp week',
 'say give call friend got money definit buy end week',
 'hi way u day normal way real ur uniqu hope know u rest mylif hope u find wot lost',
 'made day great day',
 'k k advanc happi pongal',
 'hmmm guess go kb n power yoga haha dunno tahan power yoga anot thk got lo oso forgot liao',
 'realli dude friend afraid',
 'decemb mobil mth entitl updat latest colour camera mobil free call mobil updat co free',
 'coffe cake guess',
 'merri christma babe love ya kiss',
 'hey dont go watch x men lunch haha',
 'cud u tell ppl im gona b bit l co buse hav gon past co full im still waitin pete x',
 'would great guild could meet bristol road somewher get touch weekend plan take flight good week',
 'problem',
 'call messag miss call',
 'hi da today class',
 'say good sign well know track record read women',
 'cool text park',
 'read text sent meant joke read light',
 'k k apo k good movi',
 'mayb could get book tomo return immedi someth',
 'call germani penc per minut call fix line via access number prepay direct access',
 'chanc might evapor soon violat privaci steal phone number employ paperwork cool pleas contact report supervisor',
 'valentin day special win quiz take partner trip lifetim send go p msg rcvd custcar',
 'ta daaaaa home babe still',
 'cool come havent wine dine',
 'sleep surf',
 'sorri call later',
 'u call right call hand phone',
 'ok great thanx lot',
 'take post come must text happi read one wiv hello carolin end favourit bless',
 'u hide stranger',
 'interest like',
 'sister clear two round birla soft yesterday',
 'gudnit tc practic go',
 'di yiju ju saw ur mail case huim havent sent u num di num',
 'one small prestig problem',
 'fanci shag interest sextextuk com txt xxuk suzi txt cost per msg tnc websit x',
 'check realli miss see jeremiah great month',
 'nah help never iphon',
 'car hour half go apeshit',
 'today sorri day ever angri ever misbehav hurt plz plz slap urself bcoz ur fault basic good',
 'yo guy ever figur much need alcohol jay tri figur much safe spend weed',
 'lt gt ish minut minut ago wtf',
 'thank call forgot say happi onam sirji fine rememb met insur person meet qatar insha allah rakhesh ex tata aig join tissco tayseer',
 'congratul ur award cd voucher gift guarante free entri wkli draw txt music tnc www ldew com win ppmx age',
 'ur cash balanc current pound maxim ur cash send cash p msg cc hg suit land row w j hl',
 'actor work work even sleep late sinc unemploy moment alway sleep late unemploy everi day saturday',
 'hello got st andrew boy long way cold keep post',
 'ha ha cool cool chikku chikku db',
 'oh ok prob',
 'check audrey statu right',
 'busi tri finish new year look forward final meet',
 'good afternoon sunshin dawn day refresh happi aliv breath air smile think love alway',
 'well know z take care worri',
 'updat xma offer latest motorola sonyericsson nokia free bluetooth doubl min txt orang call mobileupd call optout f q',
 'discount code rp stop messag repli stop www regalportfolio co uk custom servic',
 'wat uniform get',
 'cool text readi',
 'hello boytoy geeee miss alreadi woke wish bed cuddl love',
 'spoil bed well',
 'go bath msg next lt gt min',
 'cant keep talk peopl sure pay agre price pl tell want realli buy much will pay',
 'thank rington order refer charg gbp per week unsubscrib anytim call custom servic',
 'say happen',
 'could seen recognis face',
 'well lot thing happen lindsay new year sigh bar ptbo blue heron someth go',
 'keep payasam rinu bring',
 'taught ranjith sir call sm like becau he verifi project prabu told today pa dont mistak',

### Converting text to vectors using Bag of Words

In [114]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=2500, binary=True)

In [115]:
X= cv.fit_transform(corpus).toarray()

In [116]:
X.shape

(5572, 2500)

In [117]:
cv.vocabulary_

{'go': np.int64(865),
 'point': np.int64(1602),
 'crazi': np.int64(438),
 'avail': np.int64(143),
 'bugi': np.int64(269),
 'great': np.int64(899),
 'world': np.int64(2438),
 'la': np.int64(1156),
 'cine': np.int64(360),
 'got': np.int64(884),
 'wat': np.int64(2371),
 'ok': np.int64(1468),
 'lar': np.int64(1164),
 'joke': np.int64(1120),
 'wif': np.int64(2406),
 'oni': np.int64(1476),
 'free': np.int64(774),
 'entri': np.int64(602),
 'wkli': np.int64(2427),
 'comp': np.int64(394),
 'win': np.int64(2410),
 'fa': np.int64(666),
 'cup': np.int64(452),
 'final': np.int64(718),
 'tkt': np.int64(2219),
 'st': np.int64(2067),
 'may': np.int64(1302),
 'text': np.int64(2181),
 'receiv': np.int64(1763),
 'question': np.int64(1715),
 'std': np.int64(2078),
 'txt': np.int64(2276),
 'rate': np.int64(1740),
 'appli': np.int64(102),
 'dun': np.int64(564),
 'say': np.int64(1897),
 'earli': np.int64(568),
 'hor': np.int64(1006),
 'alreadi': np.int64(69),
 'nah': np.int64(1405),
 'think': np.int64(2195),
 'goe': np.int64(868),
 'usf': np.int64(2317),
 'live': np.int64(1218),
 'around': np.int64(117),
 'though': np.int64(2201),
 'freemsg': np.int64(777),
 'hey': np.int64(973),
 'darl': np.int64(471),
 'week': np.int64(2385),
 'word': np.int64(2435),
 'back': np.int64(156),
 'like': np.int64(1207),
 'fun': np.int64(799),
 'still': np.int64(2080),
 'tb': np.int64(2157),
 'xxx': np.int64(2465),
 'send': np.int64(1927),
 'rcv': np.int64(1743),
 'even': np.int64(624),
 'brother': np.int64(258),
 'speak': np.int64(2049),
 'treat': np.int64(2254),
 'per': np.int64(1547),
 'request': np.int64(1805),
 'mell': np.int64(1316),
 'oru': np.int64(1494),
 'minnaminungint': np.int64(1339),
 'nurungu': np.int64(1454),
 'vettam': np.int64(2331),
 'set': np.int64(1939),
 'callertun': np.int64(291),
 'caller': np.int64(290),
 'press': np.int64(1653),
 'copi': np.int64(420),
 'friend': np.int64(784),
 'winner': np.int64(2416),
 'valu': np.int64(2323),
 'network': np.int64(1422),
 'custom': np.int64(456),
 'select': np.int64(1922),
 'receivea': np.int64(1764),
 'prize': np.int64(1666),
 'reward': np.int64(1825),
 'claim': np.int64(364),
 'call': np.int64(287),
 'code': np.int64(379),
 'valid': np.int64(2322),
 'hour': np.int64(1013),
 'mobil': np.int64(1355),
 'month': np.int64(1369),
 'entitl': np.int64(601),
 'updat': np.int64(2301),
 'latest': np.int64(1169),
 'colour': np.int64(386),
 'camera': np.int64(296),
 'co': np.int64(377),
 'gonna': np.int64(873),
 'home': np.int64(998),
 'soon': np.int64(2033),
 'want': np.int64(2366),
 'talk': np.int64(2149),
 'stuff': np.int64(2100),
 'anymor': np.int64(91),
 'tonight': np.int64(2236),
 'cri': np.int64(442),
 'enough': np.int64(599),
 'today': np.int64(2226),
 'six': np.int64(1992),
 'chanc': np.int64(330),
 'cash': np.int64(313),
 'pound': np.int64(1628),
 'cost': np.int64(423),
 'day': np.int64(477),
 'repli': np.int64(1802),
 'hl': np.int64(984),
 'info': np.int64(1065),
 'urgent': np.int64(2309),
 'membership': np.int64(1318),
 'www': np.int64(2456),
 'net': np.int64(1420),
 'pobox': np.int64(1598),
 'ldnw': np.int64(1177),
 'rw': np.int64(1868),
 'search': np.int64(1913),
 'right': np.int64(1831),
 'thank': np.int64(2187),
 'promis': np.int64(1678),
 'wont': np.int64(2434),
 'take': np.int64(2145),
 'help': np.int64(967),
 'wonder': np.int64(2433),
 'bless': np.int64(219),
 'time': np.int64(2215),
 'date': np.int64(475),
 'sunday': np.int64(2117),
 'use': np.int64(2315),
 'credit': np.int64(441),
 'click': np.int64(368),
 'wap': np.int64(2367),
 'link': np.int64(1212),
 'next': np.int64(1428),
 'messag': np.int64(1324),
 'http': np.int64(1022),
 'com': np.int64(387),
 'oh': np.int64(1466),
 'watch': np.int64(2372),
 'eh': np.int64(583),
 'rememb': np.int64(1791),
 'spell': np.int64(2053),
 'name': np.int64(1407),
 'ye': np.int64(2475),
 'naughti': np.int64(1413),
 'make': np.int64(1277),
 'wet': np.int64(2396),
 'fine': np.int64(721),
 'way': np.int64(2374),
 'feel': np.int64(701),
 'england': np.int64(596),
 'dont': np.int64(545),
 'miss': np.int64(1342),
 'goal': np.int64(866),
 'team': np.int64(2163),
 'news': np.int64(1427),
 'ur': np.int64(2306),
 'nation': np.int64(1411),
 'eg': np.int64(581),
 'tri': np.int64(2256),
 'wale': np.int64(2358),
 'scotland': np.int64(1907),
 'wq': np.int64(2446),
 'serious': np.int64(1936),
 'ha': np.int64(919),
 'pay': np.int64(1534),
 'first': np.int64(725),
 'da': np.int64(462),
 'stock': np.int64(2081),
 'comin': np.int64(391),
 'aft': np.int64(40),
 'finish': np.int64(723),
 'lunch': np.int64(1256),
 'str': np.int64(2090),
 'lor': np.int64(1236),
 'ard': np.int64(109),
 'smth': np.int64(2015),
 'alright': np.int64(70),
 'meet': np.int64(1312),
 'sooner': np.int64(2034),
 'forc': np.int64(754),
 'eat': np.int64(574),
 'slice': np.int64(2004),
 'realli': np.int64(1756),
 'hungri': np.int64(1028),
 'tho': np.int64(2200),
 'suck': np.int64(2109),
 'mark': np.int64(1289),
 'get': np.int64(844),
 'worri': np.int64(2439),
 'know': np.int64(1153),
 'sick': np.int64(1974),
 'turn': np.int64(2271),
 'pizza': np.int64(1580),
 'lol': np.int64(1228),
 'alway': np.int64(73),
 'convinc': np.int64(417),
 'catch': np.int64(315),
 'bu': np.int64(264),
 'fri': np.int64(782),
 'egg': np.int64(582),
 'tea': np.int64(2160),
 'mom': np.int64(1362),
 'left': np.int64(1185),
 'dinner': np.int64(523),
 'love': np.int64(1245),
 'amp': np.int64(80),
 'pack': np.int64(1507),
 'car': np.int64(304),
 'let': np.int64(1194),
 'room': np.int64(1849),
 'work': np.int64(2436),
 'wait': np.int64(2355),
 'clear': np.int64(367),
 'sure': np.int64(2129),
 'sarcast': np.int64(1888),
 'us': np.int64(2313),
 'yeah': np.int64(2476),
 'child': np.int64(348),
 'caught': np.int64(316),
 'till': np.int64(2214),
 'cheer': np.int64(344),
 'tell': np.int64(2170),
 'anyth': np.int64(93),
 'fear': np.int64(697),
 'quick': np.int64(1716),
 'subscript': np.int64(2107),
 'rington': np.int64(1834),
 'uk': np.int64(2284),
 'charg': np.int64(334),
 'pleas': np.int64(1590),
 'confirm': np.int64(405),
 'yup': np.int64(2498),
 'look': np.int64(1233),
 'msg': np.int64(1389),
 'xuhui': np.int64(2463),
 'learn': np.int64(1180),
 'nd': np.int64(1414),
 'lesson': np.int64(1193),
 'oop': np.int64(1480),
 'roommat': np.int64(1850),
 'done': np.int64(544),
 'see': np.int64(1919),
 'letter': np.int64(1195),
 'decid': np.int64(486),
 'hello': np.int64(965),
 'saturday': np.int64(1892),
 'tomo': np.int64(2233),
 'invit': np.int64(1081),
 'pl': np.int64(1581),
 'ahead': np.int64(47),
 'weekend': np.int64(2386),
 'abiola': np.int64(4),
 'forget': np.int64(758),
 'need': np.int64(1418),
 'crave': np.int64(437),
 'sweet': np.int64(2133),
 'yummi': np.int64(2494),
 'burn': np.int64(272),
 'sm': np.int64(2009),
 'nokia': np.int64(1439),
 'camcord': np.int64(294),
 'deliveri': np.int64(497),
 'tomorrow': np.int64(2234),
 'hope': np.int64(1005),
 'man': np.int64(1281),
 'well': np.int64(2392),
 'lt': np.int64(1252),
 'gt': np.int64(907),
 'inch': np.int64(1058),
 'nigeria': np.int64(1432),
 'fair': np.int64(673),
 'tyler': np.int64(2280),
 'could': np.int64(425),
 'mayb': np.int64(1303),
 'ask': np.int64(124),
 'bit': np.int64(211),
 'hospit': np.int64(1009),
 'kept': np.int64(1138),
 'weak': np.int64(2377),
 'saw': np.int64(1896),
 'class': np.int64(365),
 'gram': np.int64(893),
 'usual': np.int64(2318),
 'run': np.int64(1866),
 'half': np.int64(927),
 'almost': np.int64(66),
 'whole': np.int64(2404),
 'second': np.int64(1916),
 'fyi': np.int64(808),
 'ride': np.int64(1830),
 'morn': np.int64(1374),
 'crash': np.int64(436),
 'place': np.int64(1582),
 'wow': np.int64(2444),
 'never': np.int64(1424),
 'realiz': np.int64(1755),
 'embarass': np.int64(590),
 'thought': np.int64(2202),
 'sinc': np.int64(1983),
 'best': np.int64(195),
 'seem': np.int64(1920),
 'happi': np.int64(939),
 'sorri': np.int64(2037),
 'give': np.int64(859),
 'offer': np.int64(1462),
 'ac': np.int64(11),
 'new': np.int64(1425),
 'red': np.int64(1772),
 'play': np.int64(1587),
 'ice': np.int64(1039),
 'hockey': np.int64(991),
 'correct': np.int64(422),
 'end': np.int64(592),
 'yesterday': np.int64(2482),
 'find': np.int64(720),
 'url': np.int64(2311),
 'congrat': np.int64(407),
 'year': np.int64(2477),
 'special': np.int64(2050),
 'cinema': np.int64(361),
 'pass': np.int64(1528),
 'suprman': np.int64(2127),
 'matrix': np.int64(1297),
 'starwar': np.int64(2074),
 'etc': np.int64(617),
 'bx': np.int64(278),
 'ip': np.int64(1084),
 'pm': np.int64(1596),
 'later': np.int64(1168),
 'reach': np.int64(1746),
 'seri': np.int64(1934),
 'pick': np.int64(1568),
 'move': np.int64(1382),
 'pain': np.int64(1511),
 'kill': np.int64(1145),
 'good': np.int64(874),
 'girl': np.int64(855),
 'situat': np.int64(1991),
 'part': np.int64(1524),
 'check': np.int64(343),
 'iq': np.int64(1087),
 'took': np.int64(2238),
 'forev': np.int64(756),
 'come': np.int64(389),
 'doubl': np.int64(548),
 'hair': np.int64(925),
 'dresser': np.int64(553),
 'said': np.int64(1877),
 'wun': np.int64(2455),
 'cut': np.int64(457),
 'short': np.int64(1962),
 'nice': np.int64(1430),
 'advis': np.int64(35),
 'follow': np.int64(747),
 'recent': np.int64(1765),
 'review': np.int64(1823),
 'mob': np.int64(1353),
 'award': np.int64(150),
 'bonu': np.int64(231),
 'song': np.int64(2030),
 'valuabl': np.int64(2324),
 'frnd': np.int64(788),
 'rpli': np.int64(1855),
 'complimentari': np.int64(398),
 'trip': np.int64(2257),
 'eurodisinc': np.int64(619),
 'di': np.int64(508),
 'ls': np.int64(1251),
 'hear': np.int64(955),
 'plane': np.int64(1585),
 'wah': np.int64(2354),
 'lucki': np.int64(1255),
 'save': np.int64(1895),
 'money': np.int64(1366),
 'hee': np.int64(959),
 'hi': np.int64(975),
 'babe': np.int64(154),
 'im': np.int64(1049),
 'wanna': np.int64(2365),
 'someth': np.int64(2026),
 'xx': np.int64(2464),
 'perform': np.int64(1550),
 'machan': np.int64(1265),
 'that': np.int64(2190),
 'cool': np.int64(419),
 'gentleman': np.int64(839),
 'digniti': np.int64(520),
 'respect': np.int64(1809),
 'peopl': np.int64(1546),
 'much': np.int64(1397),
 'shi': np.int64(1953),
 'pa': np.int64(1506),
 'oper': np.int64(1482),
 'job': np.int64(1116),
 'ta': np.int64(2142),
 'earn': np.int64(570),
 'ah': np.int64(45),
 'stop': np.int64(2085),
 'urgnt': np.int64(2310),
 'real': np.int64(1751),
 'yo': np.int64(2488),
 'ticket': np.int64(2212),
 'one': np.int64(1475),
 'start': np.int64(2073),
 'came': np.int64(295),
 'bed': np.int64(181),
 'coin': np.int64(381),
 'gotta': np.int64(886),
 'nitro': np.int64(1436),
 'kano': np.int64(1133),
 'il': np.int64(1047),
 'download': np.int64(549),
 'wen': np.int64(2394),
 'stand': np.int64(2070),
 'close': np.int64(371),
 'anoth': np.int64(86),
 'night': np.int64(1433),
 'spent': np.int64(2055),
 'late': np.int64(1167),
 'afternoon': np.int64(41),
 'mean': np.int64(1305),
 'moro': np.int64(1375),
 'includ': np.int64(1060),
 'sheet': np.int64(1951),
 'smile': np.int64(2013),
 'pleasur': np.int64(1591),
 'troubl': np.int64(2258),
 'pour': np.int64(1629),
 'rain': np.int64(1728),
 'sum': np.int64(2114),
 'hurt': np.int64(1031),
 'becoz': np.int64(180),
 'someon': np.int64(2025),
 'servic': np.int64(1938),
 'repres': np.int64(1804),
 'guarante': np.int64(909),
 'havent': np.int64(947),
 'plan': np.int64(1584),
 'buy': np.int64(275),
 'lido': np.int64(1199),
 'show': np.int64(1969),
 'collect': np.int64(384),
 'simpli': np.int64(1982),
 'password': np.int64(1530),
 'mix': np.int64(1345),
 'verifi': np.int64(2329),
 'fml': np.int64(744),
 'po': np.int64(1597),
 'box': np.int64(245),
 'mk': np.int64(1346),
 'ppw': np.int64(1638),
 'movi': np.int64(1383),
 'abt': np.int64(7),
 'load': np.int64(1221),
 'loan': np.int64(1222),
 'wk': np.int64(2424),
 'hol': np.int64(992),
 'forgot': np.int64(761),
 'appoint': np.int64(103),
 'four': np.int64(769),
 'shower': np.int64(1970),
 'caus': np.int64(317),
 'prob': np.int64(1668),
 'coffe': np.int64(380),
 'anim': np.int64(84),
 'noth': np.int64(1447),
 'els': np.int64(586),
 'okay': np.int64(1469),
 'price': np.int64(1658),
 'long': np.int64(1231),
 'legal': np.int64(1187),
 'ave': np.int64(145),
 'gone': np.int64(872),
 'drive': np.int64(556),
 'test': np.int64(2180),
 'yet': np.int64(2483),
 'guess': np.int64(912),
 'gave': np.int64(824),
 'boston': np.int64(239),
 'men': np.int64(1319),
 'chang': np.int64(331),
 'locat': np.int64(1224),
 'nyc': np.int64(1458),
 'cuz': np.int64(460),
 'page': np.int64(1509),
 'umma': np.int64(2285),
 'life': np.int64(1201),
 'vava': np.int64(2327),
 'lot': np.int64(1240),
 'dear': np.int64(481),
 'wish': np.int64(2419),
 'birthday': np.int64(209),
 'truli': np.int64(2260),
 'aight': np.int64(49),
 'hit': np.int64(982),
 'would': np.int64(2443),
 'address': np.int64(28),
 'consid': np.int64(410),
 'comput': np.int64(399),
 'old': np.int64(1472),
 'better': np.int64(197),
 'lie': np.int64(1200),
 'busi': np.int64(273),
 'research': np.int64(1807),
 'thing': np.int64(2194),
 'scare': np.int64(1898),
 'mah': np.int64(1272),
 'loud': np.int64(1241),
 'gent': np.int64(837),
 'contact': np.int64(412),
 'last': np.int64(1166),
 'draw': np.int64(550),
 'hr': np.int64(1021),
 'ppm': np.int64(1636),
 'wa': np.int64(2353),
 'sentenc': np.int64(1931),
 'formal': np.int64(764),
 'anyway': np.int64(96),
 'juz': np.int64(1130),
 'tt': np.int64(2266),
 'eatin': np.int64(576),
 'puttin': np.int64(1706),
 'weight': np.int64(2389),
 'haha': np.int64(922),
 'anythin': np.int64(94),
 'happen': np.int64(937),
 'enter': np.int64(600),
 'cabin': np.int64(280),
 'boss': np.int64(238),
 'felt': np.int64(705),
 'askd': np.int64(125),
 'apart': np.int64(98),
 'went': np.int64(2395),
 'holiday': np.int64(996),
 'flight': np.int64(738),
 'inc': np.int64(1057),
 'min': np.int64(1334),
 'goodo': np.int64(880),
 'must': np.int64(1402),
 'friday': np.int64(783),
 'potato': np.int64(1624),
 'hmm': np.int64(987),
 'uncl': np.int64(2289),
 'inform': np.int64(1066),
 'school': np.int64(1902),
 'directli': np.int64(526),
 'food': np.int64(749),
 'privat': np.int64(1665),
 'account': np.int64(18),
 'statement': np.int64(2075),
 'unredeem': np.int64(2297),
 'identifi': np.int64(1042),
 'expir': np.int64(656),
 'landlin': np.int64(1162),
 'voda': np.int64(2344),
 'number': np.int64(1453),
 'match': np.int64(1294),
 'quot': np.int64(1721),
 'standard': np.int64(2071),
 'app': np.int64(100),
 'mu': np.int64(1396),
 'predict': np.int64(1643),
 'yetund': np.int64(2484),
 'sent': np.int64(1930),
 'bother': np.int64(240),
 'apologis': np.int64(99),
 'del': np.int64(492),
 'bak': np.int64(159),
 'answer': np.int64(88),
 'sunshin': np.int64(2119),
 'quiz': np.int64(1720),
 'top': np.int64(2239),
 'soni': np.int64(2031),
 'dvd': np.int64(566),
 'player': np.int64(1588),
 'countri': np.int64(427),
 'ansr': np.int64(87),
 'sp': np.int64(2045),
 'tyron': np.int64(2282),
 'laid': np.int64(1160),
 'dog': np.int64(540),
 'direct': np.int64(525),
 'join': np.int64(1119),
 'largest': np.int64(1165),
 'bt': np.int64(262),
 'txting': np.int64(2279),
 'nt': np.int64(1449),
 'ec': np.int64(577),
 'haf': np.int64(921),
 'yiju': np.int64(2486),
 'befor': np.int64(184),
 'activ': np.int64(23),
 'chat': np.int64(338),
 'hardcor': np.int64(942),
 'age': np.int64(43),
 'yr': np.int64(2493),
 'lazi': np.int64(1174),
 'type': np.int64(2281),
 'lect': np.int64(1183),
 'pouch': np.int64(1627),
 'sir': np.int64(1987),
 'mail': np.int64(1274),
 'swt': np.int64(2138),
 'tire': np.int64(2216),
 'littl': np.int64(1217),
 'lovabl': np.int64(1244),
 'person': np.int64(1554),
 'coz': np.int64(432),
 'occupi': np.int64(1461),
 'biggest': np.int64(203),
 'heart': np.int64(957),
 'gud': np.int64(910),
 'ni': np.int64(1429),
 'open': np.int64(1481),
 'ya': np.int64(2470),
 'dot': np.int64(547),
 'what': np.int64(2397),
 'staff': np.int64(2068),
 'randi': np.int64(1735),
 'sexi': np.int64(1943),
 'femal': np.int64(706),
 'local': np.int64(1223),
 'luv': np.int64(1257),
 'netcollex': np.int64(1421),
 'ltd': np.int64(1253),
 'begin': np.int64(186),
 'qatar': np.int64(1709),
 'pray': np.int64(1641),
 'hard': np.int64(941),
 'delet': np.int64(494),
 'birla': np.int64(207),
 'soft': np.int64(2020),
 'wine': np.int64(2415),
 'flow': np.int64(742),
 'thk': np.int64(2197),
 'plaza': np.int64(1589),
 'everywher': np.int64(632),
 'floor': np.int64(741),
 'window': np.int64(2414),
 'shirt': np.int64(1956),
 'sometim': np.int64(2028),
 'dream': np.int64(551),
 'without': np.int64(2422),
 'joy': np.int64(1123),
 'tv': np.int64(2272),
 'becom': np.int64(179),
 'leav': np.int64(1182),
 'hous': np.int64(1014),
 'interview': np.int64(1079),
 'boy': np.int64(246),
 'arrang': np.int64(118),
 'keep': np.int64(1137),
 'safe': np.int64(1876),
 'everyon': np.int64(630),
 'parent': np.int64(1521),
 'hand': np.int64(932),
 'excit': np.int64(645),
 'spend': np.int64(2054),
 'order': np.int64(1490),
 'content': np.int64(413),
 'goto': np.int64(885),
 'internet': np.int64(1078),
 'menu': np.int64(1321),
 'modul': np.int64(1360),
 'avoid': np.int64(147),
 'wit': np.int64(2420),
 'escap': np.int64(610),
 'fanci': np.int64(679),
 'complet': np.int64(397),
 'form': np.int64(763),
 'also': np.int64(72),
 'utter': np.int64(2319),
 'wast': np.int64(2370),
 'bank': np.int64(162),
 'hmmm': np.int64(988),
 'hop': np.int64(1004),
 'muz': np.int64(1403),
 'discuss': np.int64(530),
 'liao': np.int64(1196),
 'bloodi': np.int64(223),
 'hell': np.int64(963),
 'cant': np.int64(302),
 'believ': np.int64(190),
 'mr': np.int64(1385),
 'ill': np.int64(1048),
 'spanish': np.int64(2047),
 'bath': np.int64(168),
 'carlo': np.int64(309),
 'mall': np.int64(1280),
 'stay': np.int64(2077),
 'til': np.int64(2213),
 'smoke': np.int64(2014),
 'worth': np.int64(2441),
 'doesnt': np.int64(539),
 'log': np.int64(1225),
 'spoke': np.int64(2059),
 'maneesha': np.int64(1284),
 'satisfi': np.int64(1891),
 'experi': np.int64(655),
 'toll': np.int64(2230),
 'lift': np.int64(1204),
 'especi': np.int64(612),
 'studi': np.int64(2099),
 'gr': np.int64(890),
 'trust': np.int64(2261),
 'guy': np.int64(915),
 'bye': np.int64(279),
 'handsom': np.int64(935),
 'toward': np.int64(2246),
 'mummi': np.int64(1399),
 'boytoy': np.int64(247),
 'awesom': np.int64(152),
 'minut': np.int64(1340),
 'freephon': np.int64(778),
 'xma': np.int64(2462),
 'radio': np.int64(1725),
 'ju': np.int64(1126),
 'si': np.int64(1973),
 'uniqu': np.int64(2293),
 'th': np.int64(2185),
 'august': np.int64(139),
 'touch': np.int64(2243),
 'deal': np.int64(480),
 'cours': np.int64(430),
 'howev': np.int64(1018),
 'suggest': np.int64(2112),
 'abl': np.int64(6),
 'everi': np.int64(627),
 'settl': np.int64(1940),
 'mrng': np.int64(1386),
 'hav': np.int64(946),
 'stori': np.int64(2088),
 'hamster': np.int64(931),
 'dead': np.int64(479),
 'tmr': np.int64(2222),
 'orchard': np.int64(1489),
 'mrt': np.int64(1387),
 'kate': np.int64(1135),
 'found': np.int64(768),
 'buck': np.int64(265),
 'darlin': np.int64(472),
 'ive': np.int64(1096),
 'colleg': np.int64(385),
 'refil': np.int64(1777),
 'success': np.int64(2108),
 'decim': np.int64(487),
 'prepaid': np.int64(1648),
 'balanc': np.int64(160),
 'rs': np.int64(1857),
 'transact': np.int64(2250),
 'id': np.int64(1040),
 'goodmorn': np.int64(876),
 'sleep': np.int64(2002),
 'ga': np.int64(809),
 'dat': np.int64(474),
 'ericsson': np.int64(607),
 'oso': np.int64(1495),
 'cannot': np.int64(301),
 'oredi': np.int64(1491),
 'straight': np.int64(2091),
 'connect': np.int64(409),
 'refund': np.int64(1778),
 'bill': np.int64(204),
 'shoot': np.int64(1960),
 'big': np.int64(201),
 'readi': np.int64(1750),
 'break': np.int64(250),
 'semest': np.int64(1925),
 'noe': np.int64(1438),
 'leh': np.int64(1188),
 'sound': np.int64(2041),
 'head': np.int64(952),
 'slept': np.int64(2003),
 'past': np.int64(1531),
 'easi': np.int64(572),
 'sen': np.int64(1926),
 'exam': np.int64(642),
 'march': np.int64(1287),
 'atm': np.int64(132),
 'regist': np.int64(1782),
 'instal': np.int64(1070),
 'import': np.int64(1053),
 'file': np.int64(714),
 'system': np.int64(2141),
 'repair': np.int64(1799),

### N-Grams
* Used to capture contect and word relationships
* These are continuous sequences of N-words from a sentence

In [118]:
## Unigram
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=100, binary=True, ngram_range=(1,1))
X = cv.fit_transform(corpus).toarray()
X.shape

(5572, 100)

In [119]:
cv.vocabulary_

{'go': np.int64(22),
 'great': np.int64(25),
 'got': np.int64(24),
 'wat': np.int64(90),
 'ok': np.int64(56),
 'free': np.int64(18),
 'win': np.int64(94),
 'text': np.int64(77),
 'txt': np.int64(85),
 'say': np.int64(67),
 'alreadi': np.int64(0),
 'think': np.int64(80),
 'hey': np.int64(28),
 'week': np.int64(92),
 'back': np.int64(3),
 'like': np.int64(38),
 'still': np.int64(73),
 'send': np.int64(69),
 'even': np.int64(15),
 'friend': np.int64(19),
 'prize': np.int64(62),
 'claim': np.int64(7),
 'call': np.int64(4),
 'mobil': np.int64(47),
 'co': np.int64(8),
 'home': np.int64(30),
 'want': np.int64(89),
 'today': np.int64(82),
 'cash': np.int64(6),
 'day': np.int64(12),
 'repli': np.int64(64),
 'www': np.int64(96),
 'right': np.int64(65),
 'thank': np.int64(78),
 'take': np.int64(75),
 'time': np.int64(81),
 'use': np.int64(87),
 'messag': np.int64(44),
 'oh': np.int64(55),
 'ye': np.int64(97),
 'make': np.int64(42),
 'way': np.int64(91),
 'feel': np.int64(16),
 'dont': np.int64(14),
 'miss': np.int64(46),
 'ur': np.int64(86),
 'tri': np.int64(84),
 'da': np.int64(11),
 'lor': np.int64(39),
 'meet': np.int64(43),
 'realli': np.int64(63),
 'get': np.int64(20),
 'know': np.int64(33),
 'love': np.int64(40),
 'let': np.int64(37),
 'work': np.int64(95),
 'wait': np.int64(88),
 'yeah': np.int64(98),
 'tell': np.int64(76),
 'pleas': np.int64(61),
 'msg': np.int64(49),
 'see': np.int64(68),
 'pl': np.int64(60),
 'need': np.int64(51),
 'tomorrow': np.int64(83),
 'hope': np.int64(31),
 'well': np.int64(93),
 'lt': np.int64(41),
 'gt': np.int64(26),
 'ask': np.int64(1),
 'morn': np.int64(48),
 'happi': np.int64(27),
 'sorri': np.int64(72),
 'give': np.int64(21),
 'new': np.int64(52),
 'find': np.int64(17),
 'year': np.int64(99),
 'later': np.int64(35),
 'pick': np.int64(59),
 'good': np.int64(23),
 'come': np.int64(9),
 'said': np.int64(66),
 'hi': np.int64(29),
 'babe': np.int64(2),
 'im': np.int64(32),
 'much': np.int64(50),
 'stop': np.int64(74),
 'one': np.int64(57),
 'night': np.int64(53),
 'servic': np.int64(70),
 'dear': np.int64(13),
 'thing': np.int64(79),
 'contact': np.int64(10),
 'last': np.int64(34),
 'min': np.int64(45),
 'number': np.int64(54),
 'leav': np.int64(36),
 'sleep': np.int64(71),
 'care': np.int64(5),
 'phone': np.int64(58)}

In [120]:
## Unigram & Bi-gram
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=100, binary=True, ngram_range=(1,2))
X = cv.fit_transform(corpus).toarray()
X.shape

(5572, 100)

In [121]:
cv.vocabulary_

{'go': np.int64(21),
 'great': np.int64(24),
 'got': np.int64(23),
 'wat': np.int64(90),
 'ok': np.int64(56),
 'free': np.int64(17),
 'win': np.int64(94),
 'text': np.int64(77),
 'txt': np.int64(85),
 'say': np.int64(67),
 'alreadi': np.int64(0),
 'think': np.int64(80),
 'hey': np.int64(27),
 'week': np.int64(92),
 'back': np.int64(3),
 'like': np.int64(37),
 'still': np.int64(73),
 'send': np.int64(69),
 'even': np.int64(14),
 'friend': np.int64(18),
 'prize': np.int64(62),
 'claim': np.int64(7),
 'call': np.int64(4),
 'mobil': np.int64(47),
 'co': np.int64(8),
 'home': np.int64(29),
 'want': np.int64(89),
 'today': np.int64(82),
 'cash': np.int64(6),
 'day': np.int64(11),
 'repli': np.int64(64),
 'www': np.int64(96),
 'right': np.int64(65),
 'thank': np.int64(78),
 'take': np.int64(75),
 'time': np.int64(81),
 'use': np.int64(87),
 'messag': np.int64(44),
 'oh': np.int64(55),
 'ye': np.int64(97),
 'make': np.int64(42),
 'way': np.int64(91),
 'feel': np.int64(15),
 'dont': np.int64(13),
 'miss': np.int64(46),
 'ur': np.int64(86),
 'tri': np.int64(84),
 'da': np.int64(10),
 'lor': np.int64(38),
 'meet': np.int64(43),
 'realli': np.int64(63),
 'get': np.int64(19),
 'know': np.int64(32),
 'love': np.int64(39),
 'let': np.int64(36),
 'work': np.int64(95),
 'wait': np.int64(88),
 'yeah': np.int64(98),
 'tell': np.int64(76),
 'pleas': np.int64(61),
 'msg': np.int64(49),
 'see': np.int64(68),
 'pl': np.int64(60),
 'need': np.int64(51),
 'tomorrow': np.int64(83),
 'hope': np.int64(30),
 'well': np.int64(93),
 'lt': np.int64(40),
 'gt': np.int64(25),
 'lt gt': np.int64(41),
 'ask': np.int64(1),
 'morn': np.int64(48),
 'happi': np.int64(26),
 'sorri': np.int64(72),
 'give': np.int64(20),
 'new': np.int64(52),
 'find': np.int64(16),
 'year': np.int64(99),
 'later': np.int64(34),
 'pick': np.int64(59),
 'good': np.int64(22),
 'come': np.int64(9),
 'said': np.int64(66),
 'hi': np.int64(28),
 'babe': np.int64(2),
 'im': np.int64(31),
 'much': np.int64(50),
 'stop': np.int64(74),
 'one': np.int64(57),
 'night': np.int64(53),
 'servic': np.int64(70),
 'dear': np.int64(12),
 'thing': np.int64(79),
 'last': np.int64(33),
 'min': np.int64(45),
 'number': np.int64(54),
 'leav': np.int64(35),
 'sleep': np.int64(71),
 'care': np.int64(5),
 'phone': np.int64(58)}

In [122]:
## Unigram, bigram and trigram
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=100, binary=True, ngram_range=(1,3))
X = cv.fit_transform(corpus).toarray()
X.shape

(5572, 100)

In [123]:
cv.vocabulary_

{'go': np.int64(22),
 'great': np.int64(25),
 'got': np.int64(24),
 'wat': np.int64(90),
 'ok': np.int64(57),
 'free': np.int64(18),
 'win': np.int64(94),
 'text': np.int64(78),
 'txt': np.int64(86),
 'say': np.int64(68),
 'alreadi': np.int64(0),
 'think': np.int64(81),
 'hey': np.int64(28),
 'week': np.int64(92),
 'back': np.int64(3),
 'like': np.int64(38),
 'still': np.int64(74),
 'send': np.int64(70),
 'even': np.int64(15),
 'friend': np.int64(19),
 'prize': np.int64(63),
 'claim': np.int64(7),
 'call': np.int64(4),
 'mobil': np.int64(48),
 'co': np.int64(8),
 'home': np.int64(30),
 'want': np.int64(89),
 'today': np.int64(83),
 'cash': np.int64(6),
 'day': np.int64(12),
 'repli': np.int64(65),
 'www': np.int64(96),
 'right': np.int64(66),
 'thank': np.int64(79),
 'take': np.int64(76),
 'time': np.int64(82),
 'messag': np.int64(45),
 'oh': np.int64(56),
 'ye': np.int64(97),
 'make': np.int64(43),
 'way': np.int64(91),
 'feel': np.int64(16),
 'dont': np.int64(14),
 'miss': np.int64(47),
 'ur': np.int64(87),
 'tri': np.int64(85),
 'da': np.int64(11),
 'lor': np.int64(39),
 'meet': np.int64(44),
 'realli': np.int64(64),
 'get': np.int64(20),
 'know': np.int64(33),
 'love': np.int64(40),
 'let': np.int64(37),
 'work': np.int64(95),
 'wait': np.int64(88),
 'yeah': np.int64(98),
 'tell': np.int64(77),
 'pleas': np.int64(62),
 'msg': np.int64(50),
 'see': np.int64(69),
 'pl': np.int64(61),
 'need': np.int64(52),
 'tomorrow': np.int64(84),
 'hope': np.int64(31),
 'well': np.int64(93),
 'lt': np.int64(41),
 'gt': np.int64(26),
 'lt gt': np.int64(42),
 'ask': np.int64(1),
 'morn': np.int64(49),
 'happi': np.int64(27),
 'sorri': np.int64(73),
 'give': np.int64(21),
 'new': np.int64(53),
 'find': np.int64(17),
 'year': np.int64(99),
 'later': np.int64(35),
 'pick': np.int64(60),
 'good': np.int64(23),
 'come': np.int64(9),
 'said': np.int64(67),
 'hi': np.int64(29),
 'babe': np.int64(2),
 'im': np.int64(32),
 'much': np.int64(51),
 'stop': np.int64(75),
 'one': np.int64(58),
 'night': np.int64(54),
 'servic': np.int64(71),
 'dear': np.int64(13),
 'thing': np.int64(80),
 'contact': np.int64(10),
 'last': np.int64(34),
 'min': np.int64(46),
 'number': np.int64(55),
 'leav': np.int64(36),
 'sleep': np.int64(72),
 'care': np.int64(5),
 'phone': np.int64(59)}

In [124]:
## Bigram and trigram
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=100, binary=True, ngram_range=(2,3))
X = cv.fit_transform(corpus).toarray()
X.shape

(5572, 100)

In [125]:
cv.vocabulary_

{'free entri': np.int64(32),
 'claim call': np.int64(17),
 'call claim': np.int64(3),
 'free call': np.int64(31),
 'chanc win': np.int64(16),
 'txt word': np.int64(91),
 'let know': np.int64(53),
 'go home': np.int64(35),
 'pleas call': np.int64(69),
 'lt gt': np.int64(59),
 'want go': np.int64(97),
 'like lt': np.int64(54),
 'like lt gt': np.int64(55),
 'sorri call': np.int64(82),
 'call later': np.int64(11),
 'sorri call later': np.int64(83),
 'ur award': np.int64(92),
 'call custom': np.int64(4),
 'custom servic': np.int64(24),
 'cash prize': np.int64(15),
 'call custom servic': np.int64(5),
 'po box': np.int64(70),
 'tri contact': np.int64(88),
 'draw show': np.int64(28),
 'show prize': np.int64(80),
 'prize guarante': np.int64(74),
 'guarante call': np.int64(41),
 'valid hr': np.int64(95),
 'draw show prize': np.int64(29),
 'show prize guarante': np.int64(81),
 'prize guarante call': np.int64(75),
 'select receiv': np.int64(77),
 'privat account': np.int64(71),
 'account statement': np.int64(0),
 'call identifi': np.int64(6),
 'identifi code': np.int64(47),
 'code expir': np.int64(21),
 'privat account statement': np.int64(72),
 'call identifi code': np.int64(7),
 'identifi code expir': np.int64(48),
 'urgent mobil': np.int64(94),
 'call landlin': np.int64(10),
 'wat time': np.int64(98),
 'ur mob': np.int64(93),
 'gud ni': np.int64(43),
 'new year': np.int64(64),
 'send stop': np.int64(79),
 'get back': np.int64(34),
 'co uk': np.int64(20),
 'nice day': np.int64(65),
 'lt decim': np.int64(57),
 'decim gt': np.int64(26),
 'lt decim gt': np.int64(58),
 'txt nokia': np.int64(89),
 'good morn': np.int64(36),
 'good night': np.int64(37),
 'repli call': np.int64(76),
 'last night': np.int64(52),
 'pick phone': np.int64(67),
 'pl send': np.int64(68),
 'send messag': np.int64(78),
 'great day': np.int64(38),
 'suit land': np.int64(84),
 'land row': np.int64(51),
 'suit land row': np.int64(85),
 'take care': np.int64(86),
 'call mobileupd': np.int64(12),
 'call optout': np.int64(13),
 'gt min': np.int64(40),
 'lt gt min': np.int64(60),
 'txt stop': np.int64(90),
 'date servic': np.int64(25),
 'mobil number': np.int64(61),
 'call land': np.int64(8),
 'land line': np.int64(49),
 'line claim': np.int64(56),
 'claim valid': np.int64(18),
 'guarante call land': np.int64(42),
 'call land line': np.int64(9),
 'land line claim': np.int64(50),
 'claim valid hr': np.int64(19),
 'gt lt': np.int64(39),
 'hope good': np.int64(46),
 'free text': np.int64(33),
 'prize claim': np.int64(73),
 'nd attempt': np.int64(63),
 'attempt contact': np.int64(1),
 'ok lor': np.int64(66),
 'want come': np.int64(96),
 'everi week': np.int64(30),
 'come home': np.int64(23),
 'happi new': np.int64(44),
 'happi new year': np.int64(45),
 'nation rate': np.int64(62),
 'week txt': np.int64(99),
 'tell ur': np.int64(87),
 'await collect': np.int64(2),
 'dont know': np.int64(27),
 'come back': np.int64(22),
 'call per': np.int64(14)}

In [126]:
## Bigram
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=100, binary=True, ngram_range=(2,2))
X = cv.fit_transform(corpus).toarray()
X.shape

(5572, 100)

In [127]:
cv.vocabulary_

{'free entri': np.int64(33),
 'claim call': np.int64(16),
 'call claim': np.int64(3),
 'free call': np.int64(32),
 'chanc win': np.int64(15),
 'txt word': np.int64(88),
 'let know': np.int64(54),
 'go home': np.int64(37),
 'pleas call': np.int64(67),
 'lt gt': np.int64(58),
 'want go': np.int64(97),
 'first time': np.int64(31),
 'like lt': np.int64(55),
 'sorri call': np.int64(80),
 'call later': np.int64(8),
 'ur award': np.int64(90),
 'call custom': np.int64(4),
 'custom servic': np.int64(23),
 'cash prize': np.int64(14),
 'po box': np.int64(68),
 'tri contact': np.int64(85),
 'draw show': np.int64(28),
 'show prize': np.int64(79),
 'prize guarante': np.int64(73),
 'guarante call': np.int64(44),
 'valid hr': np.int64(95),
 'select receiv': np.int64(76),
 'privat account': np.int64(71),
 'account statement': np.int64(0),
 'statement show': np.int64(81),
 'call identifi': np.int64(5),
 'identifi code': np.int64(50),
 'code expir': np.int64(20),
 'urgent mobil': np.int64(94),
 'call landlin': np.int64(7),
 'wat time': np.int64(98),
 'ur mob': np.int64(93),
 'gud ni': np.int64(46),
 'repli stop': np.int64(75),
 'new year': np.int64(62),
 'send stop': np.int64(78),
 'get back': np.int64(35),
 'co uk': np.int64(19),
 'gud mrng': np.int64(45),
 'nice day': np.int64(63),
 'lt decim': np.int64(57),
 'decim gt': np.int64(25),
 'txt nokia': np.int64(86),
 'good morn': np.int64(39),
 'ur friend': np.int64(91),
 'good night': np.int64(40),
 'camcord repli': np.int64(12),
 'repli call': np.int64(74),
 'last night': np.int64(53),
 'camera phone': np.int64(13),
 'pick phone': np.int64(65),
 'pl send': np.int64(66),
 'send messag': np.int64(77),
 'great day': np.int64(41),
 'suit land': np.int64(82),
 'land row': np.int64(52),
 'good afternoon': np.int64(38),
 'take care': np.int64(83),
 'doubl min': np.int64(27),
 'call mobileupd': np.int64(9),
 'call optout': np.int64(10),
 'gt min': np.int64(43),
 'txt stop': np.int64(87),
 'date servic': np.int64(24),
 'pobox wq': np.int64(69),
 'mobil number': np.int64(59),
 'call land': np.int64(6),
 'land line': np.int64(51),
 'line claim': np.int64(56),
 'claim valid': np.int64(18),
 'gt lt': np.int64(42),
 'hope good': np.int64(49),
 'free text': np.int64(34),
 'holiday cash': np.int64(48),
 'prize claim': np.int64(72),
 'nd attempt': np.int64(61),
 'attempt contact': np.int64(1),
 'claim ur': np.int64(17),
 'un redeem': np.int64(89),
 'point call': np.int64(70),
 'ok lor': np.int64(64),
 'want come': np.int64(96),
 'everi week': np.int64(30),
 'come home': np.int64(22),
 'happi new': np.int64(47),
 'nation rate': np.int64(60),
 'week txt': np.int64(99),
 'tell ur': np.int64(84),
 'ur mate': np.int64(92),
 'gift voucher': np.int64(36),
 'await collect': np.int64(2),
 'dont know': np.int64(26),
 'come back': np.int64(21),
 'call per': np.int64(11),
 'dun wan': np.int64(29)}

In [128]:
## trigram
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=100, binary=True, ngram_range=(3,3))
X = cv.fit_transform(corpus).toarray()
X.shape

(5572, 100)

In [129]:
cv.vocabulary_

{'like lt gt': np.int64(43),
 'sorri call later': np.int64(79),
 'pleas call custom': np.int64(65),
 'call custom servic': np.int64(6),
 'custom servic repres': np.int64(22),
 'guarante cash prize': np.int64(35),
 'draw show prize': np.int64(23),
 'show prize guarante': np.int64(77),
 'prize guarante call': np.int64(70),
 'valid hr ppm': np.int64(96),
 'special select receiv': np.int64(81),
 'speak live oper': np.int64(80),
 'live oper claim': np.int64(45),
 'privat account statement': np.int64(68),
 'account statement show': np.int64(0),
 'call identifi code': np.int64(7),
 'identifi code expir': np.int64(40),
 'bonu caller prize': np.int64(4),
 'select receiv award': np.int64(76),
 'match pleas call': np.int64(54),
 'urgent tri contact': np.int64(95),
 'lt decim gt': np.int64(47),
 'secret admir look': np.int64(75),
 'admir look make': np.int64(1),
 'look make contact': np.int64(46),
 'make contact find': np.int64(53),
 'contact find reveal': np.int64(19),
 'find reveal think': np.int64(28),
 'reveal think ur': np.int64(73),
 'think ur special': np.int64(85),
 'ur special call': np.int64(92),
 'draw txt music': np.int64(24),
 'www ldew com': np.int64(99),
 'anytim network min': np.int64(2),
 'camcord repli call': np.int64(12),
 'cant pick phone': np.int64(13),
 'pick phone right': np.int64(63),
 'phone right pl': np.int64(62),
 'right pl send': np.int64(74),
 'pl send messag': np.int64(64),
 'hg suit land': np.int64(37),
 'suit land row': np.int64(84),
 'land row hl': np.int64(42),
 'call mobileupd call': np.int64(9),
 'mobileupd call optout': np.int64(57),
 'lt gt min': np.int64(49),
 'free entri weekli': np.int64(29),
 'urgent mobil number': np.int64(94),
 'mobil number award': np.int64(56),
 'guarante call land': np.int64(34),
 'call land line': np.int64(8),
 'land line claim': np.int64(41),
 'line claim valid': np.int64(44),
 'claim valid hr': np.int64(16),
 'lt gt th': np.int64(51),
 'lt gt lt': np.int64(48),
 'gt lt gt': np.int64(33),
 'caller prize nd': np.int64(11),
 'prize nd attempt': np.int64(71),
 'nd attempt contact': np.int64(58),
 'ur worth discount': np.int64(93),
 'worth discount voucher': np.int64(97),
 'statement show un': np.int64(82),
 'show un redeem': np.int64(78),
 'un redeem point': np.int64(90),
 'redeem point call': np.int64(72),
 'point call identifi': np.int64(67),
 'new video phone': np.int64(59),
 'happi new year': np.int64(36),
 'everi wk txt': np.int64(27),
 'lt gt minut': np.int64(50),
 'free st week': np.int64(30),
 'nokia tone ur': np.int64(60),
 'everi week txt': np.int64(26),
 'get txting tell': np.int64(31),
 'www getz co': np.int64(98),
 'getz co uk': np.int64(32),
 'co uk pobox': np.int64(17),
 'uk pobox wq': np.int64(89),
 'pobox wq norm': np.int64(66),
 'holiday cash await': np.int64(39),
 'cash await collect': np.int64(14),
 'await collect sae': np.int64(3),
 'collect sae cs': np.int64(18),
 'stop text call': np.int64(83),
 'tri contact today': np.int64(88),
 'contact today draw': np.int64(20),
 'today draw show': np.int64(86),
 'tone ur mob': np.int64(87),
 'ur mob everi': np.int64(91),
 'mob everi week': np.int64(55),
 'call per min': np.int64(10),
 'per min ntt': np.int64(61),
 'ltd po box': np.int64(52),
 'bt nation rate': np.int64(5),
 'prize claim easi': np.int64(69),
 'claim easi call': np.int64(15),
 'easi call per': np.int64(25),
 'costa del sol': np.int64(21),
 'holiday await collect': np.int64(38)}

In [130]:
X

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       ...,
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

### Data Preprocseeing step using TF and IDF

In [131]:
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
lemmatizer_word = WordNetLemmatizer()

In [132]:
corpus = []
for i in range(0, len(matter)):
  review=re.sub('[^a-zA-Z]',' ', matter['text'][i])
  review=review.lower()
  review=review.split()
  review=[lemmatizer_word.lemmatize(word) for word in review if not word in stopwords.words('english')]
  review=' '.join(review)
  corpus.append(review)

In [133]:
corpus

['go jurong point crazy available bugis n great world la e buffet cine got amore wat',
 'ok lar joking wif u oni',
 'free entry wkly comp win fa cup final tkts st may text fa receive entry question std txt rate c apply',
 'u dun say early hor u c already say',
 'nah think go usf life around though',
 'freemsg hey darling week word back like fun still tb ok xxx std chgs send rcv',
 'even brother like speak treat like aid patent',
 'per request melle melle oru minnaminunginte nurungu vettam set callertune caller press copy friend callertune',
 'winner valued network customer selected receivea prize reward claim call claim code kl valid hour',
 'mobile month u r entitled update latest colour mobile camera free call mobile update co free',
 'gonna home soon want talk stuff anymore tonight k cried enough today',
 'six chance win cash pound txt csh send cost p day day tsandcs apply reply hl info',
 'urgent week free membership prize jackpot txt word claim c www dbuk net lccltd pobox ldnw rw',
 'searching right word thank breather promise wont take help granted fulfil promise wonderful blessing time',
 'date sunday',
 'xxxmobilemovieclub use credit click wap link next txt message click http wap xxxmobilemovieclub com n qjkgighjjgcbl',
 'oh k watching',
 'eh u remember spell name yes v naughty make v wet',
 'fine way u feel way gota b',
 'england v macedonia dont miss goal team news txt ur national team eg england try wale scotland txt poboxox w wq',
 'seriously spell name',
 'going try month ha ha joking',
 'pay first lar da stock comin',
 'aft finish lunch go str lor ard smth lor u finish ur lunch already',
 'ffffffffff alright way meet sooner',
 'forced eat slice really hungry tho suck mark getting worried know sick turn pizza lol',
 'lol always convincing',
 'catch bus frying egg make tea eating mom left dinner feel love',
 'back amp packing car let know room',
 'ahhh work vaguely remember feel like lol',
 'wait still clear sure sarcastic x want live u',
 'yeah got v apologetic n fallen actin like spoilt child got caught till go badly cheer',
 'k tell anything',
 'fear fainting housework quick cuppa',
 'thanks subscription ringtone uk mobile charged month please confirm replying yes reply charged',
 'yup ok go home look timing msg xuhui going learn nd may lesson',
 'oops let know roommate done',
 'see letter b car',
 'anything lor u decide',
 'hello saturday go texting see decided anything tomo trying invite anything',
 'pls go ahead watt wanted sure great weekend abiola',
 'forget tell want need crave love sweet arabian steed mmmmmm yummy',
 'rodger burn msg tried call reply sm free nokia mobile free camcorder please call delivery tomorrow',
 'seeing',
 'great hope like man well endowed lt gt inch',
 'call message missed call',
 'get hep b immunisation nigeria',
 'fair enough anything going',
 'yeah hopefully tyler could maybe ask around bit',
 'u know stubborn even want go hospital kept telling mark weak sucker hospital weak sucker',
 'thinked first time saw class',
 'gram usually run like lt gt half eighth smarter though get almost whole second gram lt gt',
 'k fyi x ride early tomorrow morning crashing place tonight',
 'wow never realized embarassed accomodations thought liked since best could always seemed happy cave sorry give sorry offered sorry room embarassing',
 'sm ac sptv new jersey devil detroit red wing play ice hockey correct incorrect end reply end sptv',
 'know mallika sherawat yesterday find lt url gt',
 'congrats year special cinema pas call c suprman v matrix starwars etc free bx ip pm dont miss',
 'sorry call later meeting',
 'tell reached',
 'yes gauti sehwag odi series',
 'gonna pick burger way home even move pain killing',
 'ha ha ha good joke girl situation seeker',
 'part checking iq',
 'sorry roommate took forever ok come',
 'ok lar double check wif da hair dresser already said wun cut v short said cut look nice',
 'valued customer pleased advise following recent review mob awarded bonus prize call',
 'today song dedicated day song u dedicate send ur valuable frnds first rply',
 'urgent ur awarded complimentary trip eurodisinc trav aco entry claim txt dis morefrmmob shracomorsglsuplt l aj',
 'hear new divorce barbie come ken stuff',
 'plane give month end',
 'wah lucky man save money hee',
 'finished class',
 'hi babe im home wanna something xx',
 'k k performed',
 'u call',
 'waiting machan call free',
 'thats cool gentleman treat dignity respect',
 'like people much shy pa',
 'operate lt gt',
 'still looking job much ta earn',
 'sorry call later',
 'k call ah',
 'ok way home hi hi',
 'place man',
 'yup next stop',
 'call later network urgnt sm',
 'real u getting yo need ticket one jacket done already used multis',
 'yes started send request make pain came back back bed double coin factory gotta cash nitros',
 'really still tonight babe',
 'ela kano il download come wen ur free',
 'yeah stand close tho catch something',
 'sorry pain ok meet another night spent late afternoon casualty mean done stuff moro includes time sheet sorry',
 'smile pleasure smile pain smile trouble pours like rain smile sum hurt u smile becoz someone still love see u smiling',
 'please call customer service representative pm guaranteed cash prize',
 'havent planning buy later check already lido got show e afternoon u finish work already',
 'free ringtone waiting collected simply text password mix verify get usher britney fml po box mk h ppw',
 'watching telugu movie wat abt u',
 'see finish load loan pay',
 'hi wk ok hols yes bit run forgot hairdresser appointment four need get home n shower beforehand cause prob u',
 'see cup coffee animation',
 'please text anymore nothing else say',
 'okay name ur price long legal wen pick u ave x am xx',
 'still looking car buy gone driving test yet',
 'per request melle melle oru minnaminunginte nurungu vettam set callertune caller press copy friend callertune',
 'wow right mean guess gave boston men changed search location nyc something changed cuz signin page still say boston',
 'umma life vava umma love lot dear',
 'thanks lot wish birthday thanks making birthday truly memorable',
 'aight hit get cash',
 'would ip address test considering computer minecraft server',
 'know grumpy old people mom like better lying always one play joke',
 'dont worry guess busy',
 'plural noun research',
 'going dinner msg',
 'ok wif co like try new thing scared u dun like mah co u said loud',
 'gent trying contact last weekend draw show prize guaranteed call claim code k valid hr ppm',
 'wa ur openin sentence formal anyway fine juz tt eatin much n puttin weight haha anythin special happened',
 'entered cabin pa said happy b day bos felt special askd lunch lunch invited apartment went',
 'winner u specially selected receive holiday flight inc speak live operator claim p min',
 'goodo yes must speak friday egg potato ratio tortilla needed',
 'hmm uncle informed paying school directly pls buy food',
 'private account statement show unredeemed bonus point claim call identifier code expires',
 'urgent mobile awarded bonus caller prize final try contact u call landline box wr c ppm',
 'new address apple pair malarky',
 'today voda number ending selected receive award match please call quoting claim code standard rate app',
 'going sao mu today done',
 'predict wat time finish buying',
 'good stuff',
 'know yetunde sent money yet sent text bother sending dont involve anything imposed anything first place apologise',
 'room',
 'hey girl r u hope u r well del r bak long time c give call sum time lucyxx',
 'k k much cost',
 'home',
 'dear call tmorrow pls accomodate',
 'first answer question',
 'sunshine quiz wkly q win top sony dvd player u know country algarve txt ansr sp tyrone',
 'want get laid tonight want real dogging location sent direct ur mob join uk largest dogging network bt txting gravel nt ec p msg p',
 'haf msn yijue hotmail com',
 'call meet',
 'check room befor activity',
 'rcv msg chat svc free hardcore service text go u get nothing u must age verify yr network try',
 'got c lazy type forgot lect saw pouch like v nice',
 'k text way',
 'sir waiting mail',
 'swt thought nver get tired little thing lovable person coz somtimes little thing occupy biggest part heart gud ni',
 'know pls open back',
 'yes see ya dot',
 'whats staff name taking class u',
 'freemsg replied text randy sexy female live local luv hear u netcollex ltd p per msg reply stop end',
 'ummma call check life begin qatar pls pray hard',
 'k deleted contact',
 'sindu got job birla soft',
 'wine flowing nevering',
 'yup thk cine better co need go plaza mah',
 'ok ur typical reply',
 'per request melle melle oru minnaminunginte nurungu vettam set callertune caller press copy friend callertune',
 'everywhere dirt floor window even shirt sometimes open mouth come flowing dream world without half chore time joy lot tv show see guess like thing must exist like rain hail mist time done become one',
 'aaooooright work',
 'leaving house',
 'hello love get interview today happy good boy think missing',
 'customer service annoncement new year delivery waiting please call arrange delivery',
 'winner u specially selected receive cash holiday flight inc speak live operator claim',
 'keep safe need miss already envy everyone see real life',
 'new car house parent new job hand',
 'love excited day spend make happy',
 'pls stop bootydelious f inviting friend reply yes see www sm ac u bootydelious stop send stop frnd',
 'bangbabes ur order way u receive service msg download ur content u goto wap bangb tv ur mobile internet service menu',
 'place ur point e culture module already',
 'urgent trying contact last weekend draw show prize guaranteed call claim code valid hr',
 'hi frnd best way avoid missunderstding wit beloved one',
 'great escape fancy bridge need lager see tomo',
 'yes completely form clark also utter waste',
 'sir need axis bank account bank address',
 'hmmm thk sure got time hop ard ya go free abt muz call u discus liao',
 'time coming later',
 'bloody hell cant believe forgot surname mr ill give u clue spanish begin',
 'well gonna finish bath good fine night',
 'let know got money carlos make call',
 'u still going mall',
 'turn friend staying whole show back til lt gt feel free go ahead smoke lt gt worth',
 'text doesnt reply let know log',
 'hi spoke maneesha v like know satisfied experience reply toll free yes',
 'lifted hope offer money need especially end month approach hurt studying anyways gr weekend',
 'lol u trust',
 'ok gentleman treat dignity respect',
 'guy close',
 'going nothing great bye',
 'hello handsome finding job lazy working towards getting back net mummy boytoy miss',
 'haha awesome minute',
 'please call customer service representative freephone pm guaranteed cash prize',
 'got xmas radio time get',
 'jus reached home go bathe first si using net tell u finish k',
 'unique enough find th august www areyouunique co uk',
 'sorry joined league people dont keep touch mean great deal friend time even great personal cost great week',
 'hi finally completed course',
 'stop however suggest stay someone able give or every stool',
 'hope settled new school year wishin gr day',
 'gud mrng dear hav nice day',
 'u got person story',
 'hamster dead hey tmr meet pm orchard mrt',
 'hi kate evening hope see tomorrow bit bloody babyjontet txt back u xxx',
 'found enc lt gt',
 'sent lt gt buck',
 'hello darlin ive finished college txt u finish u love kate xxx',
 'account refilled successfully inr lt decimal gt keralacircle prepaid account balance r lt decimal gt transaction id kr lt gt',
 'goodmorning sleeping ga',
 'u call alter ok',
 'say like dat dun buy ericsson oso cannot oredi lar',
 'entered cabin pa said happy b day bos felt special askd lunch lunch invited apartment went',
 'aight yo dat straight dogg',
 'please give u connection today lt decimal gt refund bill',
 'shoot big load get ready',
 'bruv hope great break rewarding semester',
 'home always chat',
 'k k good study well',
 'yup noe leh',
 'sound great home',
 'finally match heading towards draw prediction',
 'tired slept well past night',
 'easy ah sen got selected mean good',
 'take exam march',
 'yeah think use gt atm register sure anyway help let know sure ready',
 'ok prob take ur time',
 'o called ubandu run without installing hard disk use o copy important file system give repair shop',
 'sorry call later',
 'u say leh course nothing happen lar say v romantic jus bit lor thk e nite scenery nice leh',
 'new mobile must go txt nokia collect today www tc biz optout gbp mtmsg',
 'would really appreciate call need someone talk',
 'u meet ur dream partner soon ur career flyng start find free txt horo followed ur star sign e g horo aries',
 'hey company elama po mudyadhu',
 'life strict teacher bcoz teacher teach lesson amp conduct exam life first conduct exam amp teach lesson happy morning',
 'dear good morning',
 'get gandhipuram walk cross cut road right side lt gt street road turn first right',
 'dear going rubber place',
 'sorry battery died yeah',
 'yes tv always available work place',
 'text meet someone sexy today u find date even flirt u join p reply name age eg sam msg recd thirtyeight penny',
 'printed oh lt gt come upstairs',
 'ill little closer like bus stop street',
 'wil reach',
 'new theory argument win situation loses person dont argue ur friend kick amp say always correct',
 'u secret admirer looking make contact u find r reveal think ur special call',
 'tomarrow final hearing laptop case cant',
 'pleassssssseeeeee tel v avent done sportsx',
 'okay shining meant signing sound better',
 'although told u dat baig face watch really like e watch u gave co fr u thanx everything dat u done today touched',
 'u remember old commercial',
 'late said website dont slipper',
 'asked call ok',
 'kallis wont bat nd inning',
 'didnt work oh ok goodnight fix ready time wake dearly missed good night sleep',
 'congratulation ur awarded cd voucher gift guaranteed free entry wkly draw txt music tncs www ldew com win ppmx age',
 'ranjith cal drpd deeraj deepak min hold',
 'wen ur lovable bcums angry wid u dnt take seriously coz angry childish n true way showing deep affection care n luv kettoda manda nice day da',
 '',
 'ups day also shipping company take wks way usps take week get lag may bribe nipost get stuff',
 'back lemme know ready',
 'necessarily expect done get back though headin',
 'mmm yummy babe nice jolt suzy',
 'lover need',
 'tried contact reply offer video handset anytime network min unlimited text camcorder reply call',
 'parked next mini coming today think',
 'yup',
 'anyway going shopping co si done yet dun disturb u liao',
 'luton ring ur around h',
 'hey really horny want chat see naked text hot text charged pm unsubscribe text stop',
 'dint come u',
 'wana plan trip sometme',
 'sure yet still trying get hold',
 'ur ringtone service changed free credit go club mobile com choose content stop txt club stop p wk club po box mk wt',
 'evo download flash jealous',
 'ringtone club get uk single chart mobile week choose top quality ringtone message free charge',
 'come mu sorting narcotic situation',
 'night ended another day morning come special way may smile like sunny ray leaf worry blue blue bay',
 'hmv bonus special pound genuine hmv voucher answer easy question play send hmv info www percent real com',
 'usf guess might well take car',
 'objection bf coming',
 'thanx',
 'tell rob mack gf theater',
 'awesome see bit',
 'sent type food like',
 'done handed celebration full swing yet',
 'got called tool',
 'wen u miss someone person definitely special u person special miss keep touch gdeve',
 'ok asked money far',
 'okie',
 'yeah think usual guy still passed last night get ahold anybody let know throw',
 'k might come tonight class let early',
 'ok',
 'hi baby im cruisin girl friend r u give call hour home thats alright fone fone love jenny xxx',
 'life mean lot love life love people life world call friend call world ge',
 'dear shall mail tonite busy street shall update tonite thing looking ok varunnathu edukkukayee raksha ollu good one real sense',
 'hey told name gautham ah',
 'haf u found feel stupid da v cam working',
 'oops got bit',
 'much buzy',
 'accidentally deleted message resend please',
 'mobile customer may claim free camera phone upgrade pay go sim card loyalty call offer end thfeb c apply',
 'unless situation go gurl would appropriate',
 'hurt tease make cry end life die plz keep one rose grave say stupid miss u nice day bslvyl',
 'cant pick phone right pls send message',
 'need coffee run tomo believe time week already',
 'awesome remember last time got somebody high first time diesel v',
 'shit really shocking scary cant imagine second def night u think somewhere could crash night save taxi',
 'oh way food fridge want go meal tonight',
 'womdarfull actor',
 'sm ac blind date u rodds aberdeen united kingdom check http img sm ac w icmb cktz r blind date send hide',
 'yup remb think book',
 'jos ask u wana meet',
 'lol yes friendship hanging thread cause u buy stuff',
 'themob check newest selection content game tone gossip babe sport keep mobile fit funky text wap',
 'garage key bookshelf',
 'today accept day u accept brother sister lover dear best clos lvblefrnd jstfrnd cutefrnd lifpartnr belovd swtheart bstfrnd rply mean enemy',
 'think ur smart win week weekly quiz text play c winnersclub po box uz gbp week',
 'say give call friend got money definitely buying end week',
 'hi way u day normal way real ur unique hope know u rest mylife hope u find wot lost',
 'made day great day',
 'k k advance happy pongal',
 'hmmm guess go kb n power yoga haha dunno tahan power yoga anot thk got lo oso forgot liao',
 'really dude friend afraid',
 'december mobile mths entitled update latest colour camera mobile free call mobile update co free',
 'coffee cake guess',
 'merry christmas babe love ya kiss',
 'hey dont go watch x men lunch haha',
 'cud u tell ppl im gona b bit l co bus hav gon past co full im still waitin pete x',
 'would great guild could meet bristol road somewhere get touch weekend plan take flight good week',
 'problem',
 'call message missed call',
 'hi da today class',
 'say good sign well know track record reading woman',
 'cool text parked',
 'reading text sent meant joke read light',
 'k k apo k good movie',
 'maybe could get book tomo return immediately something',
 'call germany penny per minute call fixed line via access number prepayment direct access',
 'chance might evaporated soon violated privacy stealing phone number employer paperwork cool please contact report supervisor',
 'valentine day special win quiz take partner trip lifetime send go p msg rcvd custcare',
 'ta daaaaa home babe still',
 'cool come havent wined dined',
 'sleeping surfing',
 'sorry call later',
 'u calling right call hand phone',
 'ok great thanx lot',
 'take post come must text happy reading one wiv hello caroline end favourite bless',
 'u hiding stranger',
 'interested like',
 'sister cleared two round birla soft yesterday',
 'gudnite tc practice going',
 'dis yijue jus saw ur mail case huiming havent sent u num dis num',
 'one small prestige problem',
 'fancy shag interested sextextuk com txt xxuk suzy txts cost per msg tncs website x',
 'checking really miss seeing jeremiah great month',
 'nah help never iphone',
 'car hour half going apeshit',
 'today sorry day ever angry ever misbehaved hurt plz plz slap urself bcoz ur fault basically good',
 'yo guy ever figure much need alcohol jay trying figure much safely spend weed',
 'lt gt ish minute minute ago wtf',
 'thank calling forgot say happy onam sirji fine remembered met insurance person meet qatar insha allah rakhesh ex tata aig joined tissco tayseer',
 'congratulation ur awarded cd voucher gift guaranteed free entry wkly draw txt music tncs www ldew com win ppmx age',
 'ur cash balance currently pound maximize ur cash send cash p msg cc hg suite land row w j hl',

### Term Frequency (TF) and Inverse Dicument Frequency (IDF)

In [134]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer(max_features=100)
X = tfidf.fit_transform(corpus).toarray()

In [135]:
X

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.434, 0, 0, 0.461, 0.544, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.55, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.456, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0.473, 0, 0, 0, 0, 0, 0, 0, 0.492, 0, 0, 0, 0, 0, 0, 0, 0.571, 0, 0, 0, 0, 0, 0],
       [0.465, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.486, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.574, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0.389, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0.365, 0, 0, 0.384, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.403, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0.283, 0, 0, 0.85, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0.189, 0, 0, 0, 0.275, 0, 0, 0, 0, 0, 0, 0, 0.481, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.58, 0, 0, 0, 0, 0, 0.56, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0.39, 0, 0, 0, 0, 0, 0.6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0.323, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.334, 0, 0, 0, 0, 0, 0, 0, 0.387, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.422, 0, 0, 0, 0, 0, 0, 0, 0, 0.357, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.385, 0, 0, 0, 0, 0, 0.411, 0, 0, 0, 0, 0.429, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0.57, 0, 0, 0, 0, 0, 0.517, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.624, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.529, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.717],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.388, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.744, 0, 0.322, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0.429, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.329, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.325, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.695, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0.556, 0, 0, 0, 0.481, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.766, 0, 0, 0, 0, 0],
       ...,
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.602, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.675, 0, 0, 0, ..., 0, 0, 0, 0.738, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0.577, 0, 0, 0, 0.499, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0.466, 0, 0, 0, 0.449, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0.55, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.328, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0.679, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.391],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.507, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.643, 0.574, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.597, 0, 0, 0, 0, 0, 0.802, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0.558, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.444, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.514, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.415, 0, 0, 0, 0, 0, 0, 0, 0, 0.695, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.44, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.711],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.597, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.382, 0],
       [0, 0, 0, 0, 0, 0, 0, 0.445, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0.624, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.707, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0.498, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.749, 0, 0, 0, 0, 0, 0, 0, 0.663, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0.553, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.628, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0.287, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.364, 0, 0.321, 0, 0, 0, 0, 0, 0.431, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0.378, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0.369, 0, 0, 0.555, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.469, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.706, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.548, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.631, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

### Applying N-gram technique

In [136]:
tfidf = TfidfVectorizer(max_features=100, ngram_range=(2,2))
X = tfidf.fit_transform(corpus).toarray()

In [137]:
tfidf.vocabulary_

{'free entry': np.int64(33),
 'claim call': np.int64(16),
 'call claim': np.int64(3),
 'claim code': np.int64(17),
 'free call': np.int64(32),
 'chance win': np.int64(15),
 'txt word': np.int64(89),
 'let know': np.int64(54),
 'please call': np.int64(68),
 'lt gt': np.int64(58),
 'want go': np.int64(97),
 'first time': np.int64(31),
 'like lt': np.int64(55),
 'sorry call': np.int64(80),
 'call later': np.int64(8),
 'ur awarded': np.int64(90),
 'hi hi': np.int64(47),
 'call customer': np.int64(4),
 'customer service': np.int64(24),
 'guaranteed cash': np.int64(43),
 'cash prize': np.int64(14),
 'po box': np.int64(70),
 'trying contact': np.int64(86),
 'draw show': np.int64(29),
 'show prize': np.int64(79),
 'prize guaranteed': np.int64(74),
 'guaranteed call': np.int64(42),
 'valid hr': np.int64(95),
 'selected receive': np.int64(76),
 'private account': np.int64(72),
 'account statement': np.int64(0),
 'statement show': np.int64(82),
 'call identifier': np.int64(5),
 'identifier code': np.int64(50),
 'code expires': np.int64(21),
 'urgent mobile': np.int64(94),
 'call landline': np.int64(7),
 'wat time': np.int64(98),
 'ur mob': np.int64(93),
 'gud ni': np.int64(45),
 'new year': np.int64(64),
 'send stop': np.int64(78),
 'co uk': np.int64(20),
 'gud mrng': np.int64(44),
 'nice day': np.int64(65),
 'lt decimal': np.int64(57),
 'decimal gt': np.int64(26),
 'txt nokia': np.int64(87),
 'good morning': np.int64(37),
 'ur friend': np.int64(92),
 'good night': np.int64(38),
 'network min': np.int64(62),
 'camcorder reply': np.int64(12),
 'reply call': np.int64(75),
 'last night': np.int64(53),
 'camera phone': np.int64(13),
 'pick phone': np.int64(67),
 'pls send': np.int64(69),
 'send message': np.int64(77),
 'great day': np.int64(39),
 'ur cash': np.int64(91),
 'suite land': np.int64(83),
 'land row': np.int64(52),
 'good afternoon': np.int64(36),
 'take care': np.int64(84),
 'double min': np.int64(28),
 'call mobileupd': np.int64(9),
 'call optout': np.int64(10),
 'gt min': np.int64(41),
 'txt stop': np.int64(88),
 'dating service': np.int64(25),
 'pobox wq': np.int64(71),
 'mobile number': np.int64(59),
 'call land': np.int64(6),
 'land line': np.int64(51),
 'line claim': np.int64(56),
 'claim valid': np.int64(19),
 'gt lt': np.int64(40),
 'hope good': np.int64(49),
 'free text': np.int64(34),
 'holiday cash': np.int64(48),
 'prize claim': np.int64(73),
 'nd attempt': np.int64(61),
 'attempt contact': np.int64(1),
 'claim ur': np.int64(18),
 'ok lor': np.int64(66),
 'want come': np.int64(96),
 'every week': np.int64(30),
 'come home': np.int64(23),
 'new nokia': np.int64(63),
 'happy new': np.int64(46),
 'national rate': np.int64(60),
 'st week': np.int64(81),
 'week txt': np.int64(99),
 'tell ur': np.int64(85),
 'gift voucher': np.int64(35),
 'await collection': np.int64(2),
 'dont know': np.int64(27),
 'come back': np.int64(22),
 'call per': np.int64(11)}

### Word2Vec

In [138]:
!pip install gensim

Requirement already satisfied: gensim in /usr/local/lib/python3.12/dist-packages (4.4.0)
Requirement already satisfied: numpy>=1.18.5 in /usr/local/lib/python3.12/dist-packages (from gensim) (2.0.2)
Requirement already satisfied: scipy>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from gensim) (1.16.3)
Requirement already satisfied: smart_open>=1.8.1 in /usr/local/lib/python3.12/dist-packages (from gensim) (7.5.1)
Requirement already satisfied: wrapt in /usr/local/lib/python3.12/dist-packages (from smart_open>=1.8.1->gensim) (2.1.2)

In [139]:
from gensim.models import Word2Vec, KeyedVectors

### Using a word2vec model, trained and developed by stanford NLP Group

In [140]:
import gensim.downloader as api
w2v = api.load("glove-wiki-gigaword-100")
king_vec = w2v["king"]

In [141]:
king_vec.shape

(100,)

In [142]:
w2v["football"]

array([0.439, 0.105, 0.46, -1.07, -1.25, 0.764, 0.475, 0.0839, -0.913, -0.273, -0.0186, -1.18, 0.227, 0.168, -0.522, 0.113, 1.38, 0.119, -0.377, 0.511, -0.883, 0.963, 0.181, -0.407, 0.0362, -0.744, -0.00274, -0.701, 0.531, 0.451, -0.729, 1.06, -0.28, -0.638, 0.156, -0.469, -1.01, 1.03, -1.44, -0.275, 0.049, 0.14, 0.431, -0.788, 0.411, 0.585, 1.02, -0.184, 0.275, -0.909, -0.304, -0.174, 0.0209, 0.628, 0.11, -2.39, -0.564, -0.272, 0.987, 0.706, -0.512, 0.526, -0.785, -0.687, 0.381, 0.0976, -0.202, 0.432, -0.305, 0.579, 0.626, -0.474, 0.338, -0.284, -0.0975, 0.196, 0.548, 0.599, -0.416, 0.102, 0.677, 0.0042, -0.124, -0.766, -0.274, -0.682, -1.08, -0.167, 0.817, 0.027, -0.387, 0.404, -1.1, 0.647, -0.128, -0.261, -0.967, 0.881, 1.01, -0.0222], dtype=float32)

In [143]:
w2v.most_similar("stress")

[('pain', 0.725872278213501),
 ('anxiety', 0.7095138430595398),
 ('fatigue', 0.7049359679222107),
 ('mental', 0.701725423336029),
 ('psychological', 0.6904554963111877),
 ('physical', 0.6795199513435364),
 ('severe', 0.6727946400642395),
 ('problems', 0.6613970994949341),
 ('risk', 0.6541153788566589),
 ('muscle', 0.645975649356842)]

In [144]:
w2v.similarity("anxiety", "stress")

np.float32(0.70951384)

In [145]:
matter

     label                                               text
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham               Will ü b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

### 1. Data Preprocessing

In [146]:
# Importing nltk, re, stopwords and wordnet (for lemmatization)
import pandas as pd
import numpy as np
import nltk
import re
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [147]:
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer, WordNetLemmatizer
port_stemmer = PorterStemmer()

In [148]:
corpus = []
for i in range(0, len(matter)):
  review = re.sub('[^a-zA-Z]', ' ', matter['text'][i])
  review=review.lower()
  review = review.split()
  review=[port_stemmer.stem(word) for word in review if not word in stopwords.words('english')]
  review=' '.join(review)
  corpus.append(review)

In [149]:
corpus

['go jurong point crazi avail bugi n great world la e buffet cine got amor wat',
 'ok lar joke wif u oni',
 'free entri wkli comp win fa cup final tkt st may text fa receiv entri question std txt rate c appli',
 'u dun say earli hor u c alreadi say',
 'nah think goe usf live around though',
 'freemsg hey darl week word back like fun still tb ok xxx std chg send rcv',
 'even brother like speak treat like aid patent',
 'per request mell mell oru minnaminungint nurungu vettam set callertun caller press copi friend callertun',
 'winner valu network custom select receivea prize reward claim call claim code kl valid hour',
 'mobil month u r entitl updat latest colour mobil camera free call mobil updat co free',
 'gonna home soon want talk stuff anymor tonight k cri enough today',
 'six chanc win cash pound txt csh send cost p day day tsandc appli repli hl info',
 'urgent week free membership prize jackpot txt word claim c www dbuk net lccltd pobox ldnw rw',
 'search right word thank breather promis wont take help grant fulfil promis wonder bless time',
 'date sunday',
 'xxxmobilemovieclub use credit click wap link next txt messag click http wap xxxmobilemovieclub com n qjkgighjjgcbl',
 'oh k watch',
 'eh u rememb spell name ye v naughti make v wet',
 'fine way u feel way gota b',
 'england v macedonia dont miss goal team news txt ur nation team eg england tri wale scotland txt poboxox w wq',
 'serious spell name',
 'go tri month ha ha joke',
 'pay first lar da stock comin',
 'aft finish lunch go str lor ard smth lor u finish ur lunch alreadi',
 'ffffffffff alright way meet sooner',
 'forc eat slice realli hungri tho suck mark get worri know sick turn pizza lol',
 'lol alway convinc',
 'catch bu fri egg make tea eat mom left dinner feel love',
 'back amp pack car let know room',
 'ahhh work vagu rememb feel like lol',
 'wait still clear sure sarcast x want live us',
 'yeah got v apologet n fallen actin like spoilt child got caught till go badli cheer',
 'k tell anyth',
 'fear faint housework quick cuppa',
 'thank subscript rington uk mobil charg month pleas confirm repli ye repli charg',
 'yup ok go home look time msg xuhui go learn nd may lesson',
 'oop let know roommat done',
 'see letter b car',
 'anyth lor u decid',
 'hello saturday go text see decid anyth tomo tri invit anyth',
 'pl go ahead watt want sure great weekend abiola',
 'forget tell want need crave love sweet arabian steed mmmmmm yummi',
 'rodger burn msg tri call repli sm free nokia mobil free camcord pleas call deliveri tomorrow',
 'see',
 'great hope like man well endow lt gt inch',
 'call messag miss call',
 'get hep b immunis nigeria',
 'fair enough anyth go',
 'yeah hope tyler could mayb ask around bit',
 'u know stubborn even want go hospit kept tell mark weak sucker hospit weak sucker',
 'think first time saw class',
 'gram usual run like lt gt half eighth smarter though get almost whole second gram lt gt',
 'k fyi x ride earli tomorrow morn crash place tonight',
 'wow never realiz embarass accomod thought like sinc best could alway seem happi cave sorri give sorri offer sorri room embarass',
 'sm ac sptv new jersey devil detroit red wing play ice hockey correct incorrect end repli end sptv',
 'know mallika sherawat yesterday find lt url gt',
 'congrat year special cinema pass call c suprman v matrix starwar etc free bx ip pm dont miss',
 'sorri call later meet',
 'tell reach',
 'ye gauti sehwag odi seri',
 'gonna pick burger way home even move pain kill',
 'ha ha ha good joke girl situat seeker',
 'part check iq',
 'sorri roommat took forev ok come',
 'ok lar doubl check wif da hair dresser alreadi said wun cut v short said cut look nice',
 'valu custom pleas advis follow recent review mob award bonu prize call',
 'today song dedic day song u dedic send ur valuabl frnd first rpli',
 'urgent ur award complimentari trip eurodisinc trav aco entri claim txt di morefrmmob shracomorsglsuplt ls aj',
 'hear new divorc barbi come ken stuff',
 'plane give month end',
 'wah lucki man save money hee',
 'finish class',
 'hi babe im home wanna someth xx',
 'k k perform',
 'u call',
 'wait machan call free',
 'that cool gentleman treat digniti respect',
 'like peopl much shi pa',
 'oper lt gt',
 'still look job much ta earn',
 'sorri call later',
 'k call ah',
 'ok way home hi hi',
 'place man',
 'yup next stop',
 'call later network urgnt sm',
 'real u get yo need ticket one jacket done alreadi use multi',
 'ye start send request make pain came back back bed doubl coin factori gotta cash nitro',
 'realli still tonight babe',
 'ela kano il download come wen ur free',
 'yeah stand close tho catch someth',
 'sorri pain ok meet anoth night spent late afternoon casualti mean done stuff moro includ time sheet sorri',
 'smile pleasur smile pain smile troubl pour like rain smile sum hurt u smile becoz someon still love see u smile',
 'pleas call custom servic repres pm guarante cash prize',
 'havent plan buy later check alreadi lido got show e afternoon u finish work alreadi',
 'free rington wait collect simpli text password mix verifi get usher britney fml po box mk h ppw',
 'watch telugu movi wat abt u',
 'see finish load loan pay',
 'hi wk ok hol ye bit run forgot hairdress appoint four need get home n shower beforehand caus prob u',
 'see cup coffe anim',
 'pleas text anymor noth els say',
 'okay name ur price long legal wen pick u ave x am xx',
 'still look car buy gone drive test yet',
 'per request mell mell oru minnaminungint nurungu vettam set callertun caller press copi friend callertun',
 'wow right mean guess gave boston men chang search locat nyc someth chang cuz signin page still say boston',
 'umma life vava umma love lot dear',
 'thank lot wish birthday thank make birthday truli memor',
 'aight hit get cash',
 'would ip address test consid comput minecraft server',
 'know grumpi old peopl mom like better lie alway one play joke',
 'dont worri guess busi',
 'plural noun research',
 'go dinner msg',
 'ok wif co like tri new thing scare u dun like mah co u said loud',
 'gent tri contact last weekend draw show prize guarante call claim code k valid hr ppm',
 'wa ur openin sentenc formal anyway fine juz tt eatin much n puttin weight haha anythin special happen',
 'enter cabin pa said happi b day boss felt special askd lunch lunch invit apart went',
 'winner u special select receiv holiday flight inc speak live oper claim p min',
 'goodo ye must speak friday egg potato ratio tortilla need',
 'hmm uncl inform pay school directli pl buy food',
 'privat account statement show unredeem bonu point claim call identifi code expir',
 'urgent mobil award bonu caller prize final tri contact u call landlin box wr c ppm',
 'new address appl pair malarki',
 'today voda number end select receiv award match pleas call quot claim code standard rate app',
 'go sao mu today done',
 'predict wat time finish buy',
 'good stuff',
 'know yetund sent money yet sent text bother send dont involv anyth impos anyth first place apologis',
 'room',
 'hey girl r u hope u r well del r bak long time c give call sum time lucyxx',
 'k k much cost',
 'home',
 'dear call tmorrow pl accomod',
 'first answer question',
 'sunshin quiz wkli q win top soni dvd player u know countri algarv txt ansr sp tyron',
 'want get laid tonight want real dog locat sent direct ur mob join uk largest dog network bt txting gravel nt ec p msg p',
 'haf msn yiju hotmail com',
 'call meet',
 'check room befor activ',
 'rcv msg chat svc free hardcor servic text go u get noth u must age verifi yr network tri',
 'got c lazi type forgot lect saw pouch like v nice',
 'k text way',
 'sir wait mail',
 'swt thought nver get tire littl thing lovabl person coz somtim littl thing occupi biggest part heart gud ni',
 'know pl open back',
 'ye see ya dot',
 'what staff name take class us',
 'freemsg repli text randi sexi femal live local luv hear u netcollex ltd p per msg repli stop end',
 'ummma call check life begin qatar pl pray hard',
 'k delet contact',
 'sindu got job birla soft',
 'wine flow never',
 'yup thk cine better co need go plaza mah',
 'ok ur typic repli',
 'per request mell mell oru minnaminungint nurungu vettam set callertun caller press copi friend callertun',
 'everywher dirt floor window even shirt sometim open mouth come flow dream world without half chore time joy lot tv show see guess like thing must exist like rain hail mist time done becom one',
 'aaooooright work',
 'leav hous',
 'hello love get interview today happi good boy think miss',
 'custom servic annonc new year deliveri wait pleas call arrang deliveri',
 'winner u special select receiv cash holiday flight inc speak live oper claim',
 'keep safe need miss alreadi envi everyon see real life',
 'new car hous parent new job hand',
 'love excit day spend make happi',
 'pl stop bootydeli f invit friend repli ye see www sm ac u bootydeli stop send stop frnd',
 'bangbab ur order way u receiv servic msg download ur content u goto wap bangb tv ur mobil internet servic menu',
 'place ur point e cultur modul alreadi',
 'urgent tri contact last weekend draw show prize guarante call claim code valid hr',
 'hi frnd best way avoid missunderstd wit belov one',
 'great escap fanci bridg need lager see tomo',
 'ye complet form clark also utter wast',
 'sir need axi bank account bank address',
 'hmmm thk sure got time hop ard ya go free abt muz call u discuss liao',
 'time come later',
 'bloodi hell cant believ forgot surnam mr ill give u clue spanish begin',
 'well gonna finish bath good fine night',
 'let know got money carlo make call',
 'u still go mall',
 'turn friend stay whole show back til lt gt feel free go ahead smoke lt gt worth',
 'text doesnt repli let know log',
 'hi spoke maneesha v like know satisfi experi repli toll free ye',
 'lift hope offer money need especi end month approach hurt studi anyway gr weekend',
 'lol u trust',
 'ok gentleman treat digniti respect',
 'guy close',
 'go noth great bye',
 'hello handsom find job lazi work toward get back net mummi boytoy miss',
 'haha awesom minut',
 'pleas call custom servic repres freephon pm guarante cash prize',
 'got xma radio time get',
 'ju reach home go bath first si use net tell u finish k',
 'uniqu enough find th august www areyouuniqu co uk',
 'sorri join leagu peopl dont keep touch mean great deal friend time even great person cost great week',
 'hi final complet cours',
 'stop howev suggest stay someon abl give or everi stool',
 'hope settl new school year wishin gr day',
 'gud mrng dear hav nice day',
 'u got person stori',
 'hamster dead hey tmr meet pm orchard mrt',
 'hi kate even hope see tomorrow bit bloodi babyjontet txt back u xxx',
 'found enc lt gt',
 'sent lt gt buck',
 'hello darlin ive finish colleg txt u finish u love kate xxx',
 'account refil success inr lt decim gt keralacircl prepaid account balanc rs lt decim gt transact id kr lt gt',
 'goodmorn sleep ga',
 'u call alter ok',
 'say like dat dun buy ericsson oso cannot oredi lar',
 'enter cabin pa said happi b day boss felt special askd lunch lunch invit apart went',
 'aight yo dat straight dogg',
 'pleas give us connect today lt decim gt refund bill',
 'shoot big load get readi',
 'bruv hope great break reward semest',
 'home alway chat',
 'k k good studi well',
 'yup noe leh',
 'sound great home',
 'final match head toward draw predict',
 'tire slept well past night',
 'easi ah sen got select mean good',
 'take exam march',
 'yeah think use gt atm regist sure anyway help let know sure readi',
 'ok prob take ur time',
 'os call ubandu run without instal hard disk use os copi import file system give repair shop',
 'sorri call later',
 'u say leh cours noth happen lar say v romant ju bit lor thk e nite sceneri nice leh',
 'new mobil must go txt nokia collect today www tc biz optout gbp mtmsg',
 'would realli appreci call need someon talk',
 'u meet ur dream partner soon ur career flyng start find free txt horo follow ur star sign e g horo ari',
 'hey compani elama po mudyadhu',
 'life strict teacher bcoz teacher teach lesson amp conduct exam life first conduct exam amp teach lesson happi morn',
 'dear good morn',
 'get gandhipuram walk cross cut road right side lt gt street road turn first right',
 'dear go rubber place',
 'sorri batteri die yeah',
 'ye tv alway avail work place',
 'text meet someon sexi today u find date even flirt u join p repli name age eg sam msg recd thirtyeight penc',
 'print oh lt gt come upstair',
 'ill littl closer like bu stop street',
 'wil reach',
 'new theori argument win situat lose person dont argu ur friend kick amp say alway correct',
 'u secret admir look make contact u find r reveal think ur special call',
 'tomarrow final hear laptop case cant',
 'pleassssssseeeee tel v avent done sportsx',
 'okay shine meant sign sound better',
 'although told u dat baig face watch realli like e watch u gave co fr u thanx everyth dat u done today touch',
 'u rememb old commerci',
 'late said websit dont slipper',
 'ask call ok',
 'kalli wont bat nd inning',
 'didnt work oh ok goodnight fix readi time wake dearli miss good night sleep',
 'congratul ur award cd voucher gift guarante free entri wkli draw txt music tnc www ldew com win ppmx age',
 'ranjith cal drpd deeraj deepak min hold',
 'wen ur lovabl bcum angri wid u dnt take serious coz angri childish n true way show deep affect care n luv kettoda manda nice day da',
 '',
 'up day also ship compani take wk way usp take week get lag may bribe nipost get stuff',
 'back lemm know readi',
 'necessarili expect done get back though headin',
 'mmm yummi babe nice jolt suzi',
 'lover need',
 'tri contact repli offer video handset anytim network min unlimit text camcord repli call',
 'park next mini come today think',
 'yup',
 'anyway go shop co si done yet dun disturb u liao',
 'luton ring ur around h',
 'hey realli horni want chat see nake text hot text charg pm unsubscrib text stop',
 'dint come us',
 'wana plan trip sometm',
 'sure yet still tri get hold',
 'ur rington servic chang free credit go club mobil com choos content stop txt club stop p wk club po box mk wt',
 'evo download flash jealou',
 'rington club get uk singl chart mobil week choos top qualiti rington messag free charg',
 'come mu sort narcot situat',
 'night end anoth day morn come special way may smile like sunni ray leav worri blue blue bay',
 'hmv bonu special pound genuin hmv voucher answer easi question play send hmv info www percent real com',
 'usf guess might well take car',
 'object bf come',
 'thanx',
 'tell rob mack gf theater',
 'awesom see bit',
 'sent type food like',
 'done hand celebr full swing yet',
 'got call tool',
 'wen u miss someon person definit special u person special miss keep touch gdeve',
 'ok ask money far',
 'oki',
 'yeah think usual guy still pass last night get ahold anybodi let know throw',
 'k might come tonight class let earli',
 'ok',
 'hi babi im cruisin girl friend r u give call hour home that alright fone fone love jenni xxx',
 'life mean lot love life love peopl life world call friend call world ge',
 'dear shall mail tonit busi street shall updat tonit thing look ok varunnathu edukkukaye raksha ollu good one real sens',
 'hey told name gautham ah',
 'haf u found feel stupid da v cam work',
 'oop got bit',
 'much buzi',
 'accident delet messag resend pleas',
 'mobil custom may claim free camera phone upgrad pay go sim card loyalti call offer end thfeb c appli',
 'unless situat go gurl would appropri',
 'hurt teas make cri end life die plz keep one rose grave say stupid miss u nice day bslvyl',
 'cant pick phone right pl send messag',
 'need coffe run tomo believ time week alreadi',
 'awesom rememb last time got somebodi high first time diesel v',
 'shit realli shock scari cant imagin second def night u think somewher could crash night save taxi',
 'oh way food fridg want go meal tonight',
 'womdarful actor',
 'sm ac blind date u rodd aberdeen unit kingdom check http img sm ac w icmb cktz r blind date send hide',
 'yup remb think book',
 'jo ask u wana meet',
 'lol ye friendship hang thread caus u buy stuff',
 'themob check newest select content game tone gossip babe sport keep mobil fit funki text wap',
 'garag key bookshelf',
 'today accept day u accept brother sister lover dear best clo lvblefrnd jstfrnd cutefrnd lifpartnr belovd swtheart bstfrnd rpli mean enemi',
 'think ur smart win week weekli quiz text play cs winnersclub po box uz gbp week',
 'say give call friend got money definit buy end week',
 'hi way u day normal way real ur uniqu hope know u rest mylif hope u find wot lost',
 'made day great day',
 'k k advanc happi pongal',
 'hmmm guess go kb n power yoga haha dunno tahan power yoga anot thk got lo oso forgot liao',
 'realli dude friend afraid',
 'decemb mobil mth entitl updat latest colour camera mobil free call mobil updat co free',
 'coffe cake guess',
 'merri christma babe love ya kiss',
 'hey dont go watch x men lunch haha',
 'cud u tell ppl im gona b bit l co buse hav gon past co full im still waitin pete x',
 'would great guild could meet bristol road somewher get touch weekend plan take flight good week',
 'problem',
 'call messag miss call',
 'hi da today class',
 'say good sign well know track record read women',
 'cool text park',
 'read text sent meant joke read light',
 'k k apo k good movi',
 'mayb could get book tomo return immedi someth',
 'call germani penc per minut call fix line via access number prepay direct access',
 'chanc might evapor soon violat privaci steal phone number employ paperwork cool pleas contact report supervisor',
 'valentin day special win quiz take partner trip lifetim send go p msg rcvd custcar',
 'ta daaaaa home babe still',
 'cool come havent wine dine',
 'sleep surf',
 'sorri call later',
 'u call right call hand phone',
 'ok great thanx lot',
 'take post come must text happi read one wiv hello carolin end favourit bless',
 'u hide stranger',
 'interest like',
 'sister clear two round birla soft yesterday',
 'gudnit tc practic go',
 'di yiju ju saw ur mail case huim havent sent u num di num',
 'one small prestig problem',
 'fanci shag interest sextextuk com txt xxuk suzi txt cost per msg tnc websit x',
 'check realli miss see jeremiah great month',
 'nah help never iphon',
 'car hour half go apeshit',
 'today sorri day ever angri ever misbehav hurt plz plz slap urself bcoz ur fault basic good',
 'yo guy ever figur much need alcohol jay tri figur much safe spend weed',
 'lt gt ish minut minut ago wtf',
 'thank call forgot say happi onam sirji fine rememb met insur person meet qatar insha allah rakhesh ex tata aig join tissco tayseer',
 'congratul ur award cd voucher gift guarante free entri wkli draw txt music tnc www ldew com win ppmx age',
 'ur cash balanc current pound maxim ur cash send cash p msg cc hg suit land row w j hl',
 'actor work work even sleep late sinc unemploy moment alway sleep late unemploy everi day saturday',
 'hello got st andrew boy long way cold keep post',
 'ha ha cool cool chikku chikku db',
 'oh ok prob',
 'check audrey statu right',
 'busi tri finish new year look forward final meet',
 'good afternoon sunshin dawn day refresh happi aliv breath air smile think love alway',
 'well know z take care worri',
 'updat xma offer latest motorola sonyericsson nokia free bluetooth doubl min txt orang call mobileupd call optout f q',
 'discount code rp stop messag repli stop www regalportfolio co uk custom servic',
 'wat uniform get',
 'cool text readi',
 'hello boytoy geeee miss alreadi woke wish bed cuddl love',
 'spoil bed well',
 'go bath msg next lt gt min',
 'cant keep talk peopl sure pay agre price pl tell want realli buy much will pay',
 'thank rington order refer charg gbp per week unsubscrib anytim call custom servic',
 'say happen',
 'could seen recognis face',
 'well lot thing happen lindsay new year sigh bar ptbo blue heron someth go',
 'keep payasam rinu bring',
 'taught ranjith sir call sm like becau he verifi project prabu told today pa dont mistak',

In [150]:
y = pd.get_dummies(matter['label'])
y = y.iloc[:,0].values

###2. splitting data to train and test

In [151]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(corpus, y, test_size=0.2)

In [152]:
len(X_train), len(y_train)

(4457, 4457)

### 3. Bag of Words

In [153]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=2500, ngram_range=(1,2))

In [154]:
# Input Features
X_train = cv.fit_transform(X_train).toarray()
X_test = cv.transform(X_test).toarray()

In [155]:
np.set_printoptions(edgeitems=30, linewidth=10000,
                    formatter=dict(float=lambda x: "%.3g" % x))
X_train

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       ...,
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0]])

In [156]:
cv.vocabulary_

{'sir': np.int64(1892),
 'need': np.int64(1408),
 'bank': np.int64(146),
 'account': np.int64(12),
 'address': np.int64(21),
 'yo': np.int64(2491),
 'gonna': np.int64(825),
 'still': np.int64(1986),
 'stock': np.int64(1988),
 'tomorrow': np.int64(2147),
 'today': np.int64(2137),
 'tri': np.int64(2175),
 'get': np.int64(775),
 'tri get': np.int64(2178),
 'sure': np.int64(2034),
 'make': np.int64(1249),
 'smoke': np.int64(1916),
 'want': np.int64(2333),
 'told': np.int64(2145),
 'much': np.int64(1383),
 'tri make': np.int64(2179),
 'smoke much': np.int64(1917),
 'got': np.int64(847),
 'lesson': np.int64(1140),
 'sch': np.int64(1791),
 'doc': np.int64(540),
 'wait': np.int64(2319),
 'room': np.int64(1755),
 'depend': np.int64(514),
 'would': np.int64(2442),
 'like': np.int64(1153),
 'treat': np.int64(2174),
 'would like': np.int64(2443),
 'wat': np.int64(2345),
 'dear': np.int64(493),
 'sleep': np.int64(1902),
 'ah': np.int64(37),
 'help': np.int64(927),
 'pick': np.int64(1559),
 'wherev': np.int64(2390),
 'ur': np.int64(2236),
 'bird': np.int64(177),
 'meet': np.int64(1287),
 'urgent': np.int64(2272),
 'nd': np.int64(1403),
 'attempt': np.int64(117),
 'contact': np.int64(406),
 'prize': np.int64(1635),
 'yesterday': np.int64(2485),
 'await': np.int64(127),
 'collect': np.int64(373),
 'claim': np.int64(345),
 'call': np.int64(247),
 'nd attempt': np.int64(1404),
 'attempt contact': np.int64(118),
 'contact prize': np.int64(412),
 'await collect': np.int64(128),
 'claim call': np.int64(346),
 'well': np.int64(2379),
 'great': np.int64(861),
 'weekend': np.int64(2372),
 'great weekend': np.int64(863),
 'sweet': np.int64(2039),
 'heart': np.int64(918),
 'secret': np.int64(1801),
 'admir': np.int64(22),
 'look': np.int64(1186),
 'find': np.int64(686),
 'reveal': np.int64(1740),
 'think': np.int64(2098),
 'special': np.int64(1957),
 'ppm': np.int64(1619),
 'secret admir': np.int64(1802),
 'admir look': np.int64(23),
 'look make': np.int64(1188),
 'make contact': np.int64(1250),
 'contact find': np.int64(409),
 'find reveal': np.int64(689),
 'reveal think': np.int64(1741),
 'think ur': np.int64(2101),
 'ur special': np.int64(2263),
 'special call': np.int64(1958),
 'hey': np.int64(929),
 'dont': np.int64(549),
 'go': np.int64(800),
 'watch': np.int64(2348),
 'men': np.int64(1296),
 'lunch': np.int64(1239),
 'haha': np.int64(893),
 'hi': np.int64(933),
 'custom': np.int64(463),
 'loyalti': np.int64(1223),
 'offer': np.int64(1470),
 'new': np.int64(1418),
 'nokia': np.int64(1440),
 'mobil': np.int64(1332),
 'txtauction': np.int64(2207),
 'txt': np.int64(2197),
 'word': np.int64(2431),
 'start': np.int64(1976),
 'tc': np.int64(2054),
 'mtmsg': np.int64(1381),
 'custom loyalti': np.int64(464),
 'loyalti offer': np.int64(1225),
 'offer new': np.int64(1473),
 'new nokia': np.int64(1422),
 'nokia mobil': np.int64(1443),
 'mobil txtauction': np.int64(1341),
 'txtauction txt': np.int64(2208),
 'txt word': np.int64(2206),
 'word start': np.int64(2432),
 'start get': np.int64(1977),
 'yep': np.int64(2483),
 'success': np.int64(2016),
 'lt': np.int64(1229),
 'decim': np.int64(497),
 'gt': np.int64(867),
 'balanc': np.int64(144),
 'rs': np.int64(1762),
 'transact': np.int64(2171),
 'id': np.int64(996),
 'lt decim': np.int64(1230),
 'decim gt': np.int64(498),
 'lt gt': np.int64(1231),
 'sorri': np.int64(1942),
 'sent': np.int64(1841),
 'msg': np.int64(1376),
 'yup': np.int64(2498),
 'seriou': np.int64(1849),
 'studi': np.int64(2008),
 'world': np.int64(2435),
 'frnd': np.int64(748),
 'never': np.int64(1417),
 'charact': np.int64(323),
 'dey': np.int64(516),
 'best': np.int64(169),
 'understand': np.int64(2225),
 'differ': np.int64(522),
 'take': np.int64(2045),
 'min': np.int64(1307),
 'gt min': np.int64(873),
 'video': np.int64(2298),
 'handset': np.int64(900),
 'anytim': np.int64(82),
 'network': np.int64(1413),
 'half': np.int64(896),
 'price': np.int64(1630),
 'line': np.int64(1159),
 'rental': np.int64(1717),
 'camcord': np.int64(277),
 'repli': np.int64(1721),
 'deliveri': np.int64(508),
 'want new': np.int64(2339),
 'new video': np.int64(1423),
 'anytim network': np.int64(83),
 'network min': np.int64(1414),
 'min half': np.int64(1308),
 'half price': np.int64(898),
 'price line': np.int64(1631),
 'line rental': np.int64(1161),
 'camcord repli': np.int64(278),
 'repli call': np.int64(1722),
 'call deliveri': np.int64(253),
 'deliveri tomorrow': np.int64(509),
 'orang': np.int64(1504),
 'may': np.int64(1278),
 'free': np.int64(721),
 'camera': np.int64(281),
 'phone': np.int64(1551),
 'upgrad': np.int64(2234),
 'end': np.int64(598),
 'th': np.int64(2087),
 'appli': np.int64(89),
 'opt': np.int64(1502),
 'avail': np.int64(123),
 'claim free': np.int64(349),
 'free camera': np.int64(725),
 'camera phone': np.int64(284),
 'loyalti call': np.int64(1224),
 'offer end': np.int64(1471),
 'reach': np.int64(1679),
 'home': np.int64(956),
 'bath': np.int64(149),
 'liao': np.int64(1144),
 'reach home': np.int64(1681),
 'cant': np.int64(289),
 'tmr': np.int64(2133),
 'messag': np.int64(1300),
 'yahoo': np.int64(2469),
 'boy': np.int64(215),
 'bring': np.int64(222),
 'strong': np.int64(2006),
 'arm': np.int64(100),
 'met': np.int64(1303),
 'alex': np.int64(50),
 'school': np.int64(1793),
 'turn': np.int64(2193),
 'deal': np.int64(492),
 'st': np.int64(1970),
 'wk': np.int64(2419),
 'gr': np.int64(855),
 'tone': np.int64(2149),
 'str': np.int64(2002),
 'hit': np.int64(940),
 'poli': np.int64(1603),
 'wk free': np.int64(2420),
 'wk txt': np.int64(2421),
 'txt nokia': np.int64(2201),
 'nokia tone': np.int64(1445),
 'nope': np.int64(1450),
 'fri': np.int64(738),
 'quit': np.int64(1658),
 'earli': np.int64(577),
 'lor': np.int64(1190),
 'co': np.int64(363),
 'si': np.int64(1877),
 'paper': np.int64(1524),
 'da': np.int64(471),
 'morn': np.int64(1359),
 'go sch': np.int64(811),
 'come': np.int64(381),
 'right': np.int64(1744),
 'ahmad': np.int64(40),
 'ok': np.int64(1480),
 'alreadi': np.int64(54),
 'plan': np.int64(1578),
 'wil': np.int64(2399),
 'xma': np.int64(2462),
 'stori': np.int64(2001),
 'peac': np.int64(1537),
 'love': np.int64(1203),
 'miracl': np.int64(1317),
 'jesu': np.int64(1052),
 'hav': np.int64(912),
 'bless': np.int64(187),
 'month': np.int64(1355),
 'ahead': np.int64(39),
 'amp': np.int64(61),
 'wish': np.int64(2410),
 'merri': np.int64(1298),
 'number': np.int64(1461),
 'award': np.int64(130),
 'guarante': np.int64(878),
 'land': np.int64(1096),
 'valid': np.int64(2290),
 'hr': np.int64(980),
 'urgent mobil': np.int64(2275),
 'mobil number': np.int64(1340),
 'number award': np.int64(1462),
 'award prize': np.int64(133),
 'prize guarante': np.int64(1638),
 'guarante call': np.int64(879),
 'call land': np.int64(258),
 'land line': np.int64(1097),
 'line claim': np.int64(1160),
 'claim valid': np.int64(352),
 'valid hr': np.int64(2291),
 'case': np.int64(303),
 'guess': np.int64(886),
 'see': np.int64(1804),
 'campu': np.int64(285),
 'cash': np.int64(304),
 'current': np.int64(459),
 'pound': np.int64(1613),
 'maxim': np.int64(1276),
 'send': np.int64(1820),
 'cc': np.int64(314),
 'po': np.int64(1595),
 'box': np.int64(211),
 'tcr': np.int64(2056),
 'ur cash': np.int64(2239),
 'cash balanc': np.int64(306),
 'balanc current': np.int64(145),
 'current pound': np.int64(460),
 'pound maxim': np.int64(1614),
 'maxim ur': np.int64(1277),
 'cash send': np.int64(310),
 'send go': np.int64(1826),
 'go msg': np.int64(809),
 'msg cc': np.int64(1377),
 'po box': np.int64(1596),
 'almost': np.int64(51),
 'forgot': np.int64(714),
 'happi': np.int64(904),
 'day': np.int64(483),
 'babe': np.int64(137),
 'ya': np.int64(2468),
 'happi day': np.int64(906),
 'babe love': np.int64(138),
 'love ya': np.int64(1218),
 'nah': np.int64(1394),
 'pleas': np.int64(1584),
 'landlin': np.int64(1099),
 'holiday': np.int64(951),
 'cs': np.int64(451),
 'sae': np.int64(1768),
 'xy': np.int64(2467),
 'urgent pleas': np.int64(2276),
 'pleas call': np.int64(1585),
 'call landlin': np.int64(259),
 'cash holiday': np.int64(308),
 'holiday await': np.int64(952),
 'realli': np.int64(1689),
 'kiss': np.int64(1086),
 'miss': np.int64(1319),
 'babi': np.int64(139),
 'realli need': np.int64(1691),
 'good': np.int64(829),
 'plz': np.int64(1590),
 'good morn': np.int64(840),
 'plz call': np.int64(1591),
 'call sir': np.int64(268),
 'ye': np.int64(2475),
 'snow': np.int64(1920),
 'usual': np.int64(2286),
 'sinc': np.int64(1887),
 'even': np.int64(624),
 'born': np.int64(205),
 'think gonna': np.int64(2100),
 'serious': np.int64(1850),
 'spell': np.int64(1962),
 'name': np.int64(1396),
 'easi': np.int64(580),
 'pay': np.int64(1532),
 'back': np.int64(140),
 'yr': np.int64(2495),
 'say': np.int64(1786),
 'earlier': np.int64(578),
 'pay back': np.int64(1533),
 'gt yr': np.int64(877),
 'oh': np.int64(1477),
 'goin': np.int64(822),
 'yogasana': np.int64(2494),
 'den': np.int64(511),
 'rush': np.int64(1766),
 'oki': np.int64(1488),
 'readi': np.int64(1685),
 'forget': np.int64(713),
 'own': np.int64(1516),
 'privat': np.int64(1633),
 'alway': np.int64(58),
 'good boy': np.int64(831),
 'email': np.int64(594),
 'low': np.int64(1222),
 'cost': np.int64(430),
 'listen': np.int64(1166),
 'joy': np.int64(1060),
 'father': np.int64(664),
 'john': np.int64(1055),
 'an': np.int64(65),
 'ti': np.int64(2113),
 'question': np.int64(1656),
 'answer': np.int64(74),
 'joy father': np.int64(1061),
 'wine': np.int64(2407),
 'mean': np.int64(1282),
 'februari': np.int64(669),
 'april': np.int64(92),
 'place': np.int64(1577),
 'stay': np.int64(1982),
 'season': np.int64(1799),
 'sister': np.int64(1893),
 'move': np.int64(1367),
 'away': np.int64(135),
 'omg': np.int64(1490),
 'dream': np.int64(561),
 'kid': np.int64(1081),
 'piss': np.int64(1567),
 'mark': np.int64(1262),
 'chang': np.int64(322),
 'caus': np.int64(313),
 'face': np.int64(649),
 'neva': np.int64(1416),
 'worri': np.int64(2436),
 'bout': np.int64(210),
 'truth': np.int64(2185),
 'coz': np.int64(440),
 'lead': np.int64(1127),
 'least': np.int64(1129),
 'person': np.int64(1546),
 'ur heart': np.int64(2246),
 'bonu': np.int64(199),
 'caller': np.int64(272),
 'award bonu': np.int64(131),
 'bonu caller': np.int64(200),
 'caller prize': np.int64(274),
 'prize call': np.int64(1636),
 'lol': np.int64(1180),
 'eh': np.int64(590),
 'troubl': np.int64(2181),
 'saw': np.int64(1785),
 'sort': np.int64(1946),
 'bloke': np.int64(188),
 'gona': np.int64(823),
 'girl': np.int64(790),
 'mr': np.int64(1371),
 'mum': np.int64(1384),
 'later': np.int64(1112),
 'pl': np.int64(1570),
 'call later': np.int64(260),
 'next': np.int64(1426),
 'sun': np.int64(2023),
 'basic': np.int64(148),
 'yoga': np.int64(2493),
 'cours': np.int64(438),
 'bugi': np.int64(234),
 'pilat': np.int64(1565),
 'intro': np.int64(1029),
 'sat': np.int64(1778),
 'tell': np.int64(2065),
 'time': np.int64(2121),
 'wif': np.int64(2397),
 'aft': np.int64(33),
 'dog': np.int64(543),
 'rain': np.int64(1664),
 'soon': np.int64(1941),
 'look like': np.int64(1187),
 'sad': np.int64(1767),
 'one': np.int64(1492),
 'thing': np.int64(2097),
 'past': np.int64(1531),
 'busi': np.int64(238),
 'stop': np.int64(1992),
 'hella': np.int64(925),
 'weed': np.int64(2366),
 'buy': np.int64(239),
 'ok lor': np.int64(1484),
 'thought': np.int64(2107),
 'that': np.int64(2094),
 'kind': np.int64(1083),
 'love much': np.int64(1212),
 'king': np.int64(1085),
 'club': np.int64(361),
 'info': np.int64(1020),
 'uk': np.int64(2217),
 'must': np.int64(1391),
 'credit': np.int64(447),
 'redeem': np.int64(1700),
 'www': np.int64(2453),
 'enjoy': np.int64(605),
 'co uk': np.int64(364),
 'keep': np.int64(1071),
 'ten': np.int64(2070),
 'two': np.int64(2195),
 'egg': np.int64(589),
 'tonight': np.int64(2155),
 'interest': np.int64(1027),
 'later tonight': np.int64(1114),
 'win': np.int64(2401),
 'weekli': np.int64(2374),
 'sport': np.int64(1968),
 'play': np.int64(1579),
 'servic': np.int64(1853),
 'play send': np.int64(1581),
 'send stop': np.int64(1835),
 'stop end': np.int64(1993),
 'actual': np.int64(18),
 'might': np.int64(1306),
 'text': np.int64(2077),
 'rock': np.int64(1751),
 'wen': np.int64(2382),
 'wake': np.int64(2323),
 'call back': np.int64(249),
 'send text': np.int64(1837),
 'aunti': np.int64(122),
 'lucki': np.int64(1236),
 'pple': np.int64(1618),
 'finish': np.int64(693),
 'shall': np.int64(1862),
 'come get': np.int64(383),
 'mail': np.int64(1247),
 'tick': np.int64(2114),
 'tick tick': np.int64(2115),
 'music': np.int64(1388),
 'gift': np.int64(787),
 'voucher': np.int64(2315),
 'everi': np.int64(626),
 'week': np.int64(2367),
 'draw': np.int64(558),
 'com': np.int64(379),
 'age': np.int64(35),
 'gift voucher': np.int64(789),
 'everi week': np.int64(627),
 'week start': np.int64(2370),
 'cheer': np.int64(332),
 'yeah': np.int64(2479),
 'came': np.int64(279),
 'bag': np.int64(142),
 'late': np.int64(1111),
 'logo': np.int64(1178),
 'lover': np.int64(1219),
 'join': np.int64(1056),
 'eg': np.int64(588),
 'eve': np.int64(623),
 'pobox': np.int64(1597),
 'wq': np.int64(2445),
 'ad': np.int64(19),
 'ur lover': np.int64(2252),
 'pobox wq': np.int64(1600),
 'alrit': np.int64(56),
 'know': np.int64(1088),
 'wrong': np.int64(2450),
 'care': np.int64(296),
 'hun': np.int64(986),
 'take care': np.int64(2046),
 'carlo': np.int64(301),
 'lost': np.int64(1195),
 'thank': np.int64(2091),
 'vote': np.int64(2314),
 'sing': np.int64(1888),
 'along': np.int64(53),
 'link': np.int64(1163),
 'mobil free': np.int64(1338),
 'drug': np.int64(567),
 'exam': np.int64(635),
 'ho': np.int64(948),
 'first': np.int64(695),
 'use': np.int64(2282),
 'type': np.int64(2214),
 'first time': np.int64(696),
 'time use': np.int64(2127),
 'invit': np.int64(1030),
 'friend': np.int64(740),
 'sm': np.int64(1908),
 'ac': np.int64(8),
 'invit friend': np.int64(1031),
 'friend repli': np.int64(742),
 'repli ye': np.int64(1727),
 'ye see': np.int64(2478),
 'see www': np.int64(1809),
 'www sm': np.int64(2456),
 'sm ac': np.int64(1909),
 'stop send': np.int64(1996),
 'stop frnd': np.int64(1994),
 'children': np.int64(337),
 'adult': np.int64(25),
 'doctor': np.int64(541),
 'india': np.int64(1016),
 'drink': np.int64(564),
 'cancer': np.int64(287),
 'cook': np.int64(422),
 'rather': np.int64(1674),
 'nice': np.int64(1429),
 'la': np.int64(1092),
 'miss call': np.int64(1322),
 'comput': np.int64(395),
 'aiyah': np.int64(46),
 'cal': np.int64(246),
 'hold': np.int64(950),
 'advanc': np.int64(26),
 'think go': np.int64(2099),
 'wat time': np.int64(2346),
 'time go': np.int64(2124),
 'chat': np.int64(328),
 'let': np.int64(1141),
 'rcvd': np.int64(1677),
 'hg': np.int64(931),
 'suit': np.int64(2019),
 'row': np.int64(1759),
 'hl': np.int64(942),
 'ldn': np.int64(1124),
 'year': np.int64(2482),
 'send chat': np.int64(1822),
 'msg rcvd': np.int64(1379),
 'hg suit': np.int64(932),
 'suit land': np.int64(2020),
 'land row': np.int64(1098),
 'row hl': np.int64(1760),
 'hl ldn': np.int64(944),
 'argument': np.int64(99),
 'situat': np.int64(1896),
 'lose': np.int64(1193),
 'argu': np.int64(98),
 'kick': np.int64(1080),
 'correct': np.int64(429),
 'person dont': np.int64(1547),
 'ur friend': np.int64(2244),
 'solv': np.int64(1925),
 'man': np.int64(1254),
 'found': np.int64(718),
 'murder': np.int64(1386),
 'afternoon': np.int64(34),
 'wife': np.int64(2398),
 'polic': np.int64(1604),
 'everyon': np.int64(630),
 'took': np.int64(2158),
 'garden': np.int64(763),
 'hous': np.int64(974),
 'maid': np.int64(1246),
 'went': np.int64(2384),
 'post': np.int64(1611),
 'offic': np.int64(1474),
 'marriag': np.int64(1265),
 'arrest': np.int64(105),
 'immedi': np.int64(1008),
 'reason': np.int64(1692),
 'brilliant': np.int64(221),
 'murder lt': np.int64(1387),
 'gt lt': np.int64(872),
 'cook cook': np.int64(423),
 'cook garden': np.int64(424),
 'hous maid': np.int64(975),
 'post offic': np.int64(1612),
 'someth': np.int64(1931),
 'usf': np.int64(2285),
 'drive': np.int64(565),
 'street': np.int64(2004),
 'park': np.int64(1526),
 'lot': np.int64(1196),
 'congratul': np.int64(402),
 'either': np.int64(591),
 'suppli': np.int64(2031),
 'cd': np.int64(315),
 'record': np.int64(1698),
 'ts': np.int64(2187),
 'net': np.int64(1412),
 'pm': np.int64(1592),
 'congratul ur': np.int64(403),
 'ur award': np.int64(2237),
 'gift guarante': np.int64(788),
 'ts cs': np.int64(2188),
 'cs www': np.int64(453),
 'teach': np.int64(2058),
 'abi': np.int64(3),
 'say hi': np.int64(1787),
 'polyphon': np.int64(1605),
 'mob': np.int64(1330),
 'txtin': np.int64(2209),
 'tone ur': np.int64(2154),
 'ur mob': np.int64(2255),
 'mob everi': np.int64(1331),
 'week txt': np.int64(2371),
 'st tone': np.int64(1971),
 'tone free': np.int64(2151),
 'free get': np.int64(728),
 'get txtin': np.int64(781),
 'txtin tell': np.int64(2210),
 'tell ur': np.int64(2068),
 'friend tone': np.int64(743),
 'tone repli': np.int64(2152),
 'repli hl': np.int64(1725),
 'hl info': np.int64(943),
 'hour': np.int64(973),
 'half hour': np.int64(897),
 'fetch': np.int64(676),
 'yun': np.int64(2496),
 'said': np.int64(1772),
 'fool': np.int64(709),
 'ask': np.int64(109),
 'us': np.int64(2281),
 'gm': np.int64(796),
 'gn': np.int64(798),
 'ge': np.int64(771),
 'gm gn': np.int64(797),
 'gn ge': np.int64(799),
 'wan': np.int64(2326),
 'bishan': np.int64(180),
 'wan meet': np.int64(2329),
 'guy': np.int64(888),
 'gone': np.int64(824),
 'last': np.int64(1107),
 'ard': np.int64(95),
 'rest': np.int64(1737),
 'way': np.int64(2354),
 'give': np.int64(792),
 'ticket': np.int64(2116),
 'speak': np.int64(1954),
 'noth': np.int64(1455),
 'meant': np.int64(1283),
 'money': np.int64(1353),
 'enter': np.int64(608),
 'remov': np.int64(1715),
 'flat': np.int64(700),
 'rate': np.int64(1669),
 'someon': np.int64(1927),
 'transfer': np.int64(2172),
 'dollar': np.int64(547),
 'charg': np.int64(324),
 'also': np.int64(57),
 'trust': np.int64(2184),
 'ja': np.int64(1043),
 'detail': np.int64(515),
 'gt dollar': np.int64(869),
 'send account': np.int64(1821),
 'what': np.int64(2386),
 'colour': np.int64(377),
 'minut': np.int64(1315),
 'free text': np.int64(734),
 'text free': np.int64(2080),
 'free camcord': np.int64(724),
 'date': np.int64(481),
 'someon know': np.int64(1929),
 'date servic': np.int64(482),
 'remind': np.int64(1714),
 'wonder': np.int64(2429),
 'town': np.int64(2168),
 'lei': np.int64(1136),
 'dare': np.int64(477),
 'stupid': np.int64(2010),
 'wont': np.int64(2430),
 'anyth': np.int64(79),
 'hear': np.int64(916),
 'talk': np.int64(2050),
 'tell anyth': np.int64(2066),
 'lookin': np.int64(1189),
 'latest': np.int64(1115),
 'news': np.int64(1425),
 'station': np.int64(1981),
 'bad': np.int64(141),
 'princess': np.int64(1632),
 'check': np.int64(331),
 'list': np.int64(1165),
 'tel': np.int64(2064),
 'life': np.int64(1148),
 'send ur': np.int64(1838),
 'ur life': np.int64(2249),
 'car': np.int64(294),
 'shop': np.int64(1868),
 'flirt': np.int64(704),
 'boss': np.int64(206),
 'fire': np.int64(694),
 'phone number': np.int64(1555),
 'test': np.int64(2076),
 'appreci': np.int64(91),
 'call tomorrow': np.int64(270),
 'work': np.int64(2433),
 'wanna': np.int64(2332),
 'drop': np.int64(566),
 'bore': np.int64(204),
 'etc': np.int64(620),
 'ring': np.int64(1746),
 'hope': np.int64(961),
 'xx': np.int64(2463),
 'sk': np.int64(1897),
 'box sk': np.int64(214),
 'show': np.int64(1871),
 'somewher': np.int64(1934),
 'moon': np.int64(1357),
 'light': np.int64(1150),
 'true': np.int64(2182),
 'light someon': np.int64(1151),
 'sweet dream': np.int64(2040),
 'class': np.int64(353),
 'cant pick': np.int64(291),
 'pick phone': np.int64(1560),
 'phone right': np.int64(1556),
 'right pl': np.int64(1745),
 'pl send': np.int64(1576),
 'send messag': np.int64(1831),
 'sound': np.int64(1947),
 'al': np.int64(48),
 'sound like': np.int64(1948),
 'jay': np.int64(1048),
 'pain': np.int64(1523),
 'catch': np.int64(312),
 'glad': np.int64(795),
 'follow': np.int64(706),
 'heard': np.int64(917),
 'fantast': np.int64(659),
 'amaz': np.int64(59),
 'quot': np.int64(1661),

In [157]:
from sklearn.naive_bayes import MultinomialNB
spam_detection_model = MultinomialNB().fit(X_train, y_train)

In [158]:
y_pred = spam_detection_model.predict(X_test)

In [159]:
y_pred

array([False,  True,  True,  True,  True, False,  True,  True, False,  True,  True,  True,  True, False,  True,  True, False,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True, False, ...,  True,  True,  True,  True,  True,  True,  True,  True,  True, False,  True,  True,  True,  True,  True,  True, False,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True, False, False,  True])

In [160]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, y_pred)
accuracy

0.9766816143497757

### TF-IDF

In [161]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(corpus, y, test_size=0.2)

In [162]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer(max_features=2500, ngram_range=(1,2))
X_train = tfidf.fit_transform(X_train).toarray()
X_test = tfidf.transform(X_test).toarray()

In [163]:
X_train

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.301, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.257, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0.233, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0.165, 0, 0, 0.244, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.346, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       ...,
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.812, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.408, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.211, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.335, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0.439, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [164]:
tfidf.vocabulary_

{'nd': np.int64(1400),
 'time': np.int64(2122),
 'tri': np.int64(2175),
 'contact': np.int64(402),
 'pound': np.int64(1627),
 'prize': np.int64(1653),
 'claim': np.int64(333),
 'easi': np.int64(574),
 'call': np.int64(236),
 'per': np.int64(1552),
 'min': np.int64(1297),
 'bt': np.int64(213),
 'nation': np.int64(1396),
 'rate': np.int64(1684),
 'nd time': np.int64(1402),
 'time tri': np.int64(2129),
 'tri contact': np.int64(2176),
 'contact pound': np.int64(408),
 'pound prize': np.int64(1629),
 'prize claim': np.int64(1655),
 'claim easi': np.int64(336),
 'easi call': np.int64(575),
 'call per': np.int64(253),
 'per min': np.int64(1554),
 'bt nation': np.int64(215),
 'nation rate': np.int64(1397),
 'got': np.int64(833),
 'ur': np.int64(2234),
 'mail': np.int64(1239),
 'thank': np.int64(2091),
 'look': np.int64(1186),
 'forward': np.int64(709),
 'lot': np.int64(1198),
 'support': np.int64(2033),
 'less': np.int64(1137),
 'rememb': np.int64(1721),
 'one': np.int64(1495),
 'tomorrow': np.int64(2153),
 'late': np.int64(1106),
 'shall': np.int64(1856),
 'come': np.int64(368),
 'till': np.int64(2121),
 'goodnight': np.int64(831),
 'dear': np.int64(490),
 'ur mail': np.int64(2244),
 'look forward': np.int64(1187),
 'like': np.int64(1151),
 'da': np.int64(466),
 'way': np.int64(2344),
 'mm': np.int64(1322),
 'dont': np.int64(542),
 'eat': np.int64(577),
 'anyth': np.int64(70),
 'heavi': np.int64(915),
 'ok': np.int64(1475),
 'cold': np.int64(354),
 'sad': np.int64(1773),
 'sorri': np.int64(1941),
 'later': np.int64(1107),
 'sorri call': np.int64(1942),
 'call later': np.int64(248),
 'go': np.int64(793),
 'wherev': np.int64(2384),
 'tell': np.int64(2070),
 'call tell': np.int64(257),
 'come tomorrow': np.int64(375),
 'match': np.int64(1260),
 'start': np.int64(1975),
 'india': np.int64(1012),
 'lt': np.int64(1219),
 'gt': np.int64(855),
 'lt gt': np.int64(1221),
 'problem': np.int64(1661),
 'frm': np.int64(738),
 'wat': np.int64(2335),
 'matter': np.int64(1265),
 'ill': np.int64(999),
 'pick': np.int64(1572),
 'pm': np.int64(1605),
 'give': np.int64(785),
 'enough': np.int64(599),
 'get': np.int64(767),
 'park': np.int64(1536),
 'time get': np.int64(2125),
 'anybodi': np.int64(67),
 'number': np.int64(1458),
 'still': np.int64(1983),
 'thought': np.int64(2109),
 'ask': np.int64(97),
 'alex': np.int64(48),
 'know': np.int64(1082),
 'oh': np.int64(1473),
 'dont know': np.int64(543),
 'urgent': np.int64(2256),
 'last': np.int64(1101),
 'weekend': np.int64(2363),
 'draw': np.int64(552),
 'show': np.int64(1870),
 'guarante': np.int64(866),
 'code': np.int64(350),
 'valid': np.int64(2275),
 'hr': np.int64(977),
 'urgent tri': np.int64(2262),
 'contact last': np.int64(407),
 'last weekend': np.int64(1105),
 'weekend draw': np.int64(2364),
 'draw show': np.int64(553),
 'show prize': np.int64(1871),
 'prize guarante': np.int64(1656),
 'guarante call': np.int64(868),
 'call claim': np.int64(239),
 'claim code': np.int64(335),
 'code valid': np.int64(352),
 'valid hr': np.int64(2276),
 'let': np.int64(1140),
 'use': np.int64(2266),
 'next': np.int64(1425),
 'week': np.int64(2357),
 'princess': np.int64(1648),
 'next week': np.int64(1426),
 'free': np.int64(714),
 'video': np.int64(2283),
 'camera': np.int64(270),
 'phone': np.int64(1565),
 'half': np.int64(887),
 'price': np.int64(1644),
 'line': np.int64(1157),
 'rental': np.int64(1725),
 'mth': np.int64(1376),
 'txt': np.int64(2198),
 'mobileupd': np.int64(1338),
 'optout': np.int64(1512),
 'video camera': np.int64(2284),
 'camera phone': np.int64(273),
 'half price': np.int64(889),
 'price line': np.int64(1645),
 'line rental': np.int64(1159),
 'min txt': np.int64(1303),
 'txt call': np.int64(2199),
 'call mobileupd': np.int64(251),
 'mobileupd call': np.int64(1339),
 'call optout': np.int64(252),
 'done': np.int64(541),
 'oso': np.int64(1521),
 'aft': np.int64(29),
 'lect': np.int64(1130),
 'rite': np.int64(1757),
 'say': np.int64(1795),
 'fantast': np.int64(655),
 'chanc': np.int64(308),
 'need': np.int64(1405),
 'life': np.int64(1147),
 'lift': np.int64(1148),
 'lose': np.int64(1196),
 'live': np.int64(1166),
 'think': np.int64(2099),
 'would': np.int64(2432),
 'first': np.int64(687),
 'person': np.int64(1562),
 'die': np.int64(519),
 'decid': np.int64(495),
 'co': np.int64(347),
 'si': np.int64(1875),
 'home': np.int64(954),
 'liao': np.int64(1144),
 'go home': np.int64(800),
 'hey': np.int64(923),
 'glad': np.int64(788),
 'better': np.int64(159),
 'hear': np.int64(911),
 'treat': np.int64(2174),
 'urself': np.int64(2264),
 'good': np.int64(817),
 'new': np.int64(1416),
 'year': np.int64(2479),
 'wk': np.int64(2412),
 'new year': np.int64(1423),
 'invit': np.int64(1023),
 'friend': np.int64(732),
 'repli': np.int64(1727),
 'ye': np.int64(2471),
 'see': np.int64(1817),
 'www': np.int64(2446),
 'sm': np.int64(1909),
 'ac': np.int64(5),
 'stop': np.int64(1991),
 'send': np.int64(1830),
 'frnd': np.int64(739),
 'invit friend': np.int64(1025),
 'friend repli': np.int64(735),
 'repli ye': np.int64(1733),
 'ye see': np.int64(2474),
 'see www': np.int64(1820),
 'www sm': np.int64(2450),
 'sm ac': np.int64(1910),
 'stop send': np.int64(1997),
 'send stop': np.int64(1838),
 'stop frnd': np.int64(1995),
 'room': np.int64(1762),
 'someth': np.int64(1930),
 'plan': np.int64(1590),
 'famili': np.int64(652),
 'set': np.int64(1851),
 'stone': np.int64(1990),
 'guess': np.int64(875),
 'freak': np.int64(713),
 'spend': np.int64(1960),
 'qualiti': np.int64(1670),
 'togeth': np.int64(2150),
 'hang': np.int64(897),
 'brother': np.int64(211),
 'lor': np.int64(1191),
 'readi': np.int64(1694),
 'yet': np.int64(2485),
 'home first': np.int64(955),
 'ok lor': np.int64(1478),
 'uncl': np.int64(2220),
 'wish': np.int64(2402),
 'guy': np.int64(877),
 'great': np.int64(847),
 'semest': np.int64(1828),
 'search': np.int64(1808),
 'tat': np.int64(2058),
 'love': np.int64(1204),
 'receiv': np.int64(1704),
 'style': np.int64(2015),
 'enjoy': np.int64(598),
 'make': np.int64(1241),
 'night': np.int64(1431),
 'gt time': np.int64(864),
 'time per': np.int64(2128),
 'per night': np.int64(1557),
 'gal': np.int64(750),
 'wanna': np.int64(2323),
 'meet': np.int64(1280),
 'dinner': np.int64(525),
 'meet dinner': np.int64(1282),
 'abl': np.int64(3),
 'schedul': np.int64(1801),
 'town': np.int64(2169),
 'yup': np.int64(2496),
 'issu': np.int64(1034),
 'privat': np.int64(1651),
 'account': np.int64(9),
 'statement': np.int64(1976),
 'bonu': np.int64(185),
 'point': np.int64(1615),
 'identifi': np.int64(994),
 'expir': np.int64(639),
 'privat account': np.int64(1652),
 'account statement': np.int64(10),
 'statement show': np.int64(1977),
 'claim call': np.int64(334),
 'call identifi': np.int64(244),
 'identifi code': np.int64(995),
 'code expir': np.int64(351),
 'wors': np.int64(2428),
 'dude': np.int64(563),
 'alway': np.int64(57),
 'want': np.int64(2324),
 'parti': np.int64(1539),
 'file': np.int64(674),
 'three': np.int64(2110),
 'drug': np.int64(562),
 'fun': np.int64(745),
 'fact': np.int64(648),
 'armand': np.int64(89),
 'build': np.int64(222),
 'shit': np.int64(1863),
 'consid': np.int64(401),
 'much': np.int64(1381),
 'smoke': np.int64(1914),
 'fuck': np.int64(741),
 'hit': np.int64(935),
 'anyway': np.int64(74),
 'sure': np.int64(2036),
 'tho': np.int64(2107),
 'librari': np.int64(1145),
 'class': np.int64(339),
 'eve': np.int64(613),
 'sure get': np.int64(2037),
 'bore': np.int64(190),
 'nope': np.int64(1448),
 'sinc': np.int64(1887),
 'travel': np.int64(2173),
 'long': np.int64(1183),
 'til': np.int64(2120),
 'joy': np.int64(1053),
 'father': np.int64(660),
 'john': np.int64(1047),
 'name': np.int64(1395),
 'joy father': np.int64(1054),
 'father john': np.int64(661),
 'john john': np.int64(1048),
 'goodmorn': np.int64(829),
 'leav': np.int64(1128),
 'today': np.int64(2141),
 'take': np.int64(2051),
 'italian': np.int64(1035),
 'food': np.int64(701),
 'pretti': np.int64(1643),
 'dress': np.int64(556),
 'msg': np.int64(1370),
 'ju': np.int64(1056),
 'said': np.int64(1779),
 'gift': np.int64(779),
 'feel': np.int64(665),
 'bad': np.int64(131),
 'even': np.int64(614),
 'make feel': np.int64(1243),
 'feel better': np.int64(666),
 'expect': np.int64(636),
 'back': np.int64(129),
 'though': np.int64(2108),
 'get back': np.int64(768),
 'hi': np.int64(927),
 'offic': np.int64(1470),
 'winner': np.int64(2400),
 'caller': np.int64(262),
 'final': np.int64(678),
 'attempt': np.int64(106),
 'caller prize': np.int64(263),
 'final attempt': np.int64(679),
 'attempt contact': np.int64(107),
 'still want': np.int64(1986),
 'want come': np.int64(2325),
 'babe': np.int64(126),
 'everyth': np.int64(625),
 'alrit': np.int64(55),
 'idiot': np.int64(996),
 'bak': np.int64(134),
 'love babe': np.int64(1206),
 'xma': np.int64(2458),
 'stori': np.int64(2004),
 'peac': np.int64(1550),
 'miracl': np.int64(1313),
 'jesu': np.int64(1044),
 'hav': np.int64(908),
 'bless': np.int64(178),
 'month': np.int64(1348),
 'ahead': np.int64(37),
 'amp': np.int64(60),
 'merri': np.int64(1289),
 'tire': np.int64(2132),
 'wife': np.int64(2391),
 'knew': np.int64(1081),
 'murder': np.int64(1385),
 'exactli': np.int64(629),
 'vodafon': np.int64(2295),
 'end': np.int64(590),
 'digit': np.int64(522),
 'select': np.int64(1824),
 'award': np.int64(118),
 'pleas': np.int64(1596),
 'today vodafon': np.int64(2149),
 'number end': np.int64(1460),
 'select receiv': np.int64(1825),
 'receiv award': np.int64(1705),
 'match pleas': np.int64(1261),
 'pleas call': np.int64(1597),
 'whole': np.int64(2387),
 'car': np.int64(282),
 'appreci': np.int64(81),
 'two': np.int64(2197),
 'dad': np.int64(469),
 'read': np.int64(1692),
 'argument': np.int64(87),
 'apart': np.int64(75),
 'thing': np.int64(2098),
 'mother': np.int64(1358),
 'pass': np.int64(1541),
 'away': np.int64(124),
 'pray': np.int64(1637),
 'last night': np.int64(1102),
 'amaz': np.int64(58),
 'quot': np.int64(1675),
 'sometim': np.int64(1933),
 'difficult': np.int64(521),
 'what': np.int64(2380),
 'wrong': np.int64(2441),
 'lie': np.int64(1146),
 'bring': np.int64(208),
 'smile': np.int64(1913),
 'truth': np.int64(2185),
 'tear': np.int64(2066),
 'immedi': np.int64(1002),
 'messag': np.int64(1290),
 'wait': np.int64(2308),
 'call immedi': np.int64(245),
 'immedi urgent': np.int64(1003),
 'urgent messag': np.int64(2258),
 'messag wait': np.int64(1291),
 'summer': np.int64(2026),
 'fanci': np.int64(653),
 'chat': np.int64(318),
 'flirt': np.int64(696),
 'sexi': np.int64(1854),
 'singl': np.int64(1889),
 'yr': np.int64(2494),
 'area': np.int64(86),
 'join': np.int64(1049),
 'help': np.int64(921),
 'free join': np.int64(720),
 'optout txt': np.int64(1513),
 'txt stop': np.int64(2207),
 'usual': np.int64(2270),
 'film': np.int64(677),
 'differ': np.int64(520),
 'cours': np.int64(432),
 'teas': np.int64(2067),
 'simpli': np.int64(1886),
 'must': np.int64(1390),
 'grin': np.int64(852),
 'keep': np.int64(1065),
 'post': np.int64(1625),
 'kiss': np.int64(1079),
 'lol': np.int64(1179),
 'money': np.int64(1347),
 'offer': np.int64(1468),
 'wat time': np.int64(2337),
 'also': np.int64(56),
 'lunch': np.int64(1228),
 'menu': np.int64(1288),
 'come ur': np.int64(376),
 'ur home': np.int64(2241),
 'buzz': np.int64(226),
 'ass': np.int64(103),
 'requir': np.int64(1737),
 'tonight': np.int64(2159),
 'whenev': np.int64(2383),
 'cool': np.int64(420),
 'text': np.int64(2080),
 'around': np.int64(90),
 'cool text': np.int64(421),
 'break': np.int64(205),
 'stuff': np.int64(2013),
 'fr': np.int64(712),
 'come get': np.int64(370),
 'wear': np.int64(2352),
 'second': np.int64(1812),
 'weak': np.int64(2351),
 'day': np.int64(479),
 'chang': np.int64(311),
 'noth': np.int64(1452),
 'might': np.int64(1295),
 'sch': np.int64(1800),
 'yar': np.int64(2468),
 'go sch': np.int64(804),
 'wil': np.int64(2393),
 'im': np.int64(1000),
 'bout': np.int64(197),
 'ish': np.int64(1032),
 'compani': np.int64(381),
 'could': np.int64(429),
 'head': np.int64(910),
 'earlier': np.int64(572),
 'goin': np.int64(813),
 'look like': np.int64(1188),
 'auction': np.int64(109),
 'brand': np.int64(204),
 'nokia': np.int64(1437),
 'part': np.int64(1537),
 'hg': np.int64(925),
 'suit': np.int64(2023),
 'land': np.int64(1092),
 'row': np.int64(1766),
 'hl': np.int64(937),
 'new nokia': np.int64(1420),
 'take part': np.int64(2053),
 'txt nokia': np.int64(2202),
 'nokia hg': np.int64(1440),
 'hg suit': np.int64(926),
 'suit land': np.int64(2024),
 'land row': np.int64(1094),
 'row hl': np.int64(1767),
 'gonna': np.int64(815),
 'stay': np.int64(1979),
 'haha': np.int64(883),
 'okay': np.int64(1487),
 'leh': np.int64(1133),
 'mayb': np.int64(1273),
 'find': np.int64(680),
 'card': np.int64(283),
 'say hi': np.int64(1797),
 'march': np.int64(1255),
 'wait till': np.int64(2313),
 'ok ok': np.int64(1479),
 'ok what': np.int64(1486),
 'today plan': np.int64(2146),
 'paper': np.int64(1531),
 'morn': np.int64(1353),
 'ur paper': np.int64(2248),
 'th': np.int64(2089),
 'still around': np.int64(1984),
 'complimentari': np.int64(384),
 'trip': np.int64(2180),
 'entri': np.int64(604),
 'di': np.int64(516),
 'ur award': np.int64(2235),
 'train': np.int64(2171),
 'process': np.int64(1662),
 'hope': np.int64(959),
 'check': np.int64(321),
 'hope good': np.int64(961),
 'good week': np.int64(828),
 'place': np.int64(1589),
 'told': np.int64(2151),
 'big': np.int64(162),
 'load': np.int64(1169),
 'get readi': np.int64(772),
 'din': np.int64(524),
 'drop': np.int64(561),
 'em': np.int64(586),
 'omw': np.int64(1493),
 'omw back': np.int64(1494),
 'wont': np.int64(2421),
 'sort': np.int64(1944),
 'hous': np.int64(971),
 'yeah': np.int64(2475),
 'best': np.int64(158),
 'case': np.int64(291),
 'hair': np.int64(886),
 'moment': np.int64(1344),
 'fantasi': np.int64(654),
 'ntt': np.int64(1456),
 'ltd': np.int64(1223),
 'po': np.int64(1608),
 'box': np.int64(199),
 'croydon': np.int64(445),
 'cr': np.int64(435),
 'wb': np.int64(2347),
 'min ntt': np.int64(1300),
 'ntt ltd': np.int64(1457),
 'ltd po': np.int64(1224),
 'po box': np.int64(1609),
 'box croydon': np.int64(200),
 'croydon cr': np.int64(446),
 'cr wb': np.int64(436),
 'wb nation': np.int64(2348),
 'rate call': np.int64(1686),
 'buy': np.int64(225),
 'blackberri': np.int64(175),
 'bold': np.int64(184),
 'torch': np.int64(2163),
 'plu': np.int64(1602),
 'let know': np.int64(1142),
 'say lt': np.int64(1798),
 'pl': np.int64(1580),
 'pl dont': np.int64(1583),
 'beauti': np.int64(147),
 'express': np.int64(641),
 'face': np.int64(646),
 'seen': np.int64(1823),
 'everyon': np.int64(624),
 'heart': np.int64(913),
 'gud': np.int64(870),
 'ni': np.int64(1427),
 'beauti truth': np.int64(148),
 'love one': np.int64(1214),
 'gud ni': np.int64(873),
 'awak': np.int64(117),
 'snow': np.int64(1918),
 'kalli': np.int64(1061),
 'play': np.int64(1592),
 'earli': np.int64(571),
 'guarante award': np.int64(867),
 'claim ur': np.int64(337),
 'award call': np.int64(120),
 'call free': np.int64(242),
 'wan': np.int64(2317),
 'wan come': np.int64(2318),
 'everi': np.int64(617),
 'win': np.int64(2395),
 'music': np.int64(1387),
 'voucher': np.int64(2299),
 'word': np.int64(2422),
 'tsc': np.int64(2189),
 'ldew': np.int64(1120),
 'com': np.int64(365),
 'age': np.int64(33),
 'gift voucher': np.int64(781),
 'everi week': np.int64(621),
 'week start': np.int64(2361),
 'txt word': np.int64(2208),
 'www ldew': np.int64(2449),
 'ldew com': np.int64(1121),
 'pete': np.int64(1563),
 'colleg': np.int64(361),
 'graviti': np.int64(845),
 'care': np.int64(284),
 'light': np.int64(1149),
 'someon': np.int64(1926),
 'truth graviti': np.int64(2186),
 'graviti read': np.int64(846),
 'read care': np.int64(1693),
 'care heart': np.int64(286),
 'heart feel': np.int64(914),
 'feel light': np.int64(668),
 'light someon': np.int64(1150),
 'someon feel': np.int64(1927),
 'feel heavi': np.int64(667),
 'heavi someon': np.int64(916),
 'someon leav': np.int64(1929),
 'good night': np.int64(826),
 'sec': np.int64(1811),
 'wake': np.int64(2314),
 'wonder': np.int64(2420),
 'forgot': np.int64(706),
 'take care': np.int64(2052),
 'speak': np.int64(1951),
 'system': np.int64(2049),
 'well': np.int64(2371),
 'deep': np.int64(499),
 'boo': np.int64(187),
 'laugh': np.int64(1117),
 'bu': np.int64(216),
 'soon': np.int64(1940),
 'otherwis': np.int64(1523),
 'fine': np.int64(684),
 'bitch': np.int64(171),
 'bag': np.int64(132),
 'work': np.int64(2423),
 'meal': np.int64(1274),
 'cuz': np.int64(465),
 'sweet': np.int64(2043),
 'want go': np.int64(2326),
 'feel like': np.int64(669),
 'prob': np.int64(1658),
 'oh ok': np.int64(1474),
 'ok prob': np.int64(1480),
 'comput': np.int64(387),
 'fri': np.int64(730),
 'roommat': np.int64(1763),
 'run': np.int64(1772),
 'full': np.int64(742),
 'mum': np.int64(1382),
 'hour': np.int64(970),
 'lucki': np.int64(1226),
 'put': np.int64(1668),
 'busi': np.int64(224),
 'pictur': np.int64(1574),
 'facebook': np.int64(647),
 'open': np.int64(1505),
 'peopl': np.int64(1551),
 'ever': np.int64(616),
 'met': np.int64(1292),
 'hurt': np.int64(985),
 'forc': np.int64(703),
 'realli': np.int64(1698),
 'hungri': np.int64(982),
 'suck': np.int64(2021),
 'mark': np.int64(1256),
 'worri': np.int64(2427),
 'sick': np.int64(1876),
 'turn': np.int64(2194),
 'pizza': np.int64(1579),
 'dunno': np.int64(568),
 'type': np.int64(2212),
 'ar': np.int64(84),
 'normal': np.int64(1451),
 'hot': np.int64(968),
 'talk': np.int64(2055),
 'kind': np.int64(1076),
 'took': np.int64(2161),
 'centr': np.int64(307),
 'exhaust': np.int64(635),
 'order': np.int64(1518),
 'fix': np.int64(690),
 'tomo': np.int64(2152),
 'sent': np.int64(1841),
 'school': np.int64(1802),
 'deal': np.int64(489),
 'harri': np.int64(907),
 'book': np.int64(188),
 'answer': np.int64(66),
 'question': np.int64(1671),
 'rington': np.int64(1755),
 'collect': np.int64(358),
 'password': np.int64(1544),
 'verifi': np.int64(2279),
 'fml': np.int64(698),
 'free rington': np.int64(724),
 'that': np.int64(2095),
 'fall': np.int64(650),
 'bcoz': np.int64(145),
 'hold': np.int64(945),
 'bslvyl': np.int64(212),
 'fall love': np.int64(651),
 'funni': np.int64(746),
 'project': np.int64(1663),
 'bye': np.int64(229),
 'abiola': np.int64(2),
 'miss': np.int64(1314),
 'right': np.int64(1752),
 'space': np.int64(1950),
 'becom': np.int64(149),
 'suggest': np.int64(2022),
 'definit': np.int64(501),
 'move': np.int64(1361),
 'want need': np.int64(2328),
 'obvious': np.int64(1467),
 'went': np.int64(2376),
 'letter': np.int64(1143),
 'mean': np.int64(1275),
 'dirti': np.int64(528),
 'moon': np.int64(1351),
 'eye': np.int64(644),
 'result': np.int64(1744),
 'law': np.int64(1118),
 'woman': np.int64(2419),
 'boytoy': np.int64(203),
 'smth': np.int64(1916),
 'flight': np.int64(694),
 'ppm': np.int64(1633),
 'free call': np.int64(717),
 'anytim': np.int64(72),
 'landlin': np.int64(1095),
 'ibiza': np.int64(989),
 'holiday': np.int64(949),
 'cash': np.int64(292),
 'await': np.int64(115),
 'sae': np.int64(1775),
 'cs': np.int64(447),
 'sk': np.int64(1899),
 'wp': np.int64(2435),
 'urgent call': np.int64(2257),
 'call landlin': np.int64(247),
 'landlin complimentari': np.int64(1096),
 'complimentari ibiza': np.int64(385),
 'ibiza holiday': np.int64(990),
 'holiday cash': np.int64(951),
 'cash await': np.int64(293),
 'await collect': np.int64(116),
 'collect sae': np.int64(360),
 'sae cs': np.int64(1776),
 'box sk': np.int64(201),
 'sk wp': np.int64(1900),
 'wp ppm': np.int64(2436),
 'understand': np.int64(2221),
 'avoid': np.int64(114),
 'alon': np.int64(51),
 'mobil': np.int64(1328),
 'tc': np.int64(2060),
 'biz': np.int64(173),
 'gbp': np.int64(760),
 'new mobil': np.int64(1419),
 'actual': np.int64(16),
 'yor': np.int64(2493),
 'man': np.int64(1248),
 'pay': np.int64(1546),
 'rent': np.int64(1724),
 'fill': np.int64(675),
 'ga': np.int64(749),
 'stress': np.int64(2009),
 'got money': np.int64(836),
 'pay rent': np.int64(1548),
 'decim': np.int64(496),
 'balanc': np.int64(135),
 'rs': np.int64(1769),
 'id': np.int64(992),

In [165]:
from sklearn.naive_bayes import MultinomialNB
spam_detection_tfidf = MultinomialNB().fit(X_train, y_train)

In [166]:
y_pred = spam_detection_tfidf.predict(X_test)
y_pred

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True, False,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True, ...,  True,  True,  True, False,  True,  True,  True, False,  True,  True, False,  True,  True,  True,  True,  True,  True,  True, False,  True,  True,  True,  True,  True,  True, False,  True,  True,  True,  True])

In [167]:
accuracy_tfidf = accuracy_score(y_test, y_pred)
accuracy

0.9766816143497757

### Word2Vec

In [192]:
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()

In [193]:
corpus = []
for i in range(0, len(matter)):
  review = re.sub('[^a-zA-Z]', ' ', matter['text'][i])
  review=review.lower()
  review = review.split()
  review=[lemmatizer.lemmatize(word) for word in review]
  review=' '.join(review)
  corpus.append(review)

In [194]:
corpus

['go until jurong point crazy available only in bugis n great world la e buffet cine there got amore wat',
 'ok lar joking wif u oni',
 'free entry in a wkly comp to win fa cup final tkts st may text fa to to receive entry question std txt rate t c s apply over s',
 'u dun say so early hor u c already then say',
 'nah i don t think he go to usf he life around here though',
 'freemsg hey there darling it s been week s now and no word back i d like some fun you up for it still tb ok xxx std chgs to send to rcv',
 'even my brother is not like to speak with me they treat me like aid patent',
 'a per your request melle melle oru minnaminunginte nurungu vettam ha been set a your callertune for all caller press to copy your friend callertune',
 'winner a a valued network customer you have been selected to receivea prize reward to claim call claim code kl valid hour only',
 'had your mobile month or more u r entitled to update to the latest colour mobile with camera for free call the mobile update co free on',
 'i m gonna be home soon and i don t want to talk about this stuff anymore tonight k i ve cried enough today',
 'six chance to win cash from to pound txt csh and send to cost p day day tsandcs apply reply hl info',
 'urgent you have won a week free membership in our prize jackpot txt the word claim to no t c www dbuk net lccltd pobox ldnw a rw',
 'i ve been searching for the right word to thank you for this breather i promise i wont take your help for granted and will fulfil my promise you have been wonderful and a blessing at all time',
 'i have a date on sunday with will',
 'xxxmobilemovieclub to use your credit click the wap link in the next txt message or click here http wap xxxmobilemovieclub com n qjkgighjjgcbl',
 'oh k i m watching here',
 'eh u remember how spell his name yes i did he v naughty make until i v wet',
 'fine if that s the way u feel that s the way it gota b',
 'england v macedonia dont miss the goal team news txt ur national team to eg england to try wale scotland txt poboxox w wq',
 'is that seriously how you spell his name',
 'i m going to try for month ha ha only joking',
 'so pay first lar then when is da stock comin',
 'aft i finish my lunch then i go str down lor ard smth lor u finish ur lunch already',
 'ffffffffff alright no way i can meet up with you sooner',
 'just forced myself to eat a slice i m really not hungry tho this suck mark is getting worried he know i m sick when i turn down pizza lol',
 'lol your always so convincing',
 'did you catch the bus are you frying an egg did you make a tea are you eating your mom s left over dinner do you feel my love',
 'i m back amp we re packing the car now i ll let you know if there s room',
 'ahhh work i vaguely remember that what doe it feel like lol',
 'wait that s still not all that clear were you not sure about me being sarcastic or that that s why x doesn t want to live with u',
 'yeah he got in at and wa v apologetic n had fallen out and she wa actin like spoilt child and he got caught up in that till but we won t go there not doing too badly cheer you',
 'k tell me anything about you',
 'for fear of fainting with the of all that housework you just did quick have a cuppa',
 'thanks for your subscription to ringtone uk your mobile will be charged month please confirm by replying yes or no if you reply no you will not be charged',
 'yup ok i go home look at the timing then i msg again xuhui going to learn on nd may too but her lesson is at am',
 'oops i ll let you know when my roommate s done',
 'i see the letter b on my car',
 'anything lor u decide',
 'hello how s you and how did saturday go i wa just texting to see if you d decided to do anything tomo not that i m trying to invite myself or anything',
 'pls go ahead with watt i just wanted to be sure do have a great weekend abiola',
 'did i forget to tell you i want you i need you i crave you but most of all i love you my sweet arabian steed mmmmmm yummy',
 'rodger burn msg we tried to call you re your reply to our sm for a free nokia mobile free camcorder please call now for delivery tomorrow',
 'who are you seeing',
 'great i hope you like your man well endowed i am lt gt inch',
 'no call message missed call',
 'didn t you get hep b immunisation in nigeria',
 'fair enough anything going on',
 'yeah hopefully if tyler can t do it i could maybe ask around a bit',
 'u don t know how stubborn i am i didn t even want to go to the hospital i kept telling mark i m not a weak sucker hospital are for weak sucker',
 'what you thinked about me first time you saw me in class',
 'a gram usually run like lt gt a half eighth is smarter though and get you almost a whole second gram for lt gt',
 'k fyi x ha a ride early tomorrow morning but he s crashing at our place tonight',
 'wow i never realized that you were so embarassed by your accomodations i thought you liked it since i wa doing the best i could and you always seemed so happy about the cave i m sorry i didn t and don t have more to give i m sorry i offered i m sorry your room wa so embarassing',
 'sm ac sptv the new jersey devil and the detroit red wing play ice hockey correct or incorrect end reply end sptv',
 'do you know what mallika sherawat did yesterday find out now lt url gt',
 'congrats year special cinema pas for is yours call now c suprman v matrix starwars etc all free bx ip we pm dont miss out',
 'sorry i ll call later in meeting',
 'tell where you reached',
 'yes gauti and sehwag out of odi series',
 'your gonna have to pick up a burger for yourself on your way home i can t even move pain is killing me',
 'ha ha ha good joke girl are situation seeker',
 'it a part of checking iq',
 'sorry my roommate took forever it ok if i come by now',
 'ok lar i double check wif da hair dresser already he said wun cut v short he said will cut until i look nice',
 'a a valued customer i am pleased to advise you that following recent review of your mob no you are awarded with a bonus prize call',
 'today is song dedicated day which song will u dedicate for me send this to all ur valuable frnds but first rply me',
 'urgent ur awarded a complimentary trip to eurodisinc trav aco entry or to claim txt dis to morefrmmob shracomorsglsuplt l aj',
 'did you hear about the new divorce barbie it come with all of ken s stuff',
 'i plane to give on this month end',
 'wah lucky man then can save money hee',
 'finished class where are you',
 'hi babe im at home now wanna do something xx',
 'k k where are you how did you performed',
 'u can call me now',
 'i am waiting machan call me once you free',
 'thats cool i am a gentleman and will treat you with dignity and respect',
 'i like you people very much but am very shy pa',
 'doe not operate after lt gt or what',
 'it not the same here still looking for a job how much do ta s earn there',
 'sorry i ll call later',
 'k did you call me just now ah',
 'ok i am on the way to home hi hi',
 'you will be in the place of that man',
 'yup next stop',
 'i call you later don t have network if urgnt sm me',
 'for real when u getting on yo i only need more ticket and one more jacket and i m done i already used all my multis',
 'yes i started to send request to make it but pain came back so i m back in bed double coin at the factory too i gotta cash in all my nitros',
 'i m really not up to it still tonight babe',
 'ela kano il download come wen ur free',
 'yeah do don t stand to close tho you ll catch something',
 'sorry to be a pain is it ok if we meet another night i spent late afternoon in casualty and that mean i haven t done any of y stuff moro and that includes all my time sheet and that sorry',
 'smile in pleasure smile in pain smile when trouble pours like rain smile when sum hurt u smile becoz someone still love to see u smiling',
 'please call our customer service representative on between am pm a you have won a guaranteed cash or prize',
 'havent planning to buy later i check already lido only got show in e afternoon u finish work already',
 'your free ringtone is waiting to be collected simply text the password mix to to verify get usher and britney fml po box mk h ppw',
 'watching telugu movie wat abt u',
 'i see when we finish we have load of loan to pay',
 'hi wk been ok on hols now yes on for a bit of a run forgot that i have hairdresser appointment at four so need to get home n shower beforehand doe that cause prob for u',
 'i see a cup of coffee animation',
 'please don t text me anymore i have nothing else to say',
 'okay name ur price a long a it legal wen can i pick them up y u ave x am xx',
 'i m still looking for a car to buy and have not gone the driving test yet',
 'a per your request melle melle oru minnaminunginte nurungu vettam ha been set a your callertune for all caller press to copy your friend callertune',
 'wow you re right i didn t mean to do that i guess once i gave up on boston men and changed my search location to nyc something changed cuz on my signin page it still say boston',
 'umma my life and vava umma love you lot dear',
 'thanks a lot for your wish on my birthday thanks you for making my birthday truly memorable',
 'aight i ll hit you up when i get some cash',
 'how would my ip address test that considering my computer isn t a minecraft server',
 'i know grumpy old people my mom wa like you better not be lying then again i am always the one to play joke',
 'dont worry i guess he s busy',
 'what is the plural of the noun research',
 'going for dinner msg you after',
 'i m ok wif it co i like try new thing but i scared u dun like mah co u said not too loud',
 'gent we are trying to contact you last weekend draw show that you won a prize guaranteed call claim code k valid hr only ppm',
 'wa ur openin sentence very formal anyway i m fine too juz tt i m eatin too much n puttin on weight haha so anythin special happened',
 'a i entered my cabin my pa said happy b day bos i felt special she askd me lunch after lunch she invited me to her apartment we went there',
 'you are a winner u have been specially selected receive or a holiday flight inc speak to a live operator claim p min',
 'goodo yes we must speak friday egg potato ratio for tortilla needed',
 'hmm my uncle just informed me that he s paying the school directly so pls buy food',
 'private your account statement for show unredeemed bonus point to claim call identifier code expires',
 'urgent your mobile no wa awarded bonus caller prize on this is our final try to contact u call from landline box wr c ppm',
 'here is my new address apple pair all that malarky',
 'today voda number ending are selected to receive a award if you have a match please call quoting claim code standard rate app',
 'i am going to sao mu today will be done only at',
 'predict wat time ll finish buying',
 'good stuff will do',
 'just so that you know yetunde hasn t sent money yet i just sent her a text not to bother sending so it over you dont have to involve yourself in anything i shouldn t have imposed anything on you in the first place so for that i apologise',
 'are you there in room',
 'hey girl how r u hope u r well me an del r bak again long time no c give me a call sum time from lucyxx',
 'k k how much doe it cost',
 'i m home',
 'dear will call tmorrow pls accomodate',
 'first answer my question',
 'sunshine quiz wkly q win a top sony dvd player if u know which country the algarve is in txt ansr to sp tyrone',
 'want get laid tonight want real dogging location sent direct ur mob join the uk s largest dogging network bt txting gravel to nt ec a p msg p',
 'i only haf msn it s yijue hotmail com',
 'he is there you call and meet him',
 'no no i will check all room befor activity',
 'you ll not rcv any more msg from the chat svc for free hardcore service text go to if u get nothing u must age verify with yr network try again',
 'got c i lazy to type i forgot in lect i saw a pouch but like not v nice',
 'k text me when you re on the way',
 'sir waiting for your mail',
 'a swt thought nver get tired of doing little thing lovable person coz somtimes those little thing occupy d biggest part in their heart gud ni',
 'i know you are can you pls open the back',
 'yes see ya not on the dot',
 'whats the staff name who is taking class for u',
 'freemsg why haven t you replied to my text i m randy sexy female and live local luv to hear from u netcollex ltd p per msg reply stop to end',
 'ummma will call after check in our life will begin from qatar so pls pray very hard',
 'k i deleted my contact that why',
 'sindu got job in birla soft',
 'the wine is flowing and i m i have nevering',
 'yup i thk cine is better co no need go down plaza mah',
 'ok ur typical reply',
 'a per your request melle melle oru minnaminunginte nurungu vettam ha been set a your callertune for all caller press to copy your friend callertune',
 'you are everywhere dirt on the floor the window even on my shirt and sometimes when i open my mouth you are all that come flowing out i dream of my world without you then half my chore are out too a time of joy for me lot of tv show i ll see but i guess like all thing you just must exist like rain hail and mist and when my time here is done you and i become one',
 'aaooooright are you at work',
 'i m leaving my house now',
 'hello my love what are you doing did you get to that interview today are you you happy are you being a good boy do you think of me are you missing me',
 'customer service annoncement you have a new year delivery waiting for you please call now to arrange delivery',
 'you are a winner u have been specially selected receive cash or a holiday flight inc speak to a live operator claim',
 'keep yourself safe for me because i need you and i miss you already and i envy everyone that see s you in real life',
 'new car and house for my parent i have only new job in hand',
 'i m so in love with you i m excited each day i spend with you you make me so happy',
 'pls stop bootydelious f is inviting you to be her friend reply yes or no see her www sm ac u bootydelious stop send stop frnd to',
 'bangbabes ur order is on the way u should receive a service msg download ur content if u do not goto wap bangb tv on ur mobile internet service menu',
 'i place all ur point on e culture module already',
 'urgent we are trying to contact you last weekend draw show that you have won a prize guaranteed call claim code s valid hr only',
 'hi frnd which is best way to avoid missunderstding wit our beloved one s',
 'great escape i fancy the bridge but need her lager see you tomo',
 'yes it completely in out of form clark also utter waste',
 'sir i need axis bank account no and bank address',
 'hmmm thk sure got time to hop ard ya can go free abt muz call u to discus liao',
 'what time you coming down later',
 'bloody hell cant believe you forgot my surname mr ill give u a clue it spanish and begin with m',
 'well i m gonna finish my bath now have a good fine night',
 'let me know when you ve got the money so carlos can make the call',
 'u still going to the mall',
 'turn out my friend are staying for the whole show and won t be back til lt gt so feel free to go ahead and smoke that lt gt worth',
 'text her if she doesnt reply let me know so i can have her log in',
 'hi you just spoke to maneesha v we d like to know if you were satisfied with the experience reply toll free with yes or no',
 'you lifted my hope with the offer of money i am in need especially when the end of the month approach and it hurt my studying anyways have a gr weekend',
 'lol no u can trust me',
 'ok i am a gentleman and will treat you with dignity and respect',
 'he will you guy close',
 'going on nothing great bye',
 'hello handsome are you finding that job not being lazy working towards getting back that net for mummy where s my boytoy now doe he miss me',
 'haha awesome be there in a minute',
 'please call our customer service representative on freephone between am pm a you have won a guaranteed cash or prize',
 'have you got xmas radio time if not i will get it now',
 'i jus reached home i go bathe first but my si using net tell u when she finish k',
 'are you unique enough find out from th august www areyouunique co uk',
 'i m sorry i ve joined the league of people that dont keep in touch you mean a great deal to me you have been a friend at all time even at great personal cost do have a great week',
 'hi finally i completed the course',
 'it will stop on itself i however suggest she stay with someone that will be able to give or for every stool',
 'how are you doing hope you ve settled in for the new school year just wishin you a gr day',
 'gud mrng dear hav a nice day',
 'did u got that person story',
 'is your hamster dead hey so tmr i meet you at pm orchard mrt',
 'hi it kate how is your evening i hope i can see you tomorrow for a bit but i have to bloody babyjontet txt back if u can xxx',
 'found it enc lt gt where you at',
 'i sent you lt gt buck',
 'hello darlin ive finished college now so txt me when u finish if u can love kate xxx',
 'your account ha been refilled successfully by inr lt decimal gt your keralacircle prepaid account balance is r lt decimal gt your transaction id is kr lt gt',
 'goodmorning sleeping ga',
 'u call me alter at ok',
 'say until like dat i dun buy ericsson oso cannot oredi lar',
 'a i entered my cabin my pa said happy b day bos i felt special she askd me lunch after lunch she invited me to her apartment we went there',
 'aight yo dat straight dogg',
 'you please give u connection today itself before lt decimal gt or refund the bill',
 'both i shoot big load so get ready',
 'what s up bruv hope you had a great break do have a rewarding semester',
 'home so we can always chat',
 'k k good study well',
 'yup how noe leh',
 'sound great are you home now',
 'finally the match heading towards draw a your prediction',
 'tired i haven t slept well the past few night',
 'easy ah sen got selected mean it good',
 'i have to take exam with march',
 'yeah you should i think you can use your gt atm now to register not sure but if there s anyway i can help let me know but when you do be sure you are ready',
 'ok no prob take ur time',
 'there is o called ubandu which will run without installing in hard disk you can use that o to copy the important file in system and give it to repair shop',
 'sorry i ll call later',
 'u say leh of course nothing happen lar not say v romantic jus a bit only lor i thk e nite scenery not so nice leh',
 'new mobile from must go txt nokia to no collect yours today from only www tc biz optout gbp mtmsg',
 'would really appreciate if you call me just need someone to talk to',
 'will u meet ur dream partner soon is ur career off a flyng start find out free txt horo followed by ur star sign e g horo aries',
 'hey company elama po mudyadhu',
 'life is more strict than teacher bcoz teacher teach lesson amp then conduct exam but life first conduct exam amp then teach lesson happy morning',
 'dear good morning now only i am up',
 'get down in gandhipuram and walk to cross cut road right side lt gt street road and turn at first right',
 'dear we are going to our rubber place',
 'sorry battery died yeah i m here',
 'yes here tv is always available in work place',
 'text meet someone sexy today u can find a date or even flirt it up to u join just p reply with name age eg sam msg recd thirtyeight penny',
 'i have printed it oh so lt gt come upstairs',
 'or ill be a little closer like at the bus stop on the same street',
 'where are you when wil you reach here',
 'new theory argument win d situation but loses the person so dont argue with ur friend just kick them amp say i m always correct',
 'u have a secret admirer who is looking make contact with u find out who they r reveal who think ur so special call on',
 'tomarrow final hearing on my laptop case so i cant',
 'pleassssssseeeeee tel me v avent done sportsx',
 'okay no no just shining on that wa meant to be signing but that sound better',

In [195]:
from nltk import sent_tokenize
from gensim.utils import simple_preprocess
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [196]:
words=[]
for sent in corpus:
  sent_token = sent_tokenize(sent)
  for sent in sent_token:
    words.append(simple_preprocess(sent))

In [197]:
words

[['go',
  'until',
  'jurong',
  'point',
  'crazy',
  'available',
  'only',
  'in',
  'bugis',
  'great',
  'world',
  'la',
  'buffet',
  'cine',
  'there',
  'got',
  'amore',
  'wat'],
 ['ok', 'lar', 'joking', 'wif', 'oni'],
 ['free',
  'entry',
  'in',
  'wkly',
  'comp',
  'to',
  'win',
  'fa',
  'cup',
  'final',
  'tkts',
  'st',
  'may',
  'text',
  'fa',
  'to',
  'to',
  'receive',
  'entry',
  'question',
  'std',
  'txt',
  'rate',
  'apply',
  'over'],
 ['dun', 'say', 'so', 'early', 'hor', 'already', 'then', 'say'],
 ['nah',
  'don',
  'think',
  'he',
  'go',
  'to',
  'usf',
  'he',
  'life',
  'around',
  'here',
  'though'],
 ['freemsg',
  'hey',
  'there',
  'darling',
  'it',
  'been',
  'week',
  'now',
  'and',
  'no',
  'word',
  'back',
  'like',
  'some',
  'fun',
  'you',
  'up',
  'for',
  'it',
  'still',
  'tb',
  'ok',
  'xxx',
  'std',
  'chgs',
  'to',
  'send',
  'to',
  'rcv'],
 ['even',
  'my',
  'brother',
  'is',
  'not',
  'like',
  'to',
  'speak',
  'with',
  'me',
  'they',
  'treat',
  'me',
  'like',
  'aid',
  'patent'],
 ['per',
  'your',
  'request',
  'melle',
  'melle',
  'oru',
  'minnaminunginte',
  'nurungu',
  'vettam',
  'ha',
  'been',
  'set',
  'your',
  'callertune',
  'for',
  'all',
  'caller',
  'press',
  'to',
  'copy',
  'your',
  'friend',
  'callertune'],
 ['winner',
  'valued',
  'network',
  'customer',
  'you',
  'have',
  'been',
  'selected',
  'to',
  'receivea',
  'prize',
  'reward',
  'to',
  'claim',
  'call',
  'claim',
  'code',
  'kl',
  'valid',
  'hour',
  'only'],
 ['had',
  'your',
  'mobile',
  'month',
  'or',
  'more',
  'entitled',
  'to',
  'update',
  'to',
  'the',
  'latest',
  'colour',
  'mobile',
  'with',
  'camera',
  'for',
  'free',
  'call',
  'the',
  'mobile',
  'update',
  'co',
  'free',
  'on'],
 ['gonna',
  'be',
  'home',
  'soon',
  'and',
  'don',
  'want',
  'to',
  'talk',
  'about',
  'this',
  'stuff',
  'anymore',
  'tonight',
  've',
  'cried',
  'enough',
  'today'],
 ['six',
  'chance',
  'to',
  'win',
  'cash',
  'from',
  'to',
  'pound',
  'txt',
  'csh',
  'and',
  'send',
  'to',
  'cost',
  'day',
  'day',
  'tsandcs',
  'apply',
  'reply',
  'hl',
  'info'],
 ['urgent',
  'you',
  'have',
  'won',
  'week',
  'free',
  'membership',
  'in',
  'our',
  'prize',
  'jackpot',
  'txt',
  'the',
  'word',
  'claim',
  'to',
  'no',
  'www',
  'dbuk',
  'net',
  'lccltd',
  'pobox',
  'ldnw',
  'rw'],
 ['ve',
  'been',
  'searching',
  'for',
  'the',
  'right',
  'word',
  'to',
  'thank',
  'you',
  'for',
  'this',
  'breather',
  'promise',
  'wont',
  'take',
  'your',
  'help',
  'for',
  'granted',
  'and',
  'will',
  'fulfil',
  'my',
  'promise',
  'you',
  'have',
  'been',
  'wonderful',
  'and',
  'blessing',
  'at',
  'all',
  'time'],
 ['have', 'date', 'on', 'sunday', 'with', 'will'],
 ['to',
  'use',
  'your',
  'credit',
  'click',
  'the',
  'wap',
  'link',
  'in',
  'the',
  'next',
  'txt',
  'message',
  'or',
  'click',
  'here',
  'http',
  'wap',
  'com',
  'qjkgighjjgcbl'],
 ['oh', 'watching', 'here'],
 ['eh',
  'remember',
  'how',
  'spell',
  'his',
  'name',
  'yes',
  'did',
  'he',
  'naughty',
  'make',
  'until',
  'wet'],
 ['fine',
  'if',
  'that',
  'the',
  'way',
  'feel',
  'that',
  'the',
  'way',
  'it',
  'gota'],
 ['england',
  'macedonia',
  'dont',
  'miss',
  'the',
  'goal',
  'team',
  'news',
  'txt',
  'ur',
  'national',
  'team',
  'to',
  'eg',
  'england',
  'to',
  'try',
  'wale',
  'scotland',
  'txt',
  'poboxox',
  'wq'],
 ['is', 'that', 'seriously', 'how', 'you', 'spell', 'his', 'name'],
 ['going', 'to', 'try', 'for', 'month', 'ha', 'ha', 'only', 'joking'],
 ['so', 'pay', 'first', 'lar', 'then', 'when', 'is', 'da', 'stock', 'comin'],
 ['aft',
  'finish',
  'my',
  'lunch',
  'then',
  'go',
  'str',
  'down',
  'lor',
  'ard',
  'smth',
  'lor',
  'finish',
  'ur',
  'lunch',
  'already'],
 ['ffffffffff',
  'alright',
  'no',
  'way',
  'can',
  'meet',
  'up',
  'with',
  'you',
  'sooner'],
 ['just',
  'forced',
  'myself',
  'to',
  'eat',
  'slice',
  'really',
  'not',
  'hungry',
  'tho',
  'this',
  'suck',
  'mark',
  'is',
  'getting',
  'worried',
  'he',
  'know',
  'sick',
  'when',
  'turn',
  'down',
  'pizza',
  'lol'],
 ['lol', 'your', 'always', 'so', 'convincing'],
 ['did',
  'you',
  'catch',
  'the',
  'bus',
  'are',
  'you',
  'frying',
  'an',
  'egg',
  'did',
  'you',
  'make',
  'tea',
  'are',
  'you',
  'eating',
  'your',
  'mom',
  'left',
  'over',
  'dinner',
  'do',
  'you',
  'feel',
  'my',
  'love'],
 ['back',
  'amp',
  'we',
  're',
  'packing',
  'the',
  'car',
  'now',
  'll',
  'let',
  'you',
  'know',
  'if',
  'there',
  'room'],
 ['ahhh',
  'work',
  'vaguely',
  'remember',
  'that',
  'what',
  'doe',
  'it',
  'feel',
  'like',
  'lol'],
 ['wait',
  'that',
  'still',
  'not',
  'all',
  'that',
  'clear',
  'were',
  'you',
  'not',
  'sure',
  'about',
  'me',
  'being',
  'sarcastic',
  'or',
  'that',
  'that',
  'why',
  'doesn',
  'want',
  'to',
  'live',
  'with'],
 ['yeah',
  'he',
  'got',
  'in',
  'at',
  'and',
  'wa',
  'apologetic',
  'had',
  'fallen',
  'out',
  'and',
  'she',
  'wa',
  'actin',
  'like',
  'spoilt',
  'child',
  'and',
  'he',
  'got',
  'caught',
  'up',
  'in',
  'that',
  'till',
  'but',
  'we',
  'won',
  'go',
  'there',
  'not',
  'doing',
  'too',
  'badly',
  'cheer',
  'you'],
 ['tell', 'me', 'anything', 'about', 'you'],
 ['for',
  'fear',
  'of',
  'fainting',
  'with',
  'the',
  'of',
  'all',
  'that',
  'housework',
  'you',
  'just',
  'did',
  'quick',
  'have',
  'cuppa'],
 ['thanks',
  'for',
  'your',
  'subscription',
  'to',
  'ringtone',
  'uk',
  'your',
  'mobile',
  'will',
  'be',
  'charged',
  'month',
  'please',
  'confirm',
  'by',
  'replying',
  'yes',
  'or',
  'no',
  'if',
  'you',
  'reply',
  'no',
  'you',
  'will',
  'not',
  'be',
  'charged'],
 ['yup',
  'ok',
  'go',
  'home',
  'look',
  'at',
  'the',
  'timing',
  'then',
  'msg',
  'again',
  'xuhui',
  'going',
  'to',
  'learn',
  'on',
  'nd',
  'may',
  'too',
  'but',
  'her',
  'lesson',
  'is',
  'at',
  'am'],
 ['oops', 'll', 'let', 'you', 'know', 'when', 'my', 'roommate', 'done'],
 ['see', 'the', 'letter', 'on', 'my', 'car'],
 ['anything', 'lor', 'decide'],
 ['hello',
  'how',
  'you',
  'and',
  'how',
  'did',
  'saturday',
  'go',
  'wa',
  'just',
  'texting',
  'to',
  'see',
  'if',
  'you',
  'decided',
  'to',
  'do',
  'anything',
  'tomo',
  'not',
  'that',
  'trying',
  'to',
  'invite',
  'myself',
  'or',
  'anything'],
 ['pls',
  'go',
  'ahead',
  'with',
  'watt',
  'just',
  'wanted',
  'to',
  'be',
  'sure',
  'do',
  'have',
  'great',
  'weekend',
  'abiola'],
 ['did',
  'forget',
  'to',
  'tell',
  'you',
  'want',
  'you',
  'need',
  'you',
  'crave',
  'you',
  'but',
  'most',
  'of',
  'all',
  'love',
  'you',
  'my',
  'sweet',
  'arabian',
  'steed',
  'mmmmmm',
  'yummy'],
 ['rodger',
  'burn',
  'msg',
  'we',
  'tried',
  'to',
  'call',
  'you',
  're',
  'your',
  'reply',
  'to',
  'our',
  'sm',
  'for',
  'free',
  'nokia',
  'mobile',
  'free',
  'camcorder',
  'please',
  'call',
  'now',
  'for',
  'delivery',
  'tomorrow'],
 ['who', 'are', 'you', 'seeing'],
 ['great',
  'hope',
  'you',
  'like',
  'your',
  'man',
  'well',
  'endowed',
  'am',
  'lt',
  'gt',
  'inch'],
 ['no', 'call', 'message', 'missed', 'call'],
 ['didn', 'you', 'get', 'hep', 'immunisation', 'in', 'nigeria'],
 ['fair', 'enough', 'anything', 'going', 'on'],
 ['yeah',
  'hopefully',
  'if',
  'tyler',
  'can',
  'do',
  'it',
  'could',
  'maybe',
  'ask',
  'around',
  'bit'],
 ['don',
  'know',
  'how',
  'stubborn',
  'am',
  'didn',
  'even',
  'want',
  'to',
  'go',
  'to',
  'the',
  'hospital',
  'kept',
  'telling',
  'mark',
  'not',
  'weak',
  'sucker',
  'hospital',
  'are',
  'for',
  'weak',
  'sucker'],
 ['what',
  'you',
  'thinked',
  'about',
  'me',
  'first',
  'time',
  'you',
  'saw',
  'me',
  'in',
  'class'],
 ['gram',
  'usually',
  'run',
  'like',
  'lt',
  'gt',
  'half',
  'eighth',
  'is',
  'smarter',
  'though',
  'and',
  'get',
  'you',
  'almost',
  'whole',
  'second',
  'gram',
  'for',
  'lt',
  'gt'],
 ['fyi',
  'ha',
  'ride',
  'early',
  'tomorrow',
  'morning',
  'but',
  'he',
  'crashing',
  'at',
  'our',
  'place',
  'tonight'],
 ['wow',
  'never',
  'realized',
  'that',
  'you',
  'were',
  'so',
  'embarassed',
  'by',
  'your',
  'accomodations',
  'thought',
  'you',
  'liked',
  'it',
  'since',
  'wa',
  'doing',
  'the',
  'best',
  'could',
  'and',
  'you',
  'always',
  'seemed',
  'so',
  'happy',
  'about',
  'the',
  'cave',
  'sorry',
  'didn',
  'and',
  'don',
  'have',
  'more',
  'to',
  'give',
  'sorry',
  'offered',
  'sorry',
  'your',
  'room',
  'wa',
  'so',
  'embarassing'],
 ['sm',
  'ac',
  'sptv',
  'the',
  'new',
  'jersey',
  'devil',
  'and',
  'the',
  'detroit',
  'red',
  'wing',
  'play',
  'ice',
  'hockey',
  'correct',
  'or',
  'incorrect',
  'end',
  'reply',
  'end',
  'sptv'],
 ['do',
  'you',
  'know',
  'what',
  'mallika',
  'sherawat',
  'did',
  'yesterday',
  'find',
  'out',
  'now',
  'lt',
  'url',
  'gt'],
 ['congrats',
  'year',
  'special',
  'cinema',
  'pas',
  'for',
  'is',
  'yours',
  'call',
  'now',
  'suprman',
  'matrix',
  'starwars',
  'etc',
  'all',
  'free',
  'bx',
  'ip',
  'we',
  'pm',
  'dont',
  'miss',
  'out'],
 ['sorry', 'll', 'call', 'later', 'in', 'meeting'],
 ['tell', 'where', 'you', 'reached'],
 ['yes', 'gauti', 'and', 'sehwag', 'out', 'of', 'odi', 'series'],
 ['your',
  'gonna',
  'have',
  'to',
  'pick',
  'up',
  'burger',
  'for',
  'yourself',
  'on',
  'your',
  'way',
  'home',
  'can',
  'even',
  'move',
  'pain',
  'is',
  'killing',
  'me'],
 ['ha', 'ha', 'ha', 'good', 'joke', 'girl', 'are', 'situation', 'seeker'],
 ['it', 'part', 'of', 'checking', 'iq'],
 ['sorry',
  'my',
  'roommate',
  'took',
  'forever',
  'it',
  'ok',
  'if',
  'come',
  'by',
  'now'],
 ['ok',
  'lar',
  'double',
  'check',
  'wif',
  'da',
  'hair',
  'dresser',
  'already',
  'he',
  'said',
  'wun',
  'cut',
  'short',
  'he',
  'said',
  'will',
  'cut',
  'until',
  'look',
  'nice'],
 ['valued',
  'customer',
  'am',
  'pleased',
  'to',
  'advise',
  'you',
  'that',
  'following',
  'recent',
  'review',
  'of',
  'your',
  'mob',
  'no',
  'you',
  'are',
  'awarded',
  'with',
  'bonus',
  'prize',
  'call'],
 ['today',
  'is',
  'song',
  'dedicated',
  'day',
  'which',
  'song',
  'will',
  'dedicate',
  'for',
  'me',
  'send',
  'this',
  'to',
  'all',
  'ur',
  'valuable',
  'frnds',
  'but',
  'first',
  'rply',
  'me'],
 ['urgent',
  'ur',
  'awarded',
  'complimentary',
  'trip',
  'to',
  'eurodisinc',
  'trav',
  'aco',
  'entry',
  'or',
  'to',
  'claim',
  'txt',
  'dis',
  'to',
  'morefrmmob',
  'aj'],
 ['did',
  'you',
  'hear',
  'about',
  'the',
  'new',
  'divorce',
  'barbie',
  'it',
  'come',
  'with',
  'all',
  'of',
  'ken',
  'stuff'],
 ['plane', 'to', 'give', 'on', 'this', 'month', 'end'],
 ['wah', 'lucky', 'man', 'then', 'can', 'save', 'money', 'hee'],
 ['finished', 'class', 'where', 'are', 'you'],
 ['hi', 'babe', 'im', 'at', 'home', 'now', 'wanna', 'do', 'something', 'xx'],
 ['where', 'are', 'you', 'how', 'did', 'you', 'performed'],
 ['can', 'call', 'me', 'now'],
 ['am', 'waiting', 'machan', 'call', 'me', 'once', 'you', 'free'],
 ['thats',
  'cool',
  'am',
  'gentleman',
  'and',
  'will',
  'treat',
  'you',
  'with',
  'dignity',
  'and',
  'respect'],
 ['like', 'you', 'people', 'very', 'much', 'but', 'am', 'very', 'shy', 'pa'],
 ['doe', 'not', 'operate', 'after', 'lt', 'gt', 'or', 'what'],
 ['it',
  'not',
  'the',
  'same',
  'here',
  'still',
  'looking',
  'for',
  'job',
  'how',
  'much',
  'do',
  'ta',
  'earn',
  'there'],
 ['sorry', 'll', 'call', 'later'],
 ['did', 'you', 'call', 'me', 'just', 'now', 'ah'],
 ['ok', 'am', 'on', 'the', 'way', 'to', 'home', 'hi', 'hi'],
 ['you', 'will', 'be', 'in', 'the', 'place', 'of', 'that', 'man'],
 ['yup', 'next', 'stop'],
 ['call', 'you', 'later', 'don', 'have', 'network', 'if', 'urgnt', 'sm', 'me'],
 ['for',
  'real',
  'when',
  'getting',
  'on',
  'yo',
  'only',
  'need',
  'more',
  'ticket',
  'and',
  'one',
  'more',
  'jacket',
  'and',
  'done',
  'already',
  'used',
  'all',
  'my',
  'multis'],
 ['yes',
  'started',
  'to',
  'send',
  'request',
  'to',
  'make',
  'it',
  'but',
  'pain',
  'came',
  'back',
  'so',
  'back',
  'in',
  'bed',
  'double',
  'coin',
  'at',
  'the',
  'factory',
  'too',
  'gotta',
  'cash',
  'in',
  'all',
  'my',
  'nitros'],
 ['really', 'not', 'up', 'to', 'it', 'still', 'tonight', 'babe'],
 ['ela', 'kano', 'il', 'download', 'come', 'wen', 'ur', 'free'],
 ['yeah',
  'do',
  'don',
  'stand',
  'to',
  'close',
  'tho',
  'you',
  'll',
  'catch',
  'something'],
 ['sorry',
  'to',
  'be',
  'pain',
  'is',
  'it',
  'ok',
  'if',
  'we',
  'meet',
  'another',
  'night',
  'spent',
  'late',
  'afternoon',
  'in',
  'casualty',
  'and',
  'that',
  'mean',
  'haven',
  'done',
  'any',
  'of',
  'stuff',
  'moro',
  'and',
  'that',
  'includes',
  'all',
  'my',
  'time',
  'sheet',
  'and',
  'that',
  'sorry'],
 ['smile',
  'in',
  'pleasure',
  'smile',
  'in',
  'pain',
  'smile',
  'when',
  'trouble',
  'pours',
  'like',
  'rain',
  'smile',
  'when',
  'sum',
  'hurt',
  'smile',
  'becoz',
  'someone',
  'still',
  'love',
  'to',
  'see',
  'smiling'],
 ['please',
  'call',
  'our',
  'customer',
  'service',
  'representative',
  'on',
  'between',
  'am',
  'pm',
  'you',
  'have',
  'won',
  'guaranteed',
  'cash',
  'or',
  'prize'],
 ['havent',
  'planning',
  'to',
  'buy',
  'later',
  'check',
  'already',
  'lido',
  'only',
  'got',
  'show',
  'in',
  'afternoon',
  'finish',
  'work',
  'already'],
 ['your',
  'free',
  'ringtone',
  'is',
  'waiting',
  'to',
  'be',
  'collected',
  'simply',
  'text',
  'the',
  'password',
  'mix',
  'to',
  'to',
  'verify',
  'get',
  'usher',
  'and',
  'britney',
  'fml',
  'po',
  'box',
  'mk',
  'ppw'],
 ['watching', 'telugu', 'movie', 'wat', 'abt'],
 ['see',
  'when',
  'we',
  'finish',
  'we',
  'have',
  'load',
  'of',
  'loan',
  'to',
  'pay'],
 ['hi',
  'wk',
  'been',
  'ok',
  'on',
  'hols',
  'now',
  'yes',
  'on',
  'for',
  'bit',
  'of',
  'run',
  'forgot',
  'that',
  'have',
  'hairdresser',
  'appointment',
  'at',
  'four',
  'so',
  'need',
  'to',
  'get',
  'home',
  'shower',
  'beforehand',
  'doe',
  'that',
  'cause',
  'prob',
  'for'],
 ['see', 'cup', 'of', 'coffee', 'animation'],
 ['please',
  'don',
  'text',
  'me',
  'anymore',
  'have',
  'nothing',
  'else',
  'to',
  'say'],
 ['okay',
  'name',
  'ur',
  'price',
  'long',
  'it',
  'legal',
  'wen',
  'can',
  'pick',
  'them',
  'up',
  'ave',
  'am',
  'xx'],
 ['still',
  'looking',
  'for',
  'car',
  'to',
  'buy',
  'and',
  'have',
  'not',
  'gone',
  'the',
  'driving',
  'test',
  'yet'],
 ['per',
  'your',
  'request',
  'melle',
  'melle',
  'oru',
  'minnaminunginte',
  'nurungu',
  'vettam',
  'ha',
  'been',
  'set',
  'your',
  'callertune',
  'for',
  'all',
  'caller',
  'press',
  'to',
  'copy',
  'your',
  'friend',
  'callertune'],
 ['wow',
  'you',
  're',
  'right',
  'didn',
  'mean',
  'to',
  'do',
  'that',
  'guess',
  'once',
  'gave',
  'up',
  'on',
  'boston',
  'men',
  'and',
  'changed',
  'my',
  'search',
  'location',
  'to',
  'nyc',
  'something',
  'changed',
  'cuz',
  'on',
  'my',
  'signin',
  'page',
  'it',
  'still',
  'say',
  'boston'],
 ['umma', 'my', 'life', 'and', 'vava', 'umma', 'love', 'you', 'lot', 'dear'],
 ['thanks',
  'lot',
  'for',
  'your',
  'wish',
  'on',
  'my',
  'birthday',
  'thanks',
  'you',
  'for',
  'making',
  'my',
  'birthday',
  'truly',
  'memorable'],
 ['aight', 'll', 'hit', 'you', 'up', 'when', 'get', 'some', 'cash'],
 ['how',
  'would',
  'my',
  'ip',
  'address',
  'test',
  'that',
  'considering',
  'my',
  'computer',
  'isn',
  'minecraft',
  'server'],
 ['know',
  'grumpy',
  'old',
  'people',
  'my',
  'mom',
  'wa',
  'like',
  'you',
  'better',
  'not',
  'be',
  'lying',
  'then',
  'again',
  'am',
  'always',
  'the',
  'one',
  'to',
  'play',
  'joke'],
 ['dont', 'worry', 'guess', 'he', 'busy'],
 ['what', 'is', 'the', 'plural', 'of', 'the', 'noun', 'research'],
 ['going', 'for', 'dinner', 'msg', 'you', 'after'],
 ['ok',
  'wif',
  'it',
  'co',
  'like',
  'try',
  'new',
  'thing',
  'but',
  'scared',
  'dun',
  'like',
  'mah',
  'co',
  'said',
  'not',
  'too',
  'loud'],
 ['gent',
  'we',
  'are',
  'trying',
  'to',
  'contact',
  'you',
  'last',
  'weekend',
  'draw',
  'show',
  'that',
  'you',
  'won',
  'prize',
  'guaranteed',
  'call',
  'claim',
  'code',
  'valid',
  'hr',
  'only',
  'ppm'],
 ['wa',
  'ur',
  'openin',
  'sentence',
  'very',
  'formal',
  'anyway',
  'fine',
  'too',
  'juz',
  'tt',
  'eatin',
  'too',
  'much',
  'puttin',
  'on',
  'weight',
  'haha',
  'so',
  'anythin',
  'special',
  'happened'],
 ['entered',
  'my',
  'cabin',
  'my',
  'pa',
  'said',
  'happy',
  'day',
  'bos',
  'felt',
  'special',
  'she',
  'askd',
  'me',
  'lunch',
  'after',
  'lunch',
  'she',
  'invited',
  'me',
  'to',
  'her',
  'apartment',
  'we',
  'went',
  'there'],
 ['you',
  'are',
  'winner',
  'have',
  'been',
  'specially',
  'selected',
  'receive',
  'or',
  'holiday',
  'flight',
  'inc',
  'speak',
  'to',
  'live',
  'operator',
  'claim',
  'min'],
 ['goodo',
  'yes',
  'we',
  'must',
  'speak',
  'friday',
  'egg',
  'potato',
  'ratio',
  'for',
  'tortilla',
  'needed'],
 ['hmm',
  'my',
  'uncle',
  'just',
  'informed',
  'me',
  'that',
  'he',
  'paying',
  'the',
  'school',
  'directly',
  'so',
  'pls',
  'buy',
  'food'],
 ['private',
  'your',
  'account',
  'statement',
  'for',
  'show',
  'unredeemed',
  'bonus',
  'point',
  'to',
  'claim',
  'call',
  'identifier',
  'code',
  'expires'],
 ['urgent',
  'your',
  'mobile',
  'no',
  'wa',
  'awarded',
  'bonus',
  'caller',
  'prize',
  'on',
  'this',
  'is',
  'our',
  'final',
  'try',
  'to',
  'contact',
  'call',
  'from',
  'landline',
  'box',
  'wr',
  'ppm'],
 ['here',
  'is',
  'my',
  'new',
  'address',
  'apple',
  'pair',
  'all',
  'that',
  'malarky'],
 ['today',
  'voda',
  'number',
  'ending',
  'are',
  'selected',
  'to',
  'receive',
  'award',
  'if',
  'you',
  'have',
  'match',
  'please',
  'call',
  'quoting',
  'claim',
  'code',
  'standard',
  'rate',
  'app'],
 ['am',
  'going',
  'to',
  'sao',
  'mu',
  'today',
  'will',
  'be',
  'done',
  'only',
  'at'],
 ['predict', 'wat', 'time', 'll', 'finish', 'buying'],
 ['good', 'stuff', 'will', 'do'],
 ['just',
  'so',
  'that',
  'you',
  'know',
  'yetunde',
  'hasn',
  'sent',
  'money',
  'yet',
  'just',
  'sent',
  'her',
  'text',
  'not',
  'to',
  'bother',
  'sending',
  'so',
  'it',
  'over',
  'you',
  'dont',
  'have',
  'to',
  'involve',
  'yourself',
  'in',
  'anything',
  'shouldn',
  'have',
  'imposed',
  'anything',
  'on',
  'you',
  'in',
  'the',
  'first',
  'place',
  'so',
  'for',
  'that',
  'apologise'],
 ['are', 'you', 'there', 'in', 'room'],
 ['hey',
  'girl',
  'how',
  'hope',
  'well',
  'me',
  'an',
  'del',
  'bak',
  'again',
  'long',
  'time',
  'no',
  'give',
  'me',
  'call',
  'sum',
  'time',
  'from',
  'lucyxx'],
 ['how', 'much', 'doe', 'it', 'cost'],
 ['home'],
 ['dear', 'will', 'call', 'tmorrow', 'pls', 'accomodate'],
 ['first', 'answer', 'my', 'question'],
 ['sunshine',
  'quiz',
  'wkly',
  'win',
  'top',
  'sony',
  'dvd',
  'player',
  'if',
  'know',
  'which',
  'country',
  'the',
  'algarve',
  'is',
  'in',
  'txt',
  'ansr',
  'to',
  'sp',
  'tyrone'],
 ['want',
  'get',
  'laid',
  'tonight',
  'want',
  'real',
  'dogging',
  'location',
  'sent',
  'direct',
  'ur',

In [198]:
import gensim
model = gensim.models.Word2Vec(words)

In [212]:
matter.shape

(5572, 2)

In [214]:
X_arr.shape

(5569, 100)

In [199]:
## Getting all the vocabulary
model.wv.index_to_key

['to',
 'you',
 'the',
 'and',
 'it',
 'in',
 'is',
 'me',
 'my',
 'for',
 'your',
 'call',
 'of',
 'that',
 'have',
 'on',
 'now',
 'are',
 'can',
 'so',
 'but',
 'not',
 'or',
 'we',
 'do',
 'get',
 'at',
 'ur',
 'if',
 'will',
 'be',
 'with',
 'no',
 'just',
 'this',
 'gt',
 'lt',
 'go',
 'how',
 'up',
 'when',
 'day',
 'ok',
 'what',
 'free',
 'from',
 'all',
 'out',
 'know',
 'll',
 'come',
 'like',
 'good',
 'time',
 'am',
 'then',
 'got',
 'wa',
 'there',
 'he',
 'love',
 'text',
 'only',
 'want',
 'send',
 'one',
 'need',
 'txt',
 'today',
 'by',
 'going',
 'don',
 'stop',
 'she',
 'home',
 'about',
 'lor',
 'sorry',
 'see',
 'still',
 'mobile',
 'take',
 'back',
 'da',
 'reply',
 'dont',
 'our',
 'think',
 'tell',
 'week',
 'phone',
 'hi',
 'new',
 'they',
 'later',
 'please',
 'any',
 'pls',
 'her',
 'ha',
 'did',
 'co',
 'msg',
 'been',
 'min',
 'an',
 'some',
 'dear',
 'night',
 'make',
 'who',
 'here',
 'message',
 'well',
 'say',
 'where',
 're',
 'thing',
 'much',
 'hope',
 'oh',
 'claim',
 'great',
 'hey',
 'him',
 'number',
 'give',
 'more',
 'too',
 'happy',
 'work',
 'friend',
 'wat',
 'had',
 'way',
 'yes',
 'www',
 've',
 'should',
 'let',
 'prize',
 'won',
 'right',
 'tomorrow',
 'already',
 'tone',
 'after',
 'said',
 'ask',
 'win',
 'doing',
 'amp',
 'cash',
 'life',
 'im',
 'yeah',
 'really',
 'babe',
 'why',
 'meet',
 'find',
 'them',
 'miss',
 'very',
 'morning',
 'last',
 'service',
 'year',
 'uk',
 'thanks',
 'care',
 'would',
 'anything',
 'com',
 'also',
 'nokia',
 'lol',
 'every',
 'feel',
 'keep',
 'pick',
 'sure',
 'sent',
 'contact',
 'urgent',
 'over',
 'something',
 'gud',
 'buy',
 'again',
 'before',
 'cant',
 'wait',
 'box',
 'place',
 'first',
 'his',
 'even',
 'guy',
 'someone',
 'help',
 'went',
 'wish',
 'nice',
 'were',
 'next',
 'tonight',
 'off',
 'show',
 'which',
 'soon',
 'word',
 'around',
 'money',
 'could',
 'customer',
 'many',
 'sleep',
 'chat',
 'late',
 'per',
 'ya',
 'sm',
 'always',
 'gonna',
 'wan',
 'leave',
 'down',
 'name',
 'lot',
 'other',
 'pm',
 'end',
 'dun',
 'told',
 'st',
 'person',
 'waiting',
 'special',
 'hello',
 'girl',
 'try',
 'fine',
 'month',
 'hour',
 'may',
 'minute',
 'coming',
 'heart',
 'haha',
 'people',
 'best',
 'th',
 'thk',
 'yet',
 'guaranteed',
 'smile',
 'same',
 'done',
 'getting',
 'god',
 'ppm',
 'thought',
 'use',
 'offer',
 'didn',
 'start',
 'holiday',
 'class',
 'stuff',
 'talk',
 'line',
 'mean',
 'bit',
 'man',
 'live',
 'car',
 'lunch',
 'cost',
 'few',
 'draw',
 'job',
 'finish',
 'problem',
 'never',
 'being',
 'plan',
 'ill',
 'house',
 'hr',
 'better',
 'cool',
 'thats',
 'meeting',
 'trying',
 'yup',
 'mind',
 'having',
 'ready',
 'dat',
 'account',
 'long',
 'pobox',
 'rate',
 'game',
 'weekend',
 'chance',
 'enjoy',
 'wk',
 'real',
 'half',
 'latest',
 'world',
 'than',
 'because',
 'sir',
 'bt',
 'guess',
 'po',
 'yo',
 'check',
 'play',
 'room',
 'pic',
 'voucher',
 'boy',
 'luv',
 'nothing',
 'wanna',
 'awarded',
 'sweet',
 'look',
 'eat',
 'camera',
 'receive',
 'lar',
 'shit',
 'big',
 'liao',
 'another',
 'into',
 'landline',
 'birthday',
 'ah',
 'dinner',
 'xxx',
 'quite',
 'ever',
 'kiss',
 'might',
 'video',
 'jus',
 'age',
 'land',
 'watch',
 'watching',
 'wont',
 'question',
 'probably',
 'orange',
 'two',
 'baby',
 'thanx',
 'called',
 'tv',
 'dream',
 'worry',
 'aight',
 'bed',
 'pa',
 'once',
 'hear',
 'nd',
 'speak',
 'fun',
 'early',
 'point',
 'princess',
 'bad',
 'den',
 'actually',
 'sat',
 'shall',
 'nite',
 'forgot',
 'part',
 'maybe',
 'ringtone',
 'doe',
 'left',
 'bus',
 'pay',
 'remember',
 'network',
 'apply',
 'office',
 'dunno',
 'made',
 'shopping',
 'reach',
 'easy',
 'between',
 'hurt',
 'code',
 'dad',
 'wife',
 'fuck',
 'put',
 'true',
 'didnt',
 'everything',
 'face',
 'leh',
 'evening',
 'little',
 'award',
 'anyway',
 'xx',
 'dis',
 'mate',
 'town',
 'gift',
 'sound',
 'working',
 'those',
 'mail',
 'yr',
 'school',
 'movie',
 'afternoon',
 'looking',
 'thank',
 'enough',
 'selected',
 'while',
 'detail',
 'asked',
 'collect',
 'tmr',
 'missing',
 'without',
 'most',
 'pound',
 'entry',
 'important',
 'hav',
 'xmas',
 'sexy',
 'join',
 'must',
 'price',
 'okay',
 'came',
 'pain',
 'since',
 'wanted',
 'valid',
 'though',
 'wif',
 'until',
 'collection',
 'bring',
 'wot',
 'book',
 'wake',
 'able',
 'til',
 'answer',
 'abt',
 'mob',
 'run',
 'missed',
 'lesson',
 'update',
 'plus',
 'away',
 'de',
 'change',
 'plz',
 'charge',
 'decimal',
 'stay',
 'juz',
 'test',
 'haven',
 'wen',
 'date',
 'colour',
 'attempt',
 'bored',
 'dude',
 'weekly',
 'music',
 'shop',
 'else',
 'havent',
 'hair',
 'double',
 'yesterday',
 'saw',
 'till',
 'alright',
 'lei',
 'goin',
 'online',
 'these',
 'drink',
 'friendship',
 'optout',
 'oso',
 'id',
 'coz',
 'haf',
 'top',
 'food',
 'making',
 'trip',
 'yours',
 'credit',
 'net',
 'family',
 'sch',
 'either',
 'feeling',
 'club',
 'hot',
 'gr',
 'smoke',
 'player',
 'address',
 'driving',
 'yourself',
 'delivery',
 'tried',
 'ard',
 'national',
 'sad',
 'together',
 'lose',
 'sae',
 'beautiful',
 'tot',
 'head',
 'post',
 'calling',
 'full',
 'ring',
 'wid',
 'walk',
 'both',
 'story',
 'si',
 'believe',
 'order',
 'nt',
 'busy',
 'bonus',
 'second',
 'mom',
 'http',
 'brother',
 'await',
 'drive',
 'saying',
 'mum',
 'eve',
 'poly',
 'huh',
 'chikku',
 'row',
 'happen',
 'noe',
 'sleeping',
 'hand',
 'leaving',
 'old',
 'smiling',
 'close',
 'info',
 'set',
 'drop',
 'rite',
 'email',
 'pub',
 'simple',
 'thinking',
 'suite',
 'mths',
 'okie',
 'wil',
 'awesome',
 'parent',
 'match',
 'private',
 'cause',
 'started',
 'finished',
 'took',
 'congrats',
 'tomo',
 'doesn',
 'aft',
 'news',
 'hl',
 'auction',
 'anyone',
 'neva',
 'mine',
 'gd',
 'reason',
 'valentine',
 'sister',
 'card',
 'unsubscribe',
 'angry',
 'company',
 'tc',
 'break',
 'touch',
 'content',
 'everyone',
 'taking',
 'statement',
 'forget',
 'tho',
 'caller',
 'final',
 'available',
 'alone',
 'loving',
 'gal',
 'knw',
 'sun',
 'whatever',
 'opt',
 'dating',
 'choose',
 'found',
 'worth',
 'carlos',
 'bank',
 'fancy',
 'each',
 'whats',
 'open',
 'type',
 'expires',
 'search',
 'ticket',
 'lucky',
 'treat',
 'hows',
 'party',
 'fast',
 'sub',
 'visit',
 'nyt',
 'kind',
 'welcome',
 'bout',
 'mobileupd',
 'far',
 'anytime',
 'congratulation',
 'secret',
 'gbp',
 'exam',
 'college',
 'boytoy',
 'frnd',
 'hard',
 'ltd',
 'ni',
 'quiz',
 'identifier',
 'uncle',
 'friday',
 'happened',
 'hit',
 'gone',
 'prob',
 'song',
 'decided',
 'saturday',
 'smth',
 'wonderful',
 'winner',
 'chennai',
 'least',
 'wrong',
 'lovely',
 'wonder',
 'drug',
 'sea',
 'pretty',
 'fri',
 'outside',
 'nope',
 'term',
 'fucking',
 'project',
 'light',
 'read',
 'hold',
 'tel',
 'oredi',
 'goodmorning',
 'darlin',
 'mrng',
 'finally',
 'wit',
 'mu',
 'operator',
 'used',
 'camcorder',
 'crazy',
 'wasn',
 'support',
 'earlier',
 'snow',
 'listen',
 'savamob',
 'frm',
 'cum',
 'ten',
 'jay',
 'fone',
 'blue',
 'unlimited',
 'cd',
 'fr',
 'meant',
 'case',
 'course',
 'log',
 'their',
 'hmm',
 'isn',
 'frnds',
 'whole',
 'telling',
 'seeing',
 'hungry',
 'wq',
 'sunday',
 'freemsg',
 'wkly',
 'father',
 'gas',
 'john',
 'enter',
 'luck',
 'film',
 'na',
 'gn',
 'knew',
 'understand',
 'store',
 'mayb',
 'sell',
 'sex',
 'paper',
 'area',
 'happiness',
 'yar',
 'un',
 'within',
 'park',
 'sk',
 'india',
 'as',
 'rock',
 'couple',
 'talking',
 'motorola',
 'moment',
 'currently',
 'ago',
 'txts',
 'reading',
 'christmas',
 'lost',
 'bslvyl',
 'die',
 'stupid',
 'single',
 'dnt',
 'side',
 'march',
 'balance',
 'mr',
 'hmmm',
 'joy',
 'tired',
 'invited',
 'felt',
 'mah',
 'computer',
 'load',
 'download',
 'hee',
 'cut',
 'move',
 'etc',
 'pas',
 'almost',
 'child',
 'eh',
 'valued',
 'press',
 'difficult',
 'grin',
 'surprise',
 'information',
 'heard',
 'photo',
 'sort',
 'extra',
 'ugh',
 'picking',
 'eye',
 'xy',
 'darren',
 'kid',
 'gym',
 'through',
 'max',
 'redeemed',
 'lady',
 'ipod',
 'doin',
 'supposed',
 'rental',
 'seen',
 'met',
 'ish',
 'figure',
 'via',
 'return',
 'ge',
 'swing',
 'laptop',
 'reveal',
 'bcoz',
 'semester',
 'bill',
 'direct',
 'sending',
 'askd',
 'shower',
 'gotta',
 'complimentary',
 'correct',
 'red',
 'ac',
 'wow',
 'hospital',
 'confirm',
 'charged',
 'promise',
 'comp',
 'police',
 'slowly',
 'loved',
 'fact',
 'fantasy',
 'nobody',
 'truth',
 'asap',
 'whenever',
 'idea',
 'laugh',
 'noon',
 'train',
 'door',
 'clean',
 'blood',
 'member',
 'rent',
 'monday',
 'remove',
 'asking',
 'yep',
 'slow',
 'discount',
 'hg',
 'ex',
 'weed',
 'small',
 'pete',
 'rest',
 'somebody',
 'hmv',
 'leaf',
 'wana',
 'own',
 'lover',
 'road',
 'study',
 'kate',
 'orchard',
 'bath',
 'muz',
 'safe',
 'wine',
 'lovable',
 'txting',
 'dogging',
 'entered',
 'page',
 'loan',
 'save',
 'rply',
 'checking',
 'joke',
 'crave',
 'abiola',
 'cheer',
 'comin',
 'eg',
 'link',
 'wap',
 'reward',
 'request',
 'usf',
 'std',
 'empty',
 'med',
 'hw',
 'cover',
 'write',
 'bb',
 'ringtones',
 'energy',
 'doctor',
 'convey',
 'rd',
 'sale',
 'cr',
 'ntt',
 'otherwise',
 'poor',
 'gettin',
 'bag',
 'getzed',
 'summer',
 'wishing',
 'glad',
 'fantastic',
 'gap',
 'king',
 'ho',
 'indian',
 'em',
 'cheap',
 'warm',
 'across',
 'hoping',
 'less',
 'opinion',
 'near',
 'water',
 'different',
 'booked',
 'wc',
 'ldn',
 'voice',
 'mm',
 'mistake',
 'woke',
 'rakhesh',
 'custcare',
 'immediately',
 'merry',
 'normal',
 'somewhere',
 'tonite',
 'usual',
 'deep',
 'admirer',
 'kick',
 'street',
 'teach',
 'deal',
 'bathe',
 'spend',
 'pray',
 'sony',
 'del',
 'men',
 'gave',
 'representative',
 'il',
 'short',
 'forever',
 'situation',
 'reached',
 'oops',
 'catch',
 'turn',
 ...]

In [200]:
model.corpus_count

5569

In [201]:
model.wv['happy']

array([-0.306, 0.39, 0.11, 0.13, 0.158, -0.779, 0.187, 0.73, -0.431, -0.125, -0.25, -0.627, 0.0109, 0.123, 0.358, -0.22, 0.191, -0.409, -0.0925, -0.907, 0.324, 0.306, 0.134, -0.313, -0.13, 0.0639, -0.535, -0.343, -0.361, 0.0616, 0.415, 0.00773, 0.139, -0.342, -0.19, 0.619, -0.00218, -0.192, -0.181, -0.54, 0.254, -0.404, -0.253, 0.0566, 0.384, -0.0147, -0.315, -0.0831, 0.168, 0.204, 0.25, -0.296, -0.0612, 0.104, -0.104, 0.27, 0.244, 0.11, -0.44, 0.206, -0.00829, 0.19, -0.0993, -0.222, -0.515, 0.379, 0.135, 0.282, -0.544, 0.493, -0.318, 0.138, 0.486, -0.25, 0.418, 0.219, 0.0394, -0.196, -0.27, 0.0455, -0.176, -0.00277, -0.302, 0.549, -0.174, 0.0612, 0.0676, 0.315, 0.633, -0.0351, 0.475, 0.218, 0.0455, 0.215, 0.522, 0.504, 0.162, -0.305, 0.234, -0.145], dtype=float32)

In [202]:
model.wv['happy'].shape

(100,)

In [203]:
words[1]

['ok', 'lar', 'joking', 'wif', 'oni']

In [204]:
def avg_word2vec(doc):
  vectors = [model.wv[word] for word in doc if word in model.wv]

  if len(vectors) == 0:
    return np.zeros(model.vector_size)

  return np.mean(vectors, axis=0)

In [181]:
!pip install tqdm

Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (4.67.3)

In [205]:
from tqdm import tqdm
X = [avg_word2vec(doc) for doc in words]

In [206]:
X

[array([-0.185, 0.266, 0.0677, 0.0994, 0.0757, -0.531, 0.137, 0.484, -0.3, -0.0954, -0.17, -0.419, -0.00805, 0.0759, 0.229, -0.144, 0.115, -0.271, -0.0436, -0.591, 0.198, 0.197, 0.0849, -0.194, -0.0864, 0.0365, -0.391, -0.23, -0.246, 0.0339, 0.287, -0.00266, 0.1, -0.244, -0.12, 0.413, 0.00404, -0.142, -0.129, -0.365, 0.151, -0.275, -0.174, 0.0274, 0.258, -0.00861, -0.212, -0.0581, 0.127, 0.141, 0.168, -0.21, -0.0475, 0.0781, -0.0988, 0.183, 0.172, 0.0707, -0.3, 0.149, -0.00184, 0.129, -0.0635, -0.138, -0.338, 0.259, 0.0819, 0.183, -0.36, 0.321, -0.219, 0.124, 0.319, -0.18, 0.302, 0.158, 0.0106, -0.125, -0.183, 0.0361, -0.122, -0.0204, -0.221, 0.381, -0.138, 0.0268, 0.056, 0.214, 0.397, -0.0269, 0.288, 0.14, 0.0308, 0.143, 0.358, 0.312, 0.0882, -0.194, 0.153, -0.102], dtype=float32),
 array([-0.161, 0.235, 0.0576, 0.0939, 0.0633, -0.483, 0.114, 0.435, -0.258, -0.0699, -0.151, -0.368, -0.0118, 0.0591, 0.205, -0.137, 0.108, -0.246, -0.036, -0.521, 0.179, 0.17, 0.0702, -0.175, -0.078, 0.0282, -0.349, -0.212, -0.217, 0.0278, 0.256, -0.000725, 0.0895, -0.211, -0.104, 0.36, -0.00677, -0.127, -0.112, -0.331, 0.138, -0.25, -0.159, 0.0269, 0.225, -0.0106, -0.199, -0.0521, 0.115, 0.132, 0.144, -0.18, -0.0447, 0.0804, -0.094, 0.174, 0.157, 0.0645, -0.267, 0.134, 0.00426, 0.119, -0.058, -0.115, -0.3, 0.232, 0.0677, 0.165, -0.321, 0.294, -0.193, 0.11, 0.284, -0.164, 0.271, 0.134, 0.00149, -0.11, -0.162, 0.0216, -0.102, -0.0153, -0.197, 0.338, -0.128, 0.0257, 0.0534, 0.191, 0.346, -0.0275, 0.255, 0.12, 0.0233, 0.124, 0.313, 0.268, 0.0737, -0.179, 0.13, -0.0889], dtype=float32),
 array([-0.181, 0.281, 0.0902, 0.128, 0.0762, -0.586, 0.136, 0.489, -0.318, -0.113, -0.186, -0.451, -0.03, 0.0663, 0.23, -0.161, 0.122, -0.305, -0.071, -0.607, 0.176, 0.225, 0.0793, -0.226, -0.0642, 0.062, -0.415, -0.215, -0.245, 0.0415, 0.281, -0.00116, 0.103, -0.242, -0.116, 0.453, 0.041, -0.19, -0.138, -0.386, 0.13, -0.313, -0.196, 0.0019, 0.262, -0.0227, -0.228, -0.0411, 0.145, 0.121, 0.144, -0.255, -0.0248, 0.106, -0.115, 0.199, 0.157, 0.0606, -0.307, 0.179, 0.000356, 0.112, -0.0324, -0.164, -0.346, 0.264, 0.0731, 0.211, -0.365, 0.346, -0.265, 0.168, 0.327, -0.222, 0.306, 0.183, 0.0321, -0.139, -0.179, 0.00975, -0.112, -0.0256, -0.235, 0.397, -0.112, 0.0344, 0.0278, 0.19, 0.417, -0.00846, 0.28, 0.151, 0.0174, 0.147, 0.384, 0.302, 0.0652, -0.225, 0.187, -0.113], dtype=float32),
 array([-0.252, 0.365, 0.0856, 0.139, 0.0991, -0.721, 0.184, 0.664, -0.411, -0.118, -0.233, -0.568, 0.00164, 0.101, 0.313, -0.198, 0.162, -0.374, -0.0495, -0.811, 0.281, 0.269, 0.114, -0.261, -0.123, 0.0439, -0.533, -0.328, -0.332, 0.0417, 0.389, 0.00229, 0.137, -0.323, -0.163, 0.557, -0.0142, -0.185, -0.174, -0.499, 0.221, -0.369, -0.235, 0.0495, 0.353, -0.0094, -0.291, -0.0864, 0.174, 0.195, 0.221, -0.275, -0.0748, 0.107, -0.133, 0.254, 0.238, 0.103, -0.407, 0.205, 0.00759, 0.187, -0.0949, -0.17, -0.459, 0.362, 0.106, 0.242, -0.492, 0.444, -0.291, 0.161, 0.435, -0.241, 0.41, 0.204, 0.0052, -0.169, -0.249, 0.0447, -0.161, -0.0278, -0.302, 0.517, -0.198, 0.0394, 0.091, 0.3, 0.536, -0.0457, 0.391, 0.183, 0.0352, 0.196, 0.472, 0.425, 0.117, -0.271, 0.199, -0.128], dtype=float32),
 array([-0.221, 0.303, 0.0793, 0.111, 0.0977, -0.604, 0.149, 0.563, -0.345, -0.11, -0.197, -0.48, -0.0033, 0.0852, 0.265, -0.169, 0.144, -0.319, -0.0422, -0.688, 0.238, 0.223, 0.0985, -0.218, -0.0938, 0.0405, -0.446, -0.263, -0.285, 0.0407, 0.335, 0.00226, 0.117, -0.277, -0.144, 0.47, -0.00127, -0.156, -0.133, -0.419, 0.186, -0.323, -0.199, 0.0467, 0.291, 0.00209, -0.243, -0.0807, 0.131, 0.169, 0.183, -0.235, -0.06, 0.0963, -0.107, 0.215, 0.194, 0.0876, -0.342, 0.179, 0.0111, 0.152, -0.0807, -0.141, -0.386, 0.299, 0.0885, 0.204, -0.398, 0.371, -0.243, 0.133, 0.367, -0.205, 0.344, 0.158, -0.00493, -0.141, -0.203, 0.0298, -0.133, -0.0158, -0.252, 0.439, -0.158, 0.0497, 0.0863, 0.25, 0.45, -0.0381, 0.339, 0.147, 0.032, 0.164, 0.393, 0.361, 0.0955, -0.236, 0.167, -0.118], dtype=float32),
 array([-0.232, 0.327, 0.0867, 0.125, 0.101, -0.657, 0.161, 0.594, -0.369, -0.126, -0.209, -0.518, -0.0119, 0.0965, 0.274, -0.177, 0.152, -0.343, -0.0556, -0.725, 0.241, 0.238, 0.103, -0.245, -0.0903, 0.054, -0.473, -0.269, -0.294, 0.0457, 0.349, -0.00138, 0.126, -0.294, -0.145, 0.51, 0.0177, -0.18, -0.15, -0.446, 0.182, -0.349, -0.217, 0.0307, 0.309, -0.00878, -0.261, -0.0726, 0.149, 0.164, 0.194, -0.264, -0.0509, 0.102, -0.118, 0.231, 0.201, 0.084, -0.364, 0.196, 0.00577, 0.148, -0.0701, -0.162, -0.409, 0.315, 0.0932, 0.226, -0.427, 0.401, -0.277, 0.155, 0.389, -0.226, 0.367, 0.18, 0.00958, -0.151, -0.208, 0.0256, -0.144, -0.0188, -0.27, 0.465, -0.156, 0.0445, 0.0768, 0.253, 0.489, -0.0281, 0.352, 0.166, 0.0342, 0.171, 0.428, 0.378, 0.0947, -0.25, 0.195, -0.123], dtype=float32),
 array([-0.246, 0.342, 0.0918, 0.127, 0.109, -0.679, 0.164, 0.63, -0.39, -0.126, -0.218, -0.535, 0.00217, 0.105, 0.295, -0.188, 0.16, -0.354, -0.0532, -0.77, 0.262, 0.251, 0.111, -0.253, -0.103, 0.0505, -0.502, -0.291, -0.314, 0.0486, 0.371, 0.00238, 0.136, -0.311, -0.161, 0.535, 0.00149, -0.175, -0.156, -0.473, 0.202, -0.361, -0.225, 0.0414, 0.331, -0.00389, -0.274, -0.085, 0.152, 0.183, 0.206, -0.267, -0.0671, 0.102, -0.123, 0.241, 0.213, 0.0913, -0.383, 0.197, 0.0098, 0.167, -0.0857, -0.159, -0.433, 0.335, 0.099, 0.234, -0.453, 0.42, -0.281, 0.155, 0.415, -0.229, 0.385, 0.179, 0.00424, -0.162, -0.222, 0.0386, -0.154, -0.0247, -0.282, 0.494, -0.175, 0.0473, 0.0917, 0.278, 0.514, -0.0356, 0.379, 0.17, 0.0337, 0.181, 0.447, 0.406, 0.106, -0.262, 0.195, -0.131], dtype=float32),
 array([-0.169, 0.267, 0.0752, 0.108, 0.065, -0.53, 0.127, 0.462, -0.295, -0.105, -0.163, -0.422, -0.00882, 0.0708, 0.218, -0.141, 0.111, -0.276, -0.052, -0.57, 0.179, 0.196, 0.0775, -0.203, -0.0699, 0.0558, -0.376, -0.208, -0.233, 0.0328, 0.272, -0.00452, 0.101, -0.229, -0.119, 0.419, 0.0307, -0.16, -0.133, -0.357, 0.125, -0.277, -0.178, 0.00603, 0.242, -0.0127, -0.21, -0.046, 0.127, 0.126, 0.155, -0.224, -0.0422, 0.0751, -0.0905, 0.182, 0.142, 0.0627, -0.285, 0.153, -0.015, 0.108, -0.046, -0.15, -0.332, 0.246, 0.0661, 0.178, -0.344, 0.323, -0.224, 0.142, 0.303, -0.188, 0.29, 0.169, 0.0322, -0.138, -0.166, 0.0305, -0.112, -0.0212, -0.215, 0.374, -0.12, 0.0277, 0.0324, 0.191, 0.398, -0.015, 0.271, 0.141, 0.0259, 0.135, 0.349, 0.286, 0.0781, -0.194, 0.169, -0.107], dtype=float32),
 array([-0.202, 0.304, 0.11, 0.138, 0.0878, -0.629, 0.155, 0.52, -0.337, -0.136, -0.202, -0.487, -0.0352, 0.0775, 0.251, -0.174, 0.127, -0.328, -0.0846, -0.651, 0.194, 0.228, 0.0849, -0.247, -0.0788, 0.067, -0.438, -0.222, -0.249, 0.0485, 0.315, -0.00745, 0.105, -0.249, -0.136, 0.473, 0.0533, -0.202, -0.15, -0.414, 0.156, -0.34, -0.197, 0.0111, 0.275, -0.0173, -0.239, -0.0467, 0.148, 0.125, 0.176, -0.287, -0.0287, 0.108, -0.125, 0.212, 0.174, 0.0714, -0.332, 0.197, -0.0155, 0.113, -0.0405, -0.183, -0.372, 0.28, 0.0882, 0.215, -0.387, 0.374, -0.286, 0.172, 0.343, -0.231, 0.323, 0.193, 0.0452, -0.152, -0.188, 0.0104, -0.125, -0.0196, -0.252, 0.422, -0.106, 0.0474, 0.0309, 0.198, 0.449, -0.0274, 0.304, 0.151, 0.00721, 0.136, 0.416, 0.312, 0.0629, -0.25, 0.207, -0.107], dtype=float32),
 array([-0.221, 0.352, 0.12, 0.167, 0.0932, -0.729, 0.161, 0.602, -0.392, -0.144, -0.237, -0.569, -0.0422, 0.0826, 0.293, -0.196, 0.144, -0.381, -0.088, -0.745, 0.206, 0.279, 0.0962, -0.284, -0.0697, 0.0817, -0.511, -0.253, -0.297, 0.0537, 0.349, -0.0117, 0.126, -0.284, -0.148, 0.569, 0.0686, -0.251, -0.18, -0.478, 0.155, -0.388, -0.249, -0.0111, 0.318, -0.0296, -0.289, -0.0462, 0.181, 0.145, 0.186, -0.336, -0.0247, 0.124, -0.143, 0.245, 0.182, 0.0725, -0.372, 0.222, -0.0102, 0.124, -0.0301, -0.21, -0.435, 0.323, 0.0925, 0.261, -0.454, 0.443, -0.327, 0.22, 0.401, -0.282, 0.376, 0.247, 0.0584, -0.18, -0.22, 0.0208, -0.139, -0.0332, -0.291, 0.499, -0.133, 0.0378, 0.0169, 0.224, 0.525, -0.0106, 0.35, 0.194, 0.0204, 0.178, 0.488, 0.361, 0.0794, -0.273, 0.234, -0.141], dtype=float32),
 array([-0.232, 0.315, 0.0799, 0.114, 0.102, -0.632, 0.151, 0.584, -0.353, -0.12, -0.203, -0.499, -0.00405, 0.093, 0.272, -0.178, 0.15, -0.335, -0.05, -0.711, 0.243, 0.229, 0.0981, -0.235, -0.0955, 0.0477, -0.457, -0.265, -0.286, 0.0482, 0.345, 0.00149, 0.119, -0.286, -0.146, 0.49, 0.00997, -0.168, -0.137, -0.434, 0.186, -0.338, -0.209, 0.0387, 0.299, -0.000634, -0.248, -0.0805, 0.139, 0.168, 0.194, -0.249, -0.0562, 0.101, -0.108, 0.227, 0.203, 0.0836, -0.353, 0.187, 0.00829, 0.149, -0.0766, -0.15, -0.399, 0.309, 0.0943, 0.212, -0.413, 0.387, -0.261, 0.137, 0.382, -0.21, 0.354, 0.171, 0.00153, -0.145, -0.205, 0.0291, -0.141, -0.0157, -0.26, 0.453, -0.156, 0.047, 0.0817, 0.255, 0.477, -0.0307, 0.353, 0.155, 0.0356, 0.163, 0.413, 0.374, 0.0972, -0.244, 0.182, -0.119], dtype=float32),
 array([-0.23, 0.334, 0.108, 0.151, 0.102, -0.702, 0.162, 0.588, -0.382, -0.136, -0.224, -0.54, -0.0282, 0.0846, 0.28, -0.194, 0.153, -0.366, -0.0899, -0.731, 0.217, 0.267, 0.0934, -0.271, -0.0739, 0.0724, -0.49, -0.255, -0.296, 0.0538, 0.342, -0.00277, 0.122, -0.286, -0.144, 0.539, 0.0465, -0.227, -0.162, -0.463, 0.163, -0.377, -0.227, 0.00593, 0.311, -0.0228, -0.276, -0.0522, 0.165, 0.143, 0.178, -0.306, -0.0311, 0.123, -0.136, 0.237, 0.194, 0.0769, -0.369, 0.217, -0.0013, 0.134, -0.0437, -0.193, -0.415, 0.315, 0.0902, 0.252, -0.434, 0.418, -0.316, 0.191, 0.386, -0.264, 0.362, 0.207, 0.0405, -0.162, -0.216, 0.00655, -0.135, -0.0272, -0.28, 0.475, -0.129, 0.0484, 0.0393, 0.23, 0.501, -0.0184, 0.342, 0.178, 0.0176, 0.176, 0.452, 0.363, 0.0795, -0.278, 0.228, -0.132], dtype=float32),
 array([-0.239, 0.351, 0.122, 0.156, 0.104, -0.723, 0.173, 0.6, -0.391, -0.144, -0.233, -0.564, -0.0402, 0.0815, 0.292, -0.194, 0.153, -0.38, -0.0914, -0.749, 0.214, 0.274, 0.0966, -0.284, -0.082, 0.0801, -0.507, -0.258, -0.293, 0.0555, 0.361, -0.0116, 0.122, -0.289, -0.151, 0.554, 0.0603, -0.233, -0.163, -0.48, 0.177, -0.397, -0.235, 0.00758, 0.319, -0.0196, -0.282, -0.0534, 0.17, 0.142, 0.195, -0.328, -0.0295, 0.124, -0.145, 0.247, 0.204, 0.0772, -0.387, 0.224, -0.0114, 0.13, -0.0343, -0.203, -0.433, 0.321, 0.0962, 0.255, -0.445, 0.43, -0.329, 0.197, 0.402, -0.269, 0.374, 0.221, 0.0466, -0.17, -0.222, 0.0102, -0.141, -0.0265, -0.286, 0.492, -0.124, 0.0541, 0.037, 0.233, 0.521, -0.0258, 0.35, 0.184, 0.0197, 0.171, 0.477, 0.368, 0.0825, -0.285, 0.236, -0.127], dtype=float32),
 array([-0.236, 0.322, 0.0844, 0.121, 0.102, -0.64, 0.155, 0.586, -0.363, -0.124, -0.201, -0.514, -0.000869, 0.096, 0.272, -0.174, 0.152, -0.339, -0.0563, -0.711, 0.24, 0.236, 0.0992, -0.244, -0.0905, 0.0548, -0.46, -0.262, -0.289, 0.0445, 0.346, -0.000556, 0.12, -0.285, -0.147, 0.504, 0.0205, -0.174, -0.142, -0.435, 0.181, -0.338, -0.212, 0.0308, 0.299, 0.00116, -0.258, -0.0736, 0.143, 0.164, 0.201, -0.258, -0.0537, 0.0941, -0.109, 0.226, 0.195, 0.0844, -0.353, 0.189, -0.00464, 0.142, -0.0687, -0.163, -0.409, 0.306, 0.091, 0.214, -0.419, 0.393, -0.264, 0.146, 0.383, -0.214, 0.357, 0.175, 0.0177, -0.153, -0.204, 0.0334, -0.147, -0.0136, -0.258, 0.456, -0.153, 0.0451, 0.0724, 0.252, 0.489, -0.0293, 0.351, 0.164, 0.0356, 0.167, 0.42, 0.375, 0.102, -0.243, 0.194, -0.121], dtype=float32),
 array([-0.219, 0.312, 0.0879, 0.121, 0.0959, -0.626, 0.15, 0.554, -0.349, -0.117, -0.203, -0.502, -0.0116, 0.0901, 0.261, -0.173, 0.139, -0.331, -0.0591, -0.683, 0.223, 0.236, 0.0907, -0.24, -0.0847, 0.056, -0.454, -0.248, -0.276, 0.0427, 0.319, -0.00337, 0.111, -0.27, -0.143, 0.491, 0.0282, -0.182, -0.148, -0.42, 0.171, -0.334, -0.202, 0.0329, 0.298, -0.0024, -0.26, -0.0648, 0.147, 0.148, 0.192, -0.258, -0.0445, 0.0919, -0.115, 0.214, 0.19, 0.0809, -0.338, 0.184, -0.00147, 0.13, -0.0617, -0.162, -0.389, 0.296, 0.0858, 0.218, -0.412, 0.39, -0.265, 0.154, 0.37, -0.222, 0.344, 0.188, 0.0281, -0.15, -0.198, 0.0343, -0.145, -0.0241, -0.257, 0.445, -0.145, 0.0435, 0.0564, 0.238, 0.474, -0.0213, 0.341, 0.164, 0.0272, 0.161, 0.415, 0.357, 0.094, -0.23, 0.19, -0.117], dtype=float32),
 array([-0.19, 0.287, 0.0867, 0.118, 0.0824, -0.589, 0.139, 0.508, -0.328, -0.112, -0.186, -0.463, -0.0166, 0.0732, 0.246, -0.156, 0.126, -0.308, -0.063, -0.626, 0.189, 0.221, 0.0838, -0.226, -0.075, 0.0561, -0.419, -0.226, -0.257, 0.0407, 0.299, -0.00801, 0.108, -0.252, -0.127, 0.462, 0.032, -0.181, -0.143, -0.396, 0.142, -0.314, -0.199, 0.0115, 0.274, -0.0171, -0.232, -0.051, 0.142, 0.132, 0.164, -0.251, -0.0397, 0.0973, -0.113, 0.202, 0.171, 0.0678, -0.318, 0.17, -0.00642, 0.12, -0.0441, -0.159, -0.363, 0.275, 0.0798, 0.209, -0.379, 0.354, -0.255, 0.161, 0.339, -0.212, 0.313, 0.184, 0.0317, -0.143, -0.19, 0.0249, -0.121, -0.025, -0.235, 0.414, -0.127, 0.0315, 0.0395, 0.209, 0.433, -0.0159, 0.293, 0.159, 0.0259, 0.15, 0.393, 0.321, 0.0835, -0.219, 0.184, -0.115], dtype=float32),
 array([-0.211, 0.315, 0.0756, 0.116, 0.0957, -0.625, 0.158, 0.571, -0.35, -0.107, -0.194, -0.499, 0.0001, 0.0903, 0.274, -0.17, 0.144, -0.327, -0.0401, -0.698, 0.242, 0.229, 0.0991, -0.226, -0.0987, 0.0309, -0.455, -0.278, -0.296, 0.0401, 0.341, 0.00146, 0.117, -0.288, -0.146, 0.487, -0.000228, -0.168, -0.144, -0.432, 0.183, -0.32, -0.213, 0.0355, 0.304, -0.00288, -0.251, -0.0711, 0.145, 0.174, 0.207, -0.243, -0.0709, 0.096, -0.115, 0.223, 0.202, 0.0896, -0.356, 0.176, -0.000363, 0.159, -0.0849, -0.159, -0.408, 0.307, 0.0956, 0.208, -0.427, 0.382, -0.241, 0.145, 0.376, -0.207, 0.356, 0.175, 0.0102, -0.156, -0.216, 0.0457, -0.14, -0.026, -0.263, 0.459, -0.17, 0.0377, 0.0747, 0.263, 0.474, -0.0325, 0.343, 0.168, 0.035, 0.171, 0.415, 0.373, 0.108, -0.227, 0.181, -0.117], dtype=float32),
 array([-0.195, 0.261, 0.0688, 0.0961, 0.081, -0.519, 0.126, 0.477, -0.296, -0.0952, -0.171, -0.41, -0.00122, 0.0725, 0.226, -0.147, 0.122, -0.273, -0.0341, -0.586, 0.204, 0.194, 0.083, -0.189, -0.0798, 0.037, -0.38, -0.225, -0.239, 0.0337, 0.288, 0.00461, 0.0984, -0.236, -0.12, 0.409, -0.0018, -0.134, -0.113, -0.362, 0.159, -0.278, -0.171, 0.0371, 0.249, 0.00168, -0.21, -0.0695, 0.115, 0.143, 0.162, -0.204, -0.0485, 0.0762, -0.0927, 0.187, 0.164, 0.0707, -0.296, 0.151, 0.00545, 0.128, -0.066, -0.124, -0.331, 0.253, 0.0799, 0.176, -0.35, 0.325, -0.209, 0.114, 0.314, -0.173, 0.295, 0.143, 0.00312, -0.122, -0.173, 0.0295, -0.115, -0.0178, -0.215, 0.374, -0.137, 0.0364, 0.067, 0.215, 0.392, -0.0298, 0.291, 0.128, 0.0291, 0.139, 0.337, 0.314, 0.0849, -0.2, 0.147, -0.097], dtype=float32),
 array([-0.276, 0.358, 0.0814, 0.113, 0.119, -0.692, 0.17, 0.655, -0.4, -0.125, -0.227, -0.552, 0.00788, 0.112, 0.308, -0.19, 0.179, -0.364, -0.0493, -0.804, 0.28, 0.252, 0.121, -0.246, -0.106, 0.0427, -0.507, -0.297, -0.329, 0.0507, 0.398, -0.000762, 0.135, -0.325, -0.17, 0.547, -0.00244, -0.168, -0.154, -0.487, 0.209, -0.37, -0.231, 0.0617, 0.338, 0.00579, -0.288, -0.107, 0.15, 0.195, 0.227, -0.266, -0.079, 0.1, -0.124, 0.243, 0.228, 0.0956, -0.407, 0.202, 0.0102, 0.166, -0.0857, -0.158, -0.456, 0.343, 0.117, 0.233, -0.468, 0.438, -0.272, 0.144, 0.431, -0.221, 0.403, 0.183, -0.000383, -0.159, -0.231, 0.0382, -0.166, -0.0232, -0.284, 0.514, -0.192, 0.0506, 0.111, 0.299, 0.533, -0.0467, 0.408, 0.179, 0.0536, 0.183, 0.457, 0.432, 0.131, -0.263, 0.199, -0.129], dtype=float32),
 array([-0.17, 0.252, 0.0777, 0.112, 0.074, -0.521, 0.123, 0.442, -0.284, -0.0965, -0.164, -0.404, -0.0237, 0.0596, 0.212, -0.14, 0.112, -0.274, -0.061, -0.545, 0.158, 0.201, 0.0714, -0.199, -0.0586, 0.0534, -0.368, -0.194, -0.22, 0.0391, 0.26, -0.00309, 0.093, -0.215, -0.105, 0.401, 0.0321, -0.168, -0.118, -0.348, 0.125, -0.281, -0.173, 0.00732, 0.234, -0.0168, -0.208, -0.0402, 0.121, 0.109, 0.134, -0.224, -0.0263, 0.0913, -0.101, 0.178, 0.149, 0.0565, -0.279, 0.155, -0.000767, 0.104, -0.0339, -0.142, -0.312, 0.236, 0.07, 0.187, -0.322, 0.313, -0.235, 0.143, 0.294, -0.194, 0.271, 0.157, 0.0274, -0.124, -0.158, 0.00552, -0.101, -0.0195, -0.208, 0.354, -0.102, 0.0316, 0.0329, 0.175, 0.375, -0.0104, 0.251, 0.134, 0.0178, 0.133, 0.341, 0.275, 0.0637, -0.201, 0.166, -0.0986], dtype=float32),
 array([-0.264, 0.329, 0.0814, 0.106, 0.116, -0.645, 0.158, 0.613, -0.373, -0.128, -0.209, -0.52, 0.0082, 0.111, 0.283, -0.177, 0.169, -0.335, -0.0416, -0.746, 0.269, 0.229, 0.114, -0.24, -0.0954, 0.0477, -0.467, -0.282, -0.301, 0.0501, 0.373, 0.0122, 0.124, -0.295, -0.153, 0.509, -0.0076, -0.152, -0.13, -0.445, 0.217, -0.349, -0.208, 0.0537, 0.304, 0.014, -0.263, -0.102, 0.131, 0.18, 0.221, -0.252, -0.0655, 0.0919, -0.11, 0.238, 0.217, 0.0958, -0.373, 0.193, 0.00832, 0.158, -0.0891, -0.144, -0.419, 0.316, 0.105, 0.206, -0.427, 0.407, -0.252, 0.115, 0.399, -0.197, 0.371, 0.154, -0.00174, -0.15, -0.205, 0.0368, -0.151, -0.0123, -0.255, 0.466, -0.168, 0.0583, 0.113, 0.274, 0.499, -0.0462, 0.381, 0.154, 0.0395, 0.166, 0.411, 0.408, 0.117, -0.261, 0.177, -0.11], dtype=float32),
 array([-0.222, 0.348, 0.0927, 0.145, 0.0836, -0.692, 0.173, 0.61, -0.382, -0.131, -0.212, -0.544, -0.0132, 0.0957, 0.282, -0.185, 0.139, -0.355, -0.0659, -0.744, 0.241, 0.257, 0.0975, -0.258, -0.0957, 0.0599, -0.498, -0.276, -0.31, 0.0429, 0.349, -0.00203, 0.14, -0.308, -0.155, 0.541, 0.0272, -0.202, -0.176, -0.47, 0.169, -0.362, -0.232, 0.00994, 0.329, -0.0177, -0.277, -0.0595, 0.18, 0.168, 0.206, -0.275, -0.0579, 0.0954, -0.121, 0.229, 0.197, 0.0842, -0.374, 0.188, -0.016, 0.15, -0.0656, -0.199, -0.436, 0.321, 0.0984, 0.236, -0.462, 0.417, -0.285, 0.182, 0.397, -0.247, 0.387, 0.21, 0.0428, -0.175, -0.224, 0.0381, -0.157, -0.0255, -0.287, 0.487, -0.165, 0.0229, 0.0461, 0.252, 0.515, -0.0157, 0.349, 0.186, 0.0403, 0.179, 0.465, 0.384, 0.104, -0.241, 0.217, -0.133], dtype=float32),
 array([-0.213, 0.298, 0.0727, 0.108, 0.0865, -0.59, 0.148, 0.547, -0.331, -0.0986, -0.192, -0.464, -0.00169, 0.0879, 0.257, -0.164, 0.136, -0.308, -0.0399, -0.662, 0.233, 0.215, 0.0926, -0.215, -0.0962, 0.041, -0.434, -0.26, -0.279, 0.038, 0.324, 0.00407, 0.113, -0.264, -0.142, 0.458, -0.00548, -0.151, -0.14, -0.412, 0.177, -0.304, -0.19, 0.0383, 0.284, -0.00587, -0.241, -0.0781, 0.137, 0.164, 0.188, -0.229, -0.0617, 0.0895, -0.106, 0.21, 0.192, 0.0788, -0.335, 0.164, 0.00495, 0.148, -0.0757, -0.141, -0.379, 0.291, 0.0812, 0.199, -0.398, 0.362, -0.234, 0.13, 0.363, -0.194, 0.339, 0.161, 0.00405, -0.135, -0.2, 0.0347, -0.135, -0.02, -0.246, 0.423, -0.158, 0.0317, 0.0784, 0.248, 0.441, -0.0358, 0.331, 0.15, 0.0326, 0.157, 0.387, 0.353, 0.0965, -0.218, 0.167, -0.11], dtype=float32),
 array([-0.214, 0.293, 0.0782, 0.12, 0.0912, -0.599, 0.144, 0.544, -0.334, -0.0895, -0.197, -0.464, -0.0103, 0.0767, 0.258, -0.168, 0.138, -0.314, -0.045, -0.656, 0.217, 0.229, 0.0938, -0.212, -0.0916, 0.0377, -0.444, -0.266, -0.269, 0.0383, 0.32, -0.00188, 0.104, -0.257, -0.136, 0.452, -0.00767, -0.157, -0.134, -0.416, 0.18, -0.31, -0.199, 0.0338, 0.279, -0.00819, -0.245, -0.0674, 0.137, 0.158, 0.176, -0.238, -0.0513, 0.0978, -0.118, 0.213, 0.197, 0.0795, -0.339, 0.17, 0.0024, 0.15, -0.0687, -0.146, -0.38, 0.292, 0.0844, 0.207, -0.4, 0.367, -0.25, 0.134, 0.355, -0.208, 0.33, 0.163, 0.0031, -0.135, -0.212, 0.023, -0.126, -0.026, -0.244, 0.427, -0.155, 0.0381, 0.0629, 0.242, 0.435, -0.0368, 0.321, 0.15, 0.0249, 0.161, 0.39, 0.345, 0.0902, -0.228, 0.169, -0.11], dtype=float32),
 array([-0.261, 0.34, 0.0876, 0.118, 0.118, -0.689, 0.16, 0.637, -0.387, -0.132, -0.217, -0.544, -0.00336, 0.11, 0.298, -0.189, 0.172, -0.368, -0.0512, -0.773, 0.266, 0.248, 0.112, -0.257, -0.102, 0.0542, -0.502, -0.288, -0.303, 0.0562, 0.384, 0.00375, 0.127, -0.307, -0.159, 0.537, 0.00794, -0.176, -0.143, -0.466, 0.213, -0.373, -0.227, 0.0501, 0.317, 0.00788, -0.273, -0.0932, 0.148, 0.182, 0.215, -0.269, -0.0531, 0.113, -0.117, 0.25, 0.221, 0.1, -0.386, 0.213, 0.0118, 0.161, -0.0844, -0.153, -0.432, 0.336, 0.111, 0.227, -0.445, 0.429, -0.282, 0.139, 0.419, -0.226, 0.386, 0.178, -0.006, -0.152, -0.219, 0.03, -0.154, -0.0151, -0.277, 0.488, -0.167, 0.0584, 0.0943, 0.278, 0.519, -0.041, 0.393, 0.164, 0.0371, 0.175, 0.439, 0.408, 0.105, -0.272, 0.193, -0.126], dtype=float32),

In [207]:
len(X)

5569

In [209]:
X_arr = np.array(X)
X_arr

array([[-0.185, 0.266, 0.0677, 0.0994, 0.0757, -0.531, 0.137, 0.484, -0.3, -0.0954, -0.17, -0.419, -0.00805, 0.0759, 0.229, -0.144, 0.115, -0.271, -0.0436, -0.591, 0.198, 0.197, 0.0849, -0.194, -0.0864, 0.0365, -0.391, -0.23, -0.246, 0.0339, ..., -0.219, 0.124, 0.319, -0.18, 0.302, 0.158, 0.0106, -0.125, -0.183, 0.0361, -0.122, -0.0204, -0.221, 0.381, -0.138, 0.0268, 0.056, 0.214, 0.397, -0.0269, 0.288, 0.14, 0.0308, 0.143, 0.358, 0.312, 0.0882, -0.194, 0.153, -0.102],
       [-0.161, 0.235, 0.0576, 0.0939, 0.0633, -0.483, 0.114, 0.435, -0.258, -0.0699, -0.151, -0.368, -0.0118, 0.0591, 0.205, -0.137, 0.108, -0.246, -0.036, -0.521, 0.179, 0.17, 0.0702, -0.175, -0.078, 0.0282, -0.349, -0.212, -0.217, 0.0278, ..., -0.193, 0.11, 0.284, -0.164, 0.271, 0.134, 0.00149, -0.11, -0.162, 0.0216, -0.102, -0.0153, -0.197, 0.338, -0.128, 0.0257, 0.0534, 0.191, 0.346, -0.0275, 0.255, 0.12, 0.0233, 0.124, 0.313, 0.268, 0.0737, -0.179, 0.13, -0.0889],
       [-0.181, 0.281, 0.0902, 0.128, 0.0762, -0.586, 0.136, 0.489, -0.318, -0.113, -0.186, -0.451, -0.03, 0.0663, 0.23, -0.161, 0.122, -0.305, -0.071, -0.607, 0.176, 0.225, 0.0793, -0.226, -0.0642, 0.062, -0.415, -0.215, -0.245, 0.0415, ..., -0.265, 0.168, 0.327, -0.222, 0.306, 0.183, 0.0321, -0.139, -0.179, 0.00975, -0.112, -0.0256, -0.235, 0.397, -0.112, 0.0344, 0.0278, 0.19, 0.417, -0.00846, 0.28, 0.151, 0.0174, 0.147, 0.384, 0.302, 0.0652, -0.225, 0.187, -0.113],
       [-0.252, 0.365, 0.0856, 0.139, 0.0991, -0.721, 0.184, 0.664, -0.411, -0.118, -0.233, -0.568, 0.00164, 0.101, 0.313, -0.198, 0.162, -0.374, -0.0495, -0.811, 0.281, 0.269, 0.114, -0.261, -0.123, 0.0439, -0.533, -0.328, -0.332, 0.0417, ..., -0.291, 0.161, 0.435, -0.241, 0.41, 0.204, 0.0052, -0.169, -0.249, 0.0447, -0.161, -0.0278, -0.302, 0.517, -0.198, 0.0394, 0.091, 0.3, 0.536, -0.0457, 0.391, 0.183, 0.0352, 0.196, 0.472, 0.425, 0.117, -0.271, 0.199, -0.128],
       [-0.221, 0.303, 0.0793, 0.111, 0.0977, -0.604, 0.149, 0.563, -0.345, -0.11, -0.197, -0.48, -0.0033, 0.0852, 0.265, -0.169, 0.144, -0.319, -0.0422, -0.688, 0.238, 0.223, 0.0985, -0.218, -0.0938, 0.0405, -0.446, -0.263, -0.285, 0.0407, ..., -0.243, 0.133, 0.367, -0.205, 0.344, 0.158, -0.00493, -0.141, -0.203, 0.0298, -0.133, -0.0158, -0.252, 0.439, -0.158, 0.0497, 0.0863, 0.25, 0.45, -0.0381, 0.339, 0.147, 0.032, 0.164, 0.393, 0.361, 0.0955, -0.236, 0.167, -0.118],
       [-0.232, 0.327, 0.0867, 0.125, 0.101, -0.657, 0.161, 0.594, -0.369, -0.126, -0.209, -0.518, -0.0119, 0.0965, 0.274, -0.177, 0.152, -0.343, -0.0556, -0.725, 0.241, 0.238, 0.103, -0.245, -0.0903, 0.054, -0.473, -0.269, -0.294, 0.0457, ..., -0.277, 0.155, 0.389, -0.226, 0.367, 0.18, 0.00958, -0.151, -0.208, 0.0256, -0.144, -0.0188, -0.27, 0.465, -0.156, 0.0445, 0.0768, 0.253, 0.489, -0.0281, 0.352, 0.166, 0.0342, 0.171, 0.428, 0.378, 0.0947, -0.25, 0.195, -0.123],
       [-0.246, 0.342, 0.0918, 0.127, 0.109, -0.679, 0.164, 0.63, -0.39, -0.126, -0.218, -0.535, 0.00217, 0.105, 0.295, -0.188, 0.16, -0.354, -0.0532, -0.77, 0.262, 0.251, 0.111, -0.253, -0.103, 0.0505, -0.502, -0.291, -0.314, 0.0486, ..., -0.281, 0.155, 0.415, -0.229, 0.385, 0.179, 0.00424, -0.162, -0.222, 0.0386, -0.154, -0.0247, -0.282, 0.494, -0.175, 0.0473, 0.0917, 0.278, 0.514, -0.0356, 0.379, 0.17, 0.0337, 0.181, 0.447, 0.406, 0.106, -0.262, 0.195, -0.131],
       [-0.169, 0.267, 0.0752, 0.108, 0.065, -0.53, 0.127, 0.462, -0.295, -0.105, -0.163, -0.422, -0.00882, 0.0708, 0.218, -0.141, 0.111, -0.276, -0.052, -0.57, 0.179, 0.196, 0.0775, -0.203, -0.0699, 0.0558, -0.376, -0.208, -0.233, 0.0328, ..., -0.224, 0.142, 0.303, -0.188, 0.29, 0.169, 0.0322, -0.138, -0.166, 0.0305, -0.112, -0.0212, -0.215, 0.374, -0.12, 0.0277, 0.0324, 0.191, 0.398, -0.015, 0.271, 0.141, 0.0259, 0.135, 0.349, 0.286, 0.0781, -0.194, 0.169, -0.107],
       [-0.202, 0.304, 0.11, 0.138, 0.0878, -0.629, 0.155, 0.52, -0.337, -0.136, -0.202, -0.487, -0.0352, 0.0775, 0.251, -0.174, 0.127, -0.328, -0.0846, -0.651, 0.194, 0.228, 0.0849, -0.247, -0.0788, 0.067, -0.438, -0.222, -0.249, 0.0485, ..., -0.286, 0.172, 0.343, -0.231, 0.323, 0.193, 0.0452, -0.152, -0.188, 0.0104, -0.125, -0.0196, -0.252, 0.422, -0.106, 0.0474, 0.0309, 0.198, 0.449, -0.0274, 0.304, 0.151, 0.00721, 0.136, 0.416, 0.312, 0.0629, -0.25, 0.207, -0.107],
       [-0.221, 0.352, 0.12, 0.167, 0.0932, -0.729, 0.161, 0.602, -0.392, -0.144, -0.237, -0.569, -0.0422, 0.0826, 0.293, -0.196, 0.144, -0.381, -0.088, -0.745, 0.206, 0.279, 0.0962, -0.284, -0.0697, 0.0817, -0.511, -0.253, -0.297, 0.0537, ..., -0.327, 0.22, 0.401, -0.282, 0.376, 0.247, 0.0584, -0.18, -0.22, 0.0208, -0.139, -0.0332, -0.291, 0.499, -0.133, 0.0378, 0.0169, 0.224, 0.525, -0.0106, 0.35, 0.194, 0.0204, 0.178, 0.488, 0.361, 0.0794, -0.273, 0.234, -0.141],
       [-0.232, 0.315, 0.0799, 0.114, 0.102, -0.632, 0.151, 0.584, -0.353, -0.12, -0.203, -0.499, -0.00405, 0.093, 0.272, -0.178, 0.15, -0.335, -0.05, -0.711, 0.243, 0.229, 0.0981, -0.235, -0.0955, 0.0477, -0.457, -0.265, -0.286, 0.0482, ..., -0.261, 0.137, 0.382, -0.21, 0.354, 0.171, 0.00153, -0.145, -0.205, 0.0291, -0.141, -0.0157, -0.26, 0.453, -0.156, 0.047, 0.0817, 0.255, 0.477, -0.0307, 0.353, 0.155, 0.0356, 0.163, 0.413, 0.374, 0.0972, -0.244, 0.182, -0.119],
       [-0.23, 0.334, 0.108, 0.151, 0.102, -0.702, 0.162, 0.588, -0.382, -0.136, -0.224, -0.54, -0.0282, 0.0846, 0.28, -0.194, 0.153, -0.366, -0.0899, -0.731, 0.217, 0.267, 0.0934, -0.271, -0.0739, 0.0724, -0.49, -0.255, -0.296, 0.0538, ..., -0.316, 0.191, 0.386, -0.264, 0.362, 0.207, 0.0405, -0.162, -0.216, 0.00655, -0.135, -0.0272, -0.28, 0.475, -0.129, 0.0484, 0.0393, 0.23, 0.501, -0.0184, 0.342, 0.178, 0.0176, 0.176, 0.452, 0.363, 0.0795, -0.278, 0.228, -0.132],
       [-0.239, 0.351, 0.122, 0.156, 0.104, -0.723, 0.173, 0.6, -0.391, -0.144, -0.233, -0.564, -0.0402, 0.0815, 0.292, -0.194, 0.153, -0.38, -0.0914, -0.749, 0.214, 0.274, 0.0966, -0.284, -0.082, 0.0801, -0.507, -0.258, -0.293, 0.0555, ..., -0.329, 0.197, 0.402, -0.269, 0.374, 0.221, 0.0466, -0.17, -0.222, 0.0102, -0.141, -0.0265, -0.286, 0.492, -0.124, 0.0541, 0.037, 0.233, 0.521, -0.0258, 0.35, 0.184, 0.0197, 0.171, 0.477, 0.368, 0.0825, -0.285, 0.236, -0.127],
       [-0.236, 0.322, 0.0844, 0.121, 0.102, -0.64, 0.155, 0.586, -0.363, -0.124, -0.201, -0.514, -0.000869, 0.096, 0.272, -0.174, 0.152, -0.339, -0.0563, -0.711, 0.24, 0.236, 0.0992, -0.244, -0.0905, 0.0548, -0.46, -0.262, -0.289, 0.0445, ..., -0.264, 0.146, 0.383, -0.214, 0.357, 0.175, 0.0177, -0.153, -0.204, 0.0334, -0.147, -0.0136, -0.258, 0.456, -0.153, 0.0451, 0.0724, 0.252, 0.489, -0.0293, 0.351, 0.164, 0.0356, 0.167, 0.42, 0.375, 0.102, -0.243, 0.194, -0.121],
       [-0.219, 0.312, 0.0879, 0.121, 0.0959, -0.626, 0.15, 0.554, -0.349, -0.117, -0.203, -0.502, -0.0116, 0.0901, 0.261, -0.173, 0.139, -0.331, -0.0591, -0.683, 0.223, 0.236, 0.0907, -0.24, -0.0847, 0.056, -0.454, -0.248, -0.276, 0.0427, ..., -0.265, 0.154, 0.37, -0.222, 0.344, 0.188, 0.0281, -0.15, -0.198, 0.0343, -0.145, -0.0241, -0.257, 0.445, -0.145, 0.0435, 0.0564, 0.238, 0.474, -0.0213, 0.341, 0.164, 0.0272, 0.161, 0.415, 0.357, 0.094, -0.23, 0.19, -0.117],
       [-0.19, 0.287, 0.0867, 0.118, 0.0824, -0.589, 0.139, 0.508, -0.328, -0.112, -0.186, -0.463, -0.0166, 0.0732, 0.246, -0.156, 0.126, -0.308, -0.063, -0.626, 0.189, 0.221, 0.0838, -0.226, -0.075, 0.0561, -0.419, -0.226, -0.257, 0.0407, ..., -0.255, 0.161, 0.339, -0.212, 0.313, 0.184, 0.0317, -0.143, -0.19, 0.0249, -0.121, -0.025, -0.235, 0.414, -0.127, 0.0315, 0.0395, 0.209, 0.433, -0.0159, 0.293, 0.159, 0.0259, 0.15, 0.393, 0.321, 0.0835, -0.219, 0.184, -0.115],
       [-0.211, 0.315, 0.0756, 0.116, 0.0957, -0.625, 0.158, 0.571, -0.35, -0.107, -0.194, -0.499, 0.0001, 0.0903, 0.274, -0.17, 0.144, -0.327, -0.0401, -0.698, 0.242, 0.229, 0.0991, -0.226, -0.0987, 0.0309, -0.455, -0.278, -0.296, 0.0401, ..., -0.241, 0.145, 0.376, -0.207, 0.356, 0.175, 0.0102, -0.156, -0.216, 0.0457, -0.14, -0.026, -0.263, 0.459, -0.17, 0.0377, 0.0747, 0.263, 0.474, -0.0325, 0.343, 0.168, 0.035, 0.171, 0.415, 0.373, 0.108, -0.227, 0.181, -0.117],
       [-0.195, 0.261, 0.0688, 0.0961, 0.081, -0.519, 0.126, 0.477, -0.296, -0.0952, -0.171, -0.41, -0.00122, 0.0725, 0.226, -0.147, 0.122, -0.273, -0.0341, -0.586, 0.204, 0.194, 0.083, -0.189, -0.0798, 0.037, -0.38, -0.225, -0.239, 0.0337, ..., -0.209, 0.114, 0.314, -0.173, 0.295, 0.143, 0.00312, -0.122, -0.173, 0.0295, -0.115, -0.0178, -0.215, 0.374, -0.137, 0.0364, 0.067, 0.215, 0.392, -0.0298, 0.291, 0.128, 0.0291, 0.139, 0.337, 0.314, 0.0849, -0.2, 0.147, -0.097],
       [-0.276, 0.358, 0.0814, 0.113, 0.119, -0.692, 0.17, 0.655, -0.4, -0.125, -0.227, -0.552, 0.00788, 0.112, 0.308, -0.19, 0.179, -0.364, -0.0493, -0.804, 0.28, 0.252, 0.121, -0.246, -0.106, 0.0427, -0.507, -0.297, -0.329, 0.0507, ..., -0.272, 0.144, 0.431, -0.221, 0.403, 0.183, -0.000383, -0.159, -0.231, 0.0382, -0.166, -0.0232, -0.284, 0.514, -0.192, 0.0506, 0.111, 0.299, 0.533, -0.0467, 0.408, 0.179, 0.0536, 0.183, 0.457, 0.432, 0.131, -0.263, 0.199, -0.129],
       [-0.17, 0.252, 0.0777, 0.112, 0.074, -0.521, 0.123, 0.442, -0.284, -0.0965, -0.164, -0.404, -0.0237, 0.0596, 0.212, -0.14, 0.112, -0.274, -0.061, -0.545, 0.158, 0.201, 0.0714, -0.199, -0.0586, 0.0534, -0.368, -0.194, -0.22, 0.0391, ..., -0.235, 0.143, 0.294, -0.194, 0.271, 0.157, 0.0274, -0.124, -0.158, 0.00552, -0.101, -0.0195, -0.208, 0.354, -0.102, 0.0316, 0.0329, 0.175, 0.375, -0.0104, 0.251, 0.134, 0.0178, 0.133, 0.341, 0.275, 0.0637, -0.201, 0.166, -0.0986],
       [-0.264, 0.329, 0.0814, 0.106, 0.116, -0.645, 0.158, 0.613, -0.373, -0.128, -0.209, -0.52, 0.0082, 0.111, 0.283, -0.177, 0.169, -0.335, -0.0416, -0.746, 0.269, 0.229, 0.114, -0.24, -0.0954, 0.0477, -0.467, -0.282, -0.301, 0.0501, ..., -0.252, 0.115, 0.399, -0.197, 0.371, 0.154, -0.00174, -0.15, -0.205, 0.0368, -0.151, -0.0123, -0.255, 0.466, -0.168, 0.0583, 0.113, 0.274, 0.499, -0.0462, 0.381, 0.154, 0.0395, 0.166, 0.411, 0.408, 0.117, -0.261, 0.177, -0.11],
       [-0.222, 0.348, 0.0927, 0.145, 0.0836, -0.692, 0.173, 0.61, -0.382, -0.131, -0.212, -0.544, -0.0132, 0.0957, 0.282, -0.185, 0.139, -0.355, -0.0659, -0.744, 0.241, 0.257, 0.0975, -0.258, -0.0957, 0.0599, -0.498, -0.276, -0.31, 0.0429, ..., -0.285, 0.182, 0.397, -0.247, 0.387, 0.21, 0.0428, -0.175, -0.224, 0.0381, -0.157, -0.0255, -0.287, 0.487, -0.165, 0.0229, 0.0461, 0.252, 0.515, -0.0157, 0.349, 0.186, 0.0403, 0.179, 0.465, 0.384, 0.104, -0.241, 0.217, -0.133],
       [-0.213, 0.298, 0.0727, 0.108, 0.0865, -0.59, 0.148, 0.547, -0.331, -0.0986, -0.192, -0.464, -0.00169, 0.0879, 0.257, -0.164, 0.136, -0.308, -0.0399, -0.662, 0.233, 0.215, 0.0926, -0.215, -0.0962, 0.041, -0.434, -0.26, -0.279, 0.038, ..., -0.234, 0.13, 0.363, -0.194, 0.339, 0.161, 0.00405, -0.135, -0.2, 0.0347, -0.135, -0.02, -0.246, 0.423, -0.158, 0.0317, 0.0784, 0.248, 0.441, -0.0358, 0.331, 0.15, 0.0326, 0.157, 0.387, 0.353, 0.0965, -0.218, 0.167, -0.11],
       [-0.214, 0.293, 0.0782, 0.12, 0.0912, -0.599, 0.144, 0.544, -0.334, -0.0895, -0.197, -0.464, -0.0103, 0.0767, 0.258, -0.168, 0.138, -0.314, -0.045, -0.656, 0.217, 0.229, 0.0938, -0.212, -0.0916, 0.0377, -0.444, -0.266, -0.269, 0.0383, ..., -0.25, 0.134, 0.355, -0.208, 0.33, 0.163, 0.0031, -0.135, -0.212, 0.023, -0.126, -0.026, -0.244, 0.427, -0.155, 0.0381, 0.0629, 0.242, 0.435, -0.0368, 0.321, 0.15, 0.0249, 0.161, 0.39, 0.345, 0.0902, -0.228, 0.169, -0.11],
       [-0.261, 0.34, 0.0876, 0.118, 0.118, -0.689, 0.16, 0.637, -0.387, -0.132, -0.217, -0.544, -0.00336, 0.11, 0.298, -0.189, 0.172, -0.368, -0.0512, -0.773, 0.266, 0.248, 0.112, -0.257, -0.102, 0.0542, -0.502, -0.288, -0.303, 0.0562, ..., -0.282, 0.139, 0.419, -0.226, 0.386, 0.178, -0.006, -0.152, -0.219, 0.03, -0.154, -0.0151, -0.277, 0.488, -0.167, 0.0584, 0.0943, 0.278, 0.519, -0.041, 0.393, 0.164, 0.0371, 0.175, 0.439, 0.408, 0.105, -0.272, 0.193, -0.126],
       [-0.176, 0.244, 0.0646, 0.0897, 0.0753, -0.486, 0.115, 0.446, -0.275, -0.0909, -0.157, -0.383, -0.00342, 0.0731, 0.21, -0.136, 0.114, -0.255, -0.038, -0.547, 0.186, 0.176, 0.0789, -0.178, -0.0721, 0.0358, -0.355, -0.208, -0.224, 0.0337, ..., -0.198, 0.11, 0.293, -0.161, 0.275, 0.13, 0.00282, -0.114, -0.156, 0.0241, -0.106, -0.0135, -0.199, 0.352, -0.122, 0.0357, 0.0657, 0.197, 0.367, -0.0265, 0.271, 0.12, 0.028, 0.129, 0.317, 0.291, 0.0753, -0.189, 0.139, -0.0913],
       [-0.256, 0.36, 0.101, 0.139, 0.109, -0.715, 0.17, 0.65, -0.404, -0.139, -0.231, -0.571, -0.00356, 0.094, 0.306, -0.2, 0.165, -0.386, -0.0663, -0.793, 0.26, 0.268, 0.108, -0.269, -0.105, 0.062, -0.52, -0.301, -0.319, 0.056, ..., -0.299, 0.177, 0.425, -0.245, 0.393, 0.209, 0.0261, -0.17, -0.232, 0.0354, -0.152, -0.0255, -0.29, 0.51, -0.171, 0.0507, 0.0719, 0.278, 0.539, -0.0391, 0.392, 0.182, 0.0305, 0.193, 0.47, 0.411, 0.108, -0.28, 0.216, -0.135],
       [-0.246, 0.3, 0.0815, 0.0944, 0.111, -0.588, 0.139, 0.562, -0.337, -0.121, -0.188, -0.472, 0.00688, 0.0991, 0.257, -0.162, 0.157, -0.312, -0.042, -0.678, 0.24, 0.209, 0.098, -0.227, -0.0905, 0.0482, -0.421, -0.25, -0.263, 0.0523, ..., -0.241, 0.101, 0.364, -0.18, 0.328, 0.133, -0.0111, -0.131, -0.179, 0.0306, -0.138, -0.00124, -0.227, 0.415, -0.139, 0.0642, 0.104, 0.244, 0.456, -0.0404, 0.354, 0.135, 0.0322, 0.147, 0.37, 0.366, 0.1, -0.242, 0.165, -0.103],
       [-0.263, 0.361, 0.0919, 0.128, 0.118, -0.713, 0.173, 0.669, -0.405, -0.135, -0.231, -0.566, -0.00428, 0.115, 0.311, -0.196, 0.174, -0.374, -0.056, -0.809, 0.283, 0.249, 0.115, -0.27, -0.113, 0.0488, -0.523, -0.305, -0.324, 0.0522, ..., -0.293, 0.15, 0.441, -0.233, 0.404, 0.187, -0.00158, -0.165, -0.228, 0.0391, -0.163, -0.0168, -0.299, 0.51, -0.18, 0.052, 0.103, 0.296, 0.541, -0.0376, 0.41, 0.177, 0.0376, 0.183, 0.466, 0.431, 0.109, -0.275, 0.2, -0.134],
       [-0.239, 0.321, 0.0724, 0.103, 0.103, -0.624, 0.152, 0.595, -0.358, -0.117, -0.201, -0.496, 0.00217, 0.101, 0.275, -0.168, 0.148, -0.321, -0.0362, -0.723, 0.255, 0.224, 0.105, -0.225, -0.102, 0.0362, -0.46, -0.277, -0.293, 0.0454, ..., -0.247, 0.123, 0.387, -0.196, 0.362, 0.156, -0.00392, -0.145, -0.205, 0.0432, -0.152, -0.0139, -0.256, 0.457, -0.174, 0.046, 0.0996, 0.274, 0.478, -0.0378, 0.362, 0.157, 0.0447, 0.168, 0.414, 0.39, 0.113, -0.235, 0.17, -0.112],
       ...,
       [-0.202, 0.303, 0.087, 0.118, 0.0805, -0.606, 0.145, 0.537, -0.34, -0.117, -0.195, -0.472, -0.0116, 0.0823, 0.249, -0.162, 0.135, -0.315, -0.0604, -0.664, 0.208, 0.224, 0.0906, -0.235, -0.0782, 0.0588, -0.439, -0.24, -0.264, 0.0455, ..., -0.264, 0.16, 0.352, -0.214, 0.331, 0.178, 0.0183, -0.148, -0.191, 0.0263, -0.124, -0.0206, -0.244, 0.426, -0.135, 0.0419, 0.0531, 0.223, 0.445, -0.0205, 0.317, 0.153, 0.0296, 0.154, 0.398, 0.336, 0.0779, -0.236, 0.181, -0.116],
       [-0.181, 0.257, 0.061, 0.0946, 0.0755, -0.511, 0.132, 0.468, -0.282, -0.0825, -0.17, -0.403, -0.00327, 0.0735, 0.219, -0.137, 0.116, -0.267, -0.0343, -0.573, 0.197, 0.189, 0.077, -0.184, -0.0842, 0.0353, -0.372, -0.226, -0.234, 0.0281, ..., -0.21, 0.11, 0.305, -0.17, 0.297, 0.147, 0.0048, -0.118, -0.176, 0.0314, -0.121, -0.0199, -0.212, 0.373, -0.138, 0.0273, 0.0582, 0.211, 0.379, -0.0329, 0.284, 0.132, 0.024, 0.135, 0.339, 0.298, 0.083, -0.188, 0.146, -0.0894],
       [-0.257, 0.354, 0.0915, 0.128, 0.113, -0.701, 0.17, 0.647, -0.396, -0.132, -0.226, -0.553, -0.00721, 0.108, 0.301, -0.192, 0.169, -0.37, -0.0613, -0.783, 0.266, 0.255, 0.111, -0.265, -0.0985, 0.0543, -0.509, -0.291, -0.316, 0.0533, ..., -0.288, 0.157, 0.428, -0.232, 0.393, 0.188, 0.00611, -0.164, -0.221, 0.0354, -0.159, -0.017, -0.287, 0.498, -0.169, 0.0478, 0.0924, 0.281, 0.531, -0.0319, 0.392, 0.175, 0.0392, 0.177, 0.457, 0.418, 0.108, -0.271, 0.204, -0.132],
       [-0.285, 0.385, 0.0961, 0.13, 0.121, -0.751, 0.188, 0.699, -0.427, -0.149, -0.241, -0.609, 0.00338, 0.121, 0.322, -0.207, 0.174, -0.394, -0.0534, -0.851, 0.296, 0.27, 0.122, -0.28, -0.117, 0.0525, -0.536, -0.317, -0.341, 0.0501, ..., -0.3, 0.155, 0.457, -0.239, 0.429, 0.204, 0.00702, -0.178, -0.235, 0.0484, -0.181, -0.0157, -0.306, 0.538, -0.189, 0.0587, 0.106, 0.306, 0.583, -0.0376, 0.43, 0.19, 0.0447, 0.183, 0.484, 0.457, 0.127, -0.287, 0.221, -0.143],
       [-0.258, 0.356, 0.089, 0.124, 0.119, -0.702, 0.181, 0.655, -0.403, -0.126, -0.22, -0.557, 0.00538, 0.11, 0.306, -0.199, 0.166, -0.356, -0.0426, -0.79, 0.282, 0.238, 0.113, -0.264, -0.12, 0.0432, -0.512, -0.316, -0.324, 0.049, ..., -0.277, 0.134, 0.435, -0.22, 0.404, 0.18, -0.0011, -0.155, -0.223, 0.0469, -0.165, -0.011, -0.288, 0.501, -0.188, 0.0485, 0.106, 0.303, 0.539, -0.0365, 0.408, 0.18, 0.04, 0.184, 0.461, 0.427, 0.115, -0.259, 0.193, -0.135],
       [-0.182, 0.305, 0.0934, 0.135, 0.0765, -0.622, 0.145, 0.519, -0.336, -0.12, -0.198, -0.484, -0.0321, 0.0728, 0.251, -0.164, 0.122, -0.321, -0.0698, -0.643, 0.186, 0.236, 0.0836, -0.242, -0.066, 0.0648, -0.441, -0.223, -0.264, 0.0414, ..., -0.275, 0.185, 0.348, -0.236, 0.328, 0.208, 0.0485, -0.159, -0.189, 0.0262, -0.126, -0.0285, -0.257, 0.429, -0.122, 0.0247, 0.018, 0.203, 0.453, -0.00424, 0.299, 0.169, 0.0233, 0.152, 0.414, 0.316, 0.074, -0.22, 0.199, -0.126],
       [-0.254, 0.345, 0.086, 0.121, 0.108, -0.68, 0.169, 0.636, -0.385, -0.122, -0.217, -0.546, -0.00793, 0.103, 0.297, -0.187, 0.16, -0.358, -0.0445, -0.77, 0.261, 0.25, 0.107, -0.247, -0.105, 0.043, -0.5, -0.289, -0.319, 0.0431, ..., -0.276, 0.158, 0.418, -0.233, 0.387, 0.188, 0.0116, -0.166, -0.227, 0.0374, -0.157, -0.0261, -0.283, 0.495, -0.178, 0.0459, 0.0819, 0.281, 0.517, -0.0283, 0.381, 0.171, 0.0391, 0.183, 0.453, 0.411, 0.123, -0.254, 0.202, -0.13],
       [-0.239, 0.316, 0.0771, 0.0991, 0.101, -0.609, 0.149, 0.581, -0.352, -0.111, -0.197, -0.492, 0.011, 0.107, 0.271, -0.163, 0.156, -0.321, -0.039, -0.706, 0.255, 0.214, 0.106, -0.231, -0.106, 0.0393, -0.448, -0.264, -0.289, 0.0419, ..., -0.243, 0.116, 0.383, -0.188, 0.357, 0.151, -0.00442, -0.143, -0.198, 0.0431, -0.148, -0.0113, -0.25, 0.445, -0.17, 0.046, 0.0989, 0.263, 0.472, -0.0363, 0.363, 0.147, 0.0354, 0.161, 0.393, 0.386, 0.111, -0.231, 0.167, -0.112],
       [-0.281, 0.352, 0.0868, 0.107, 0.13, -0.698, 0.167, 0.674, -0.398, -0.145, -0.221, -0.562, 0.00476, 0.124, 0.306, -0.186, 0.19, -0.364, -0.0446, -0.808, 0.289, 0.238, 0.117, -0.273, -0.109, 0.0507, -0.507, -0.303, -0.317, 0.0573, ..., -0.277, 0.116, 0.441, -0.209, 0.398, 0.155, -0.022, -0.157, -0.214, 0.0413, -0.17, -0.00122, -0.277, 0.5, -0.176, 0.073, 0.133, 0.297, 0.539, -0.0503, 0.419, 0.162, 0.0421, 0.179, 0.439, 0.439, 0.116, -0.282, 0.187, -0.12],
       [-0.259, 0.331, 0.0801, 0.105, 0.112, -0.647, 0.152, 0.613, -0.368, -0.126, -0.21, -0.513, 0.00483, 0.104, 0.284, -0.176, 0.171, -0.342, -0.0479, -0.741, 0.262, 0.234, 0.109, -0.238, -0.101, 0.0512, -0.471, -0.28, -0.293, 0.0539, ..., -0.259, 0.121, 0.396, -0.203, 0.366, 0.156, -0.0124, -0.146, -0.204, 0.0369, -0.152, -0.00637, -0.256, 0.463, -0.165, 0.0609, 0.108, 0.272, 0.496, -0.0411, 0.376, 0.151, 0.0373, 0.168, 0.41, 0.394, 0.109, -0.255, 0.178, -0.113],
       [-0.192, 0.253, 0.0745, 0.0961, 0.0846, -0.512, 0.121, 0.463, -0.284, -0.102, -0.162, -0.402, -0.00827, 0.0745, 0.214, -0.143, 0.127, -0.27, -0.0474, -0.565, 0.19, 0.19, 0.0812, -0.196, -0.0666, 0.0484, -0.366, -0.204, -0.221, 0.0412, ..., -0.215, 0.114, 0.301, -0.174, 0.278, 0.135, 0.00818, -0.117, -0.158, 0.0173, -0.111, -0.0106, -0.201, 0.359, -0.111, 0.0452, 0.0619, 0.194, 0.384, -0.0241, 0.282, 0.125, 0.0219, 0.131, 0.329, 0.296, 0.0723, -0.206, 0.151, -0.09],
       [-0.244, 0.367, 0.109, 0.141, 0.109, -0.727, 0.17, 0.65, -0.399, -0.141, -0.224, -0.577, -0.00229, 0.0945, 0.303, -0.196, 0.16, -0.388, -0.0747, -0.793, 0.251, 0.266, 0.109, -0.278, -0.0998, 0.0741, -0.513, -0.292, -0.311, 0.0512, ..., -0.309, 0.185, 0.42, -0.254, 0.394, 0.219, 0.0415, -0.184, -0.228, 0.0322, -0.152, -0.0177, -0.281, 0.514, -0.164, 0.0498, 0.0486, 0.263, 0.548, -0.0322, 0.387, 0.188, 0.032, 0.19, 0.48, 0.404, 0.119, -0.278, 0.223, -0.14],

In [210]:
X_arr.shape

(5569, 100)

In [211]:
X[0].shape

(100,)

In [216]:
y = matter[list(map(lambda x: len(x)>0, corpus))]
y = pd.get_dummies(y['label'])
y = y.iloc[:,0].values

In [217]:
y.shape

(5569,)

In [218]:
X[0]

array([-0.185, 0.266, 0.0677, 0.0994, 0.0757, -0.531, 0.137, 0.484, -0.3, -0.0954, -0.17, -0.419, -0.00805, 0.0759, 0.229, -0.144, 0.115, -0.271, -0.0436, -0.591, 0.198, 0.197, 0.0849, -0.194, -0.0864, 0.0365, -0.391, -0.23, -0.246, 0.0339, 0.287, -0.00266, 0.1, -0.244, -0.12, 0.413, 0.00404, -0.142, -0.129, -0.365, 0.151, -0.275, -0.174, 0.0274, 0.258, -0.00861, -0.212, -0.0581, 0.127, 0.141, 0.168, -0.21, -0.0475, 0.0781, -0.0988, 0.183, 0.172, 0.0707, -0.3, 0.149, -0.00184, 0.129, -0.0635, -0.138, -0.338, 0.259, 0.0819, 0.183, -0.36, 0.321, -0.219, 0.124, 0.319, -0.18, 0.302, 0.158, 0.0106, -0.125, -0.183, 0.0361, -0.122, -0.0204, -0.221, 0.381, -0.138, 0.0268, 0.056, 0.214, 0.397, -0.0269, 0.288, 0.14, 0.0308, 0.143, 0.358, 0.312, 0.0882, -0.194, 0.153, -0.102], dtype=float32)

In [222]:
df = pd.DataFrame(X)

In [223]:
df.shape

(5569, 100)

In [225]:
df.head()

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
0,-0.184592,0.265945,0.067658,0.099388,0.075691,-0.531253,0.136795,0.483797,-0.299923,-0.095368,...,0.287663,0.140246,0.030812,0.142732,0.357706,0.312252,0.088198,-0.193591,0.152749,-0.102324
1,-0.161360,0.234984,0.057587,0.093913,0.063258,-0.482799,0.114406,0.435250,-0.257844,-0.069931,...,0.255425,0.119715,0.023342,0.124144,0.313195,0.267893,0.073706,-0.179372,0.130412,-0.088881
2,-0.181119,0.281408,0.090242,0.127531,0.076176,-0.585798,0.135911,0.488971,-0.318031,-0.112826,...,0.280263,0.150754,0.017420,0.147466,0.383674,0.301762,0.065212,-0.224510,0.186908,-0.113004
3,-0.252428,0.364981,0.085585,0.138998,0.099106,-0.720768,0.184494,0.664247,-0.410895,-0.117526,...,0.391259,0.183076,0.035202,0.196476,0.471848,0.424937,0.117290,-0.270976,0.199428,-0.127742
4,-0.220765,0.302509,0.079345,0.111074,0.097712,-0.603831,0.148891,0.562803,-0.344567,-0.109872,...,0.338882,0.147254,0.031981,0.163556,0.393145,0.361122,0.095524,-0.236307,0.167321,-0.117503

In [226]:
X=df ## independent features

In [234]:
df['Output'] = y

In [235]:
df.head()

,0,1,2,3,4,5,6,7,8,9,...,91,92,93,94,95,96,97,98,99,Output
0,-0.184592,0.265945,0.067658,0.099388,0.075691,-0.531253,0.136795,0.483797,-0.299923,-0.095368,...,0.140246,0.030812,0.142732,0.357706,0.312252,0.088198,-0.193591,0.152749,-0.102324,True
1,-0.161360,0.234984,0.057587,0.093913,0.063258,-0.482799,0.114406,0.435250,-0.257844,-0.069931,...,0.119715,0.023342,0.124144,0.313195,0.267893,0.073706,-0.179372,0.130412,-0.088881,True
2,-0.181119,0.281408,0.090242,0.127531,0.076176,-0.585798,0.135911,0.488971,-0.318031,-0.112826,...,0.150754,0.017420,0.147466,0.383674,0.301762,0.065212,-0.224510,0.186908,-0.113004,False
3,-0.252428,0.364981,0.085585,0.138998,0.099106,-0.720768,0.184494,0.664247,-0.410895,-0.117526,...,0.183076,0.035202,0.196476,0.471848,0.424937,0.117290,-0.270976,0.199428,-0.127742,True
4,-0.220765,0.302509,0.079345,0.111074,0.097712,-0.603831,0.148891,0.562803,-0.344567,-0.109872,...,0.147254,0.031981,0.163556,0.393145,0.361122,0.095524,-0.236307,0.167321,-0.117503,True

In [227]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [229]:
X_train.head()

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
333,-0.157210,0.285379,0.089825,0.129050,0.069406,-0.576998,0.140883,0.474550,-0.306439,-0.114140,...,0.269325,0.149882,0.013344,0.133331,0.395747,0.279443,0.064088,-0.205870,0.184504,-0.115701
3184,-0.236862,0.326129,0.073698,0.115385,0.099575,-0.624442,0.156589,0.590492,-0.363903,-0.112604,...,0.355103,0.157125,0.037146,0.171202,0.416547,0.385458,0.107550,-0.231679,0.182435,-0.119187
4036,-0.211485,0.300807,0.075766,0.100920,0.089989,-0.591391,0.144760,0.546673,-0.333269,-0.107960,...,0.329360,0.153912,0.035203,0.154087,0.395036,0.349462,0.099839,-0.218537,0.173565,-0.114865
329,-0.262128,0.342412,0.096526,0.121313,0.124068,-0.696645,0.158042,0.641784,-0.387894,-0.143362,...,0.404158,0.157145,0.028334,0.165368,0.432632,0.407618,0.091742,-0.293875,0.195899,-0.125421
3561,-0.250283,0.324207,0.080380,0.108179,0.112169,-0.635606,0.156755,0.603165,-0.363277,-0.127821,...,0.373097,0.153937,0.038014,0.162670,0.408557,0.386128,0.102865,-0.252776,0.177180,-0.110807

In [231]:
y_train

array([False,  True,  True,  True,  True,  True,  True,  True,  True,  True, False,  True,  True,  True,  True,  True,  True,  True,  True,  True, False, False,  True, False,  True,  True,  True,  True,  True,  True, ...,  True,  True,  True,  True, False, False,  True, False,  True,  True,  True,  True,  True, False,  True,  True,  True,  True,  True, False,  True,  True,  True,  True,  True,  True,  True,  True, False,  True])

In [232]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier()

In [233]:
classifier.fit(X_train, y_train)

RandomForestClassifier()

In [236]:
y_pred = classifier.predict(X_test)

In [237]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, y_pred)

In [238]:
accuracy

0.9649910233393177